export const GCP_DOMAIN_ORCHESTRATION_TASKS = [
  'obsidian-daily',
  'obsidian-sync',
  'regime-compute',
  'model-ic-full-check',
  'verify-v2',
  'weekly-audit',
  'weekly-optuna',
  'monthly-optuna',
  'monthly-strategy-mining',
  'alpha-quality',
  'optuna-queue',
  'lifecycle',
  'backtest',
  'monte-carlo',
  'pbo',
  'model-artifact-candidate-validation',
  'model-artifact-validation',
  'weekly-drift-retrain',
  'external-evidence',
  'allocator-ev-feature-snapshot-backfill',
  'finlab-v4-backfill',
  'finlab-backfill-watchdog',
  'allocator-ev-lifecycle-watchdog',
  'active8-oof-lifecycle',
  'active8-oof-daily',
  'active8-oof-weekly',
  'active8-oof-monthly',
] as const

export {
  runArtifactAutoPromotion,
  runModelIcRollingRefresh,
  runModelIcFullCheck,
  runObsidianDaily,
  runPaperActivePostmarketPromotion,
  runRegimeCompute,
  runVerifyV2,
  runVerifyV2Repair,
  expectedVerifyProducerRunId,
} from './controllerDailyWorkflows'

export {
  finLabBackfillModalTriggerEnabled,
  runExternalEvidenceMaterialize,
  runOptunaQueueProcessor,
  runFinLabV4Backfill,
  runWeeklyAudit,
  runWeeklyAlphaQuality,
  runWeeklyBacktest,
  runWeeklyBacktestEvidenceReconciliation,
  runWeeklyBacktestResearchBundle,
  runWeeklyModelRegistryCheck,
  runActive8OofLifecycle,
  runL4AlphaEvRefresh,
  runAllocatorEvFusionRefresh,
  runOpbArmPriorRefresh,
  runAllocatorEvFeatureSnapshotBackfill,
  runWeeklyModelArtifactCandidateValidation,
  runMonthlyOptunaResearch,
  runMonthlyStrategyMining,
  runWeeklyModelArtifactValidation,
  runWeeklyMonteCarlo,
  runWeeklyOptunaResearch,
  runWeeklyPBO,
  runWeeklyValidationChain,
  runWeeklyDriftDetection,
  runWeeklyDriftRetrain,
  runWeeklyRetrain,
  summarizeWeeklyValidationChain,
  weeklyBacktestResearchBundleEnabled,
} from './controllerResearchWorkflows'
