export const GCP_DOMAIN_ORCHESTRATION_TASKS = [
  'obsidian-daily',
  'obsidian-sync',
  'regime-compute',
  'model-ic-tracker',
  'verify-v2',
  'weekly-audit',
  'weekly-drift-retrain',
  'weekly-optuna',
  'monthly-optuna',
  'alpha-quality',
  'optuna-queue',
  'lifecycle',
  'backtest',
  'monte-carlo',
  'pbo',
  'model-artifact-candidate-validation',
  'model-artifact-validation',
  'finlab-v4-backfill',
  'retrain',
  'monthly-retrain',
] as const

export {
  runModelIcRollingRefresh,
  runModelIcTrackerChain,
  runObsidianDaily,
  runPaperActivePostmarketPromotion,
  runRegimeCompute,
  runVerifyV2,
} from './controllerDailyWorkflows'

export {
  finLabBackfillModalTriggerEnabled,
  runOptunaQueueProcessor,
  runFinLabV4Backfill,
  runWeeklyAudit,
  runWeeklyAlphaQuality,
  runWeeklyBacktest,
  runWeeklyBacktestResearchBundle,
  runWeeklyLifecycleCheck,
  runWeeklyModelArtifactCandidateValidation,
  runMonthlyOptunaResearch,
  runWeeklyModelArtifactValidation,
  runWeeklyMonteCarlo,
  runWeeklyOptunaResearch,
  runWeeklyPBO,
  runWeeklyValidationChain,
  runWeeklyDriftRetrain,
  runWeeklyRetrain,
  summarizeWeeklyValidationChain,
  triggerRetrain,
  weeklyBacktestResearchBundleEnabled,
} from './controllerResearchWorkflows'
