import assert from 'node:assert/strict'
import * as fs from 'node:fs'

const reference = fs.readFileSync('src/lib/selectionReferenceEvidence.ts', 'utf8')
const repair = fs.readFileSync('src/lib/selectionReferenceRepair.ts', 'utf8')
const projection = fs.readFileSync('src/lib/priceHorizonProjection.ts', 'utf8')
const controlRoute = fs.readFileSync('src/routes/adminControlRoutes.ts', 'utf8')
const triggerRoute = fs.readFileSync('src/routes/adminTriggerRoutes.ts', 'utf8')
const domainTasks = fs.readFileSync('src/lib/adminTriggerWorkerDomainTasks.ts', 'utf8')
const finalizer = fs.readFileSync('src/lib/strategyLearning.ts', 'utf8')
const runState = fs.readFileSync('src/lib/strategyLearningRunState.ts', 'utf8')
const orchestrator = fs.readFileSync('src/lib/updateOrchestrator.ts', 'utf8')
const postMarketChain = fs.readFileSync('src/lib/postMarketChain.ts', 'utf8')
const weeklyDag = fs.readFileSync('../frontend/src/components/observability/ExecutionChainPanel.tsx', 'utf8')
const schemaGenerator = fs.readFileSync('scripts/build-domain-schemas.mjs', 'utf8')

assert.match(reference, /resolveReferenceStockIds/)
assert.match(reference, /selection_reference_stock_identity_incomplete/)
assert.match(reference, /stockIds\.get\(clean\(row\.symbol\)\) \?\? null/)
assert.doesNotMatch(reference, /stock_id=CASE/)
assert.match(repair, /repairSelectionReferenceStockIdentities/)
assert.match(repair, /selection_reference_identity_repair_runs_v1/)
assert.match(domainTasks, /'selection-reference-identity-repair': async/)
assert.match(triggerRoute, /'selection-reference-identity-repair'/)
assert.match(domainTasks, /canonical-selection-labels-rebuild/)
assert.match(domainTasks, /projection_only/)
assert.match(domainTasks, /downstream=skipped_by_explicit_projection_only/)
assert.match(domainTasks, /materializeCanonicalSelectionLabelsV4/)
assert.match(domainTasks, /loadCanonicalScreenerRunIds/)
assert.match(domainTasks, /idempotent=/)
assert.doesNotMatch(domainTasks, /canonical_selection_labels_rebuild_empty/)

assert.match(projection, /price_horizon_v4_finlab_canonical_adjusted_price_lineage/)
assert.match(projection, /loadCandidateSignalDates/)
assert.match(projection, /price_horizon_reference_identity_incomplete/)
assert.match(projection, /feature_contract_version IN \(\?, \?\)/)
assert.match(projection, /SELECTION_REFERENCE_MATURE_COMPATIBLE_CONTRACT_VERSIONS/)
assert.doesNotMatch(projection, /identifiedReferenceRows[\s\S]*INSERT INTO price_horizon_projection_status[\s\S]*price_horizon_reference_identity_incomplete/)
assert.match(projection, /const status = 'success'/)
assert.doesNotMatch(projection, /status === 'empty'/)

assert.match(controlRoute, /strategy_redundancy_oof/)
assert.match(controlRoute, /strategy-redundancy-oof-evidence-v1/)
assert.match(controlRoute, /payload\.production_selector !== false/)

const canonicalFinalizer = finalizer.slice(
  finalizer.indexOf('export async function finalizeStrategyLearningEvidenceV5'),
  finalizer.indexOf('export async function runStrategyLearningClosure'),
)
assert(canonicalFinalizer.indexOf('options.beforePromotion') > canonicalFinalizer.indexOf('materializeCanonicalSelectionLabelsV4'))
assert(canonicalFinalizer.indexOf('options.beforePromotion') < canonicalFinalizer.indexOf('const marginalEdge = await runStrategyLearningFinalizerStage'))
assert.match(finalizer, /WITH source_dates AS/)
assert.match(finalizer, /ORDER BY d\.date ASC/)
assert.match(finalizer, /STRATEGY_EVIDENCE_V5_LIVE_FRONTIER_START_DATE/)
assert.match(finalizer, /priorityDate: options\.historicalPriorityDate/)
const directClosure = finalizer.slice(finalizer.indexOf('export async function runStrategyLearningClosure'))
assert.match(directClosure, /strategy_learning_direct_production_mutation_requires_evening_chain_audit/)
assert.match(directClosure, /allowPromotion: false/)
assert.match(directClosure, /persistPolicy: false/)
assert.match(canonicalFinalizer, /adaptiveState: policy\.policy_state/)
assert.match(canonicalFinalizer, /cachedStageResults/)
assert.match(canonicalFinalizer, /onStageTransition/)
assert.match(canonicalFinalizer, /onStageComplete/)
assert.match(canonicalFinalizer, /drainHistoricalStrategyEvidenceV5/)
assert.match(canonicalFinalizer, /repairHistoricalDecisionGrid: options\.repairHistoricalDecisionGrid/)

const strategyQueue = orchestrator.slice(
  orchestrator.indexOf("if (msg.type === 'strategy_learning_materialize')"),
  orchestrator.indexOf("if (msg.type === 'source_readiness_retry')"),
)
assert(strategyQueue.indexOf('auditEveningChainEvidenceClosure') < strategyQueue.indexOf("logSchedulerResult(env.KV, 'evening-chain'"))
assert.match(strategyQueue, /resolveExpectedMatureSignalDate/)
assert.match(strategyQueue, /historicalPriorityDate/)
assert.match(strategyQueue, /drainMatureSelectionEvidence/)
assert.match(strategyQueue, /repairHistoricalStrategyDecisionGrid/)
assert.match(strategyQueue, /v4-canonical-matrix-parity/)
assert.match(strategyQueue, /assertCanonicalStrategyDecisionGridParity/)
assert.match(domainTasks, /evening_chain_evidence_closure_callback_missing/)
assert.match(domainTasks, /failStrategyLearningRun/)
assert.match(runState, /status='error'.*completed_at=NULL/s)
assert.match(runState, /status='running'.*completed_at=NULL/s)
assert.match(runState, /markStrategyLearningRunFinalized/)
assert.match(runState, /status='success'.*completed_at=CURRENT_TIMESTAMP/s)
const completeRunState = runState.slice(runState.indexOf('export async function completeStrategyLearningRun'), runState.indexOf('export async function markStrategyLearningRunFinalized'))
assert.match(completeRunState, /durableCoverageComplete/)
assert.match(completeRunState, /if \(!durableCoverageComplete\)/)
assert(completeRunState.indexOf('durableCoverageComplete') < completeRunState.indexOf('SELECT COUNT(DISTINCT d.symbol)'))
assert.match(strategyQueue, /materializationAlreadyComplete/)
assert.match(strategyQueue, /deferStrategyLearningFinalizer/)
assert.match(strategyQueue, /markStrategyLearningRunFinalized/)
assert.match(domainTasks, /deferStrategyLearningFinalizer/)
assert.match(domainTasks, /markStrategyLearningRunFinalized/)
assert.match(strategyQueue, /finalizerAttemptId/)
assert.match(strategyQueue, /leaseOwner = `\$\{canonicalRunId\}:lease:\$\{crypto\.randomUUID\(\)\}`/)
assert.match(strategyQueue, /durable finalizer queued/)
assert.match(strategyQueue, /policyMutationAllowed: msg\.policyMutationAllowed/)
assert.match(strategyQueue, /allowPromotion: policyMutationAllowed/)
assert.match(strategyQueue, /persistPolicy: policyMutationAllowed/)
assert.match(strategyQueue, /strategy_learning_lease_retry_exhausted/)
assert.match(strategyQueue, /lease busy; durable retry scheduled/)
assert.match(strategyQueue, /finalizerCacheMode = policyMutationAllowed \? 'policy-mutation' : 'evidence-only'/)
assert.match(strategyQueue, /expirationTtl: 7 \* 24 \* 3600/)
assert.match(strategyQueue, /cachedStageResults: finalizerStageResults/)
assert.match(strategyQueue, /onStageComplete: persistFinalizerStage/)
assert.match(strategyQueue, /root chain blocked by strategy-learning evidence audit/)
assert.match(domainTasks, /manual-finalize/)
assert.match(domainTasks, /root chain blocked by strategy-learning evidence audit/)

const strategyEnqueue = postMarketChain.slice(
  postMarketChain.indexOf("results.push(await logChainedTask(env, ctx, 'strategy-learning'"),
  postMarketChain.indexOf('await logChainSummary', postMarketChain.indexOf("results.push(await logChainedTask(env, ctx, 'strategy-learning'")),
)
assert.match(strategyEnqueue, /critical: true/)
assert.match(postMarketChain, /waitingForQueuedStrategyLearning/)
assert.match(postMarketChain, /status = hasError \? 'error' : waitingForQueuedStrategyLearning \? 'running' : 'success'/)


const weekly = weeklyDag.slice(
  weeklyDag.indexOf("id: 'weekly'"),
  weeklyDag.indexOf("id: 'monthly'"),
)
assert.match(weekly, /\['weekly-backtest', 'alpha-quality', 'active8-oof-weekly'\]/)
assert.match(weekly, /\['weekly-optuna', 'sector-leaders'\]/)
assert.match(weekly, /\['adaptive-meta-policy-replay', 's12-smcvwap-calibration', 'linucb-multiplier-replay'\]/)
assert.match(weekly, /\['weekly-cleanup'\]/)
assert.doesNotMatch(weekly, /\['weekly-drift-retrain'\]/)

assert.match(schemaGenerator, /CREATE\(\?:\\s\+UNIQUE\)\?\\s\+INDEX/)
