import assert from 'node:assert/strict'
import fs from 'node:fs'

const registry = fs.readFileSync('src/lib/expectedReturnServingRegistry.ts', 'utf8')
const servingState = fs.readFileSync('src/lib/expectedReturnServingState.ts', 'utf8')
const promotionRoute = fs.readFileSync('src/routes/adminConfigCoreRoutes.ts', 'utf8')
const walkForward = fs.readFileSync('../ml-controller/routers/walk_forward.py', 'utf8')
const orchestrator = fs.readFileSync('src/lib/updateOrchestrator.ts', 'utf8')
const triggerTasks = fs.readFileSync('src/lib/adminTriggerGcpTasks.ts', 'utf8')
const migration = fs.readFileSync('migrations/0087_expected_return_serving_baseline.sql', 'utf8')
const contractMigration = fs.readFileSync('migrations/0104_expected_return_v5_v14_baseline_pointer_closure.sql', 'utf8')

assert(registry.includes('FROM model_champion_pointers p'))
assert(registry.includes('LEFT JOIN expected_return_artifact_payloads x'))
assert(registry.includes('champion_payload_checksum_mismatch'))
assert(registry.includes('legacy_config_fallback_blocked'))
assert(registry.includes('await db.batch(['))
assert(registry.includes('INSERT INTO model_champion_pointers'))
assert(registry.includes('INSERT OR IGNORE INTO model_champion_history'))
assert(registry.includes('offline_gate_decision !== \'PASS\''))
assert(registry.includes("candidate_cohort.status = 'ready'"))
assert(registry.includes('ORDER BY candidate.max_date DESC, candidate.updated_at DESC, candidate.cohort_id DESC'))
assert(!registry.includes('SELECT artifact_kind, MAX(max_date) AS max_date'))
assert(registry.includes('champion_payload_table_version_mismatch'))
assert(registry.includes("candidate_type IN ('l4_alpha_ev_refresh', 'allocator_ev_fusion_refresh')"))
assert(registry.includes('ORDER BY source_run_date DESC, updated_at DESC, version DESC, artifact_id DESC'))
assert(registry.includes('input.artifactId.trim()'))
assert(registry.includes('expected_return_registry_artifact_id_checksum_mismatch'))
assert(registry.includes('expected_return_registry_artifact_path_checksum_mismatch'))
assert(!registry.includes('const artifactId = `${input.owner}:${modelVersion}`'))
assert(registry.includes('production_candidate_not_champion_pointer'))
assert(registry.includes('resolveExpectedOofCoverageDates'))
assert(registry.includes('awaiting_current_close_oof_materialization'))
assert(registry.includes('LIMIT 7'))
assert(registry.includes('active8_oof_forward_extension_coverage'))
assert(registry.includes("coverage_status = 'verified'"))
assert(registry.includes('current.promotion_eligible = 0'))
assert(registry.includes('candidate.artifact_kind = current.artifact_kind'))
assert(registry.includes('oof_base_max_dates: oofBaseMaxDates'))
assert(registry.includes('oof_shadow_max_dates: oofShadowMaxDates'))

assert(servingState.includes("state: 'production_primary' | 'no_eligible_owner'"))
assert(servingState.includes("sourceOfTruth: 'model_champion_pointers+artifact_payloads'"))
assert(servingState.includes("artifact.serving_mode === 'abstention_baseline'"))
assert(servingState.includes("artifact_state === 'safe_abstention'"))
assert(servingState.includes('alpha_champion_not_promoted'))
assert(!servingState.includes('abstention_baseline_not_serving'))
assert(servingState.includes('policy_value_head_count_not_one'))

const configGetStart = promotionRoute.indexOf("adminConfigCoreRoutes.get('/api/admin/config'")
const configGetEnd = promotionRoute.indexOf("adminConfigCoreRoutes.put('/api/admin/config'", configGetStart)
const configGetBody = promotionRoute.slice(configGetStart, configGetEnd)
assert(promotionRoute.includes("import { databaseForDataDomain } from '../lib/dataDomainRegistry'"))
assert(configGetBody.includes("const learningDb = databaseForDataDomain(c.env, 'learning')"))
assert(!configGetBody.includes('hydrateExpectedReturnConfigFromPointers(c.env.DB'))
const promoteStart = promotionRoute.indexOf("adminConfigCoreRoutes.post('/api/admin/config/expected-return/promote'")
const promoteEnd = promotionRoute.indexOf("adminConfigCoreRoutes.post('/api/admin/config/push-defaults'", promoteStart)
const promoteBody = promotionRoute.slice(promoteStart, promoteEnd)
assert(promoteBody.includes("const learningDb = databaseForDataDomain(c.env, 'learning')"))
for (const call of [
  'hydrateExpectedReturnConfigFromPointers', 'recordParameterCandidateFromSandbox',
  'recordParameterCandidateEvidence', 'validatePromotionPacketForProd',
  'commitExpectedReturnChampion', 'markParameterCandidatePromoted',
]) {
  assert(promoteBody.includes(`${call}(learningDb`), `${call} must use the learning domain database`)
}
assert(promoteBody.includes('artifact_id: String(rawCandidate.artifact_id'))
assert(promoteBody.includes('artifactId: candidate.artifact_id'))
assert.equal((walkForward.match(/"artifact_id": \(candidate_artifacts\.get\(/g) ?? []).length, 2)
assert(!promoteBody.includes('c.env.DB'))
assert(
  promoteBody.indexOf('pointerCommit = await commitExpectedReturnChampion')
    < promoteBody.indexOf('snapshot = await setTradingConfig'),
)
assert(promoteBody.includes('D1 pointer + payload is the serving authority'))
assert(
  promoteBody.indexOf('hydrateExpectedReturnConfigFromPointers') < promoteBody.indexOf('const plan = buildExpectedReturnOwnerPromotionPlan'),
)

const readinessStart = orchestrator.indexOf('async function runDailyAllocatorEvReadiness')
const readinessEnd = orchestrator.indexOf('async function continuePostScreenerPipeline', readinessStart)
const readinessBody = orchestrator.slice(readinessStart, readinessEnd)
assert(readinessBody.includes('inspectExpectedReturnLifecycleHealth'))
assert(!readinessBody.includes('runL4AlphaEvRefresh'))
assert(!readinessBody.includes('runAllocatorEvFusionRefresh'))
assert(readinessBody.includes('required_oof_max_date=${health.expected_mature_signal_date'))
assert(readinessBody.includes('newly_mature_signal_date=${health.newly_mature_signal_date'))
assert(readinessBody.includes("state: 'ready' | 'degraded' | 'safe_abstain' | 'fatal'"))
assert(readinessBody.includes("servingState.state === 'production_primary'"))
assert(readinessBody.includes("servingState.action_gate === 'expected_return_owner'"))
assert(readinessBody.includes("status: state === 'fatal' ? 'error' : 'success'"))
assert(!readinessBody.includes('return { ok: true, summary }'))
assert(orchestrator.includes('export async function runDailyAllocatorEvReadiness'))
assert(triggerTasks.includes("'allocator-ev-readiness': async () =>"))
assert(triggerTasks.includes('return runDailyAllocatorEvReadiness(c.env, requestedRunDate() || twToday())'))

for (const owner of ['l4_alpha_ev', 'allocator_ev_fusion']) {
  assert(migration.includes(`'${owner}'`))
}
assert.equal((migration.match(/contract_valid_abstention_bootstrap/g) ?? []).length, 2)
assert.equal((migration.match(/ON CONFLICT\(model_name\) DO NOTHING/g) ?? []).length, 2)
assert(migration.includes("serving_mode TEXT NOT NULL CHECK(serving_mode IN ('alpha','abstention_baseline'))"))
assert(migration.includes("promotion_decision = 'baseline_retained_for_rollback'"))
assert(migration.includes('pointer.champion_artifact_id != model_artifact_registry.artifact_id'))
assert(migration.includes('UPDATE model_champion_history'))
assert(migration.includes('SET retired_at = COALESCE(retired_at, CURRENT_TIMESTAMP)'))
assert(contractMigration.includes('l4-alpha-ev-contract-v5'))
assert(contractMigration.includes('allocator-ev-fusion-contract-v14'))
assert(contractMigration.includes("champion_artifact_id = 'l4_alpha_ev:l4-alpha-ev-ridge-v5-sector-abstention-baseline-v1'"))
assert(contractMigration.includes("champion_artifact_id = 'allocator_ev_fusion:allocator-ev-fusion-residual-v14-abstention-baseline-v1'"))
assert(!contractMigration.includes('ON CONFLICT(model_name) DO UPDATE'))

console.log('expectedReturnServingRegistryContract tests passed')
