const fs = require('fs')
const path = require('path')

export {}

function assert(condition: unknown, message: string): void {
  if (!condition) throw new Error(message)
}

const root = path.join(process.cwd(), '..')
const frontend = path.join(root, 'frontend', 'src')

const queryPolicyPath = path.join(frontend, 'lib', 'queryPolicy.ts')
const virtualListPath = path.join(frontend, 'components', 'performance', 'VirtualizedList.tsx')
const mainSource = fs.readFileSync(path.join(frontend, 'main.tsx'), 'utf8')
const appSource = fs.readFileSync(path.join(frontend, 'App.tsx'), 'utf8')
const appShellSource = fs.readFileSync(path.join(frontend, 'components', 'AppShell.tsx'), 'utf8')
const workstationSource = fs.readFileSync(path.join(frontend, 'components', 'workstation', 'WorkstationChrome.tsx'), 'utf8')
const cssSource = fs.readFileSync(path.join(frontend, 'index.css'), 'utf8')
const dailyPanelV2Path = path.join(frontend, 'components', 'DailyRecommendationPanelV2.tsx')
const homeSource = fs.readFileSync(path.join(frontend, 'pages', 'DailyFocusHomePage.tsx'), 'utf8')
const legacyStockReportRedirectSource = fs.readFileSync(path.join(frontend, 'pages', 'LegacyStockReportRedirectPage.tsx'), 'utf8')
const stockAIReportSource = fs.readFileSync(path.join(frontend, 'components', 'StockAIReport.tsx'), 'utf8')
const dashboardV4ChartSource = fs.readFileSync(path.join(frontend, 'components', 'charts', 'DashboardV4LightweightChart.tsx'), 'utf8')
const botSource = fs.readFileSync(path.join(frontend, 'pages', 'BotDashboard.tsx'), 'utf8')
const strategyLabSource = fs.readFileSync(path.join(frontend, 'pages', 'StrategyLabPage.tsx'), 'utf8')
const strategyChartSource = fs.readFileSync(path.join(frontend, 'components', 'charts', 'StrategyExperimentTimeline.tsx'), 'utf8')
const modelPoolSource = fs.readFileSync(path.join(frontend, 'pages', 'ModelPoolPage.tsx'), 'utf8')
const pipelineSource = fs.readFileSync(path.join(frontend, 'pages', 'PipelinePage.tsx'), 'utf8')
const inspectorSource = fs.readFileSync(path.join(frontend, 'pages', 'ModelPoolInspectorPage.tsx'), 'utf8')
const schedulerSource = fs.readFileSync(path.join(frontend, 'pages', 'SchedulerPage.tsx'), 'utf8')
const schedulerChartSource = fs.readFileSync(path.join(frontend, 'components', 'charts', 'SchedulerCadenceChart.tsx'), 'utf8')
const dataQualitySource = fs.readFileSync(path.join(frontend, 'pages', 'DataQualityPage.tsx'), 'utf8')
const dataQualityChartSource = fs.readFileSync(path.join(frontend, 'components', 'charts', 'DataQualityTrendChart.tsx'), 'utf8')
const dashboardSource = fs.readFileSync(path.join(frontend, 'pages', 'Dashboard.tsx'), 'utf8')
const obsSource = fs.readFileSync(path.join(frontend, 'pages', 'ObservabilityPage.tsx'), 'utf8')
const apiSource = fs.readFileSync(path.join(frontend, 'lib', 'api.ts'), 'utf8')
const recommendationRouteSource = fs.readFileSync(path.join(root, 'worker', 'src', 'routes', 'other.ts'), 'utf8')
const viteConfigSource = fs.readFileSync(path.join(root, 'frontend', 'vite.config.ts'), 'utf8')

assert(fs.existsSync(queryPolicyPath), 'frontend must centralize React Query cache and prefetch policy')
assert(fs.existsSync(virtualListPath), 'frontend must provide a reusable virtualized list for large OBS/funnel tables')
assert(!fs.existsSync(dailyPanelV2Path), 'retired DailyRecommendationPanelV2 must not remain as a duplicate detailed recommendation surface')

const queryPolicy = fs.existsSync(queryPolicyPath) ? fs.readFileSync(queryPolicyPath, 'utf8') : ''
assert(queryPolicy.includes('refetchOnWindowFocus: false'), 'query policy must stop focus-driven duplicate refetches')
assert(queryPolicy.includes('gcTime'), 'query policy must tune cache retention for page switches')
assert(queryPolicy.includes('prefetchWorkstationRoute'), 'query policy must expose route-level prefetch for heavy workstations')
assert(queryPolicy.includes('recommendationDailyKey'), 'query policy must own daily recommendation cache keys')
assert(queryPolicy.includes('selectRecommendationLanes'), 'query policy must expose server-payload lane selector')

assert(mainSource.includes('defaultQueryOptions'), 'main QueryClient must use centralized default query options')
assert(appShellSource.includes('useQueryClient'), 'AppShell sidebar must prefetch route data before navigation')
assert(appShellSource.includes('prefetchWorkstationRoute'), 'AppShell sidebar must use the centralized route prefetch contract')
assert(appShellSource.includes('data-sv-surface={surface}'), 'AppShell must expose route-level surface themes for visual differentiation')
assert(cssSource.includes('[data-sv-surface="home"]') && cssSource.includes('[data-sv-surface="stock"]') && cssSource.includes('[data-sv-surface="bot"]') && cssSource.includes('[data-sv-surface="strategy"]') && cssSource.includes('[data-sv-surface="model"]') && cssSource.includes('[data-sv-surface="ops"]'), 'Frontend CSS must define differentiated Home/Stock/Bot/StrategyLab/ModelPool/OBS surface themes')
assert(workstationSource.includes('var(--sv-accent)') && workstationSource.includes('var(--sv-panel-border)'), 'Workstation primitives must consume semantic surface tokens instead of one fixed palette')
assert(homeSource.includes('sv-content-card') && homeSource.includes('sv-accent-text'), 'Home public visualization surface must consume route-level surface tokens')
assert(homeSource.includes('var(--sv-accent-border)') && !homeSource.includes('border-[#d6a85f]/30 text-[#f1c16f]'), 'Home refresh action must use the public route accent instead of the retired amber-only styling')
assert(appShellSource.includes("currentPath.startsWith('/stock/')"), 'Formal stock workspace must receive the stock detail route surface')
assert(!appShellSource.includes("currentPath.startsWith('/report/')"), 'Legacy report route must not remain the formal stock surface owner')
assert(appSource.includes('path="/report/:symbol"') && appSource.includes('<LegacyStockReportRedirectPage />'), 'Legacy report URLs must redirect instead of owning a duplicate stock report surface')
assert(legacyStockReportRedirectSource.includes("LEGACY_STOCK_REPORT_REDIRECT_TARGET = '/'") && legacyStockReportRedirectSource.includes('<Redirect to={LEGACY_STOCK_REPORT_REDIRECT_TARGET} replace />'), 'Legacy stock report redirect must return retired symbol URLs to Home')
assert(!legacyStockReportRedirectSource.includes('stocksApi.search') && !legacyStockReportRedirectSource.includes('useQuery'), 'Legacy stock report redirect must not depend on stock search or expose an old loading shell')
assert(dashboardSource.includes('DashboardV4LightweightChart') && dashboardSource.includes('StockAIReport'), 'Dashboard stock selection workspace must own chart and AI analysis tabs')
assert(stockAIReportSource.includes('StockAIReport') && stockAIReportSource.includes('buildScoreBreakdownViewModel'), 'Current stock AI report must live in StockAIReport')
assert(dashboardV4ChartSource.includes('Dashboard V4 / Lightweight Charts') && dashboardV4ChartSource.includes('sv-content-card'), 'Dashboard V4 chart must consume active route surface card tokens')
assert(dashboardV4ChartSource.includes('data-testid="dashboard-v4-chart-empty-state"'), 'Dashboard V4 chart unavailable state must be a compact visible data-state surface')
assert(!dashboardV4ChartSource.includes('min-h-[460px] place-items-center rounded-xl px-4 text-center'), 'Dashboard V4 chart unavailable state must not reserve full chart height when no packet exists')
assert(modelPoolSource.includes('ModelGovernanceVisualMap') && modelPoolSource.includes('sv-content-card'), 'ModelPool governance visual map must consume route-level surface tokens')
assert(modelPoolSource.includes('data-testid="modelpool-governance-drilldown"') && modelPoolSource.includes('sv-disclosure'), 'ModelPool governance drilldown must consume route-level disclosure tokens')
assert(modelPoolSource.includes('var(--sv-accent-border)') && !modelPoolSource.includes('border-[#d6a85f]/30 text-[#f1c16f]'), 'ModelPool actions must use the governance route accent instead of the retired amber-only styling')
assert(cssSource.includes('.sv-content-card') && botSource.includes('sv-content-card'), 'Bot page-level visual summary cards must consume surface tokens')
assert(cssSource.includes('.sv-content-card-selected') && botSource.includes('sv-content-card-selected'), 'Bot selected execution/staging cards must consume route-level selected surface tokens')
assert(cssSource.includes('.sv-surface-chip-accent') && botSource.includes('sv-surface-chip-accent'), 'Bot private rank chips must consume route-level accent tokens')
assert(cssSource.includes('.sv-login-panel') && botSource.includes('sv-login-panel'), 'Bot logged-out private preview must consume surface tokens')
assert(appShellSource.includes("currentPath.startsWith('/strategy-lab')"), 'Strategy Lab must receive a dedicated research route surface')
assert(strategyLabSource.includes('data-testid="strategy-signal-board"') && strategyLabSource.includes('StrategyExperimentTimeline'), 'Strategy Lab must visualize research health before dense controls')
assert(strategyLabSource.includes('WorkstationPageTitle') && strategyLabSource.includes('sv-content-card') && strategyLabSource.includes('sv-accent-text'), 'Strategy Lab must consume research surface tokens')
assert(strategyChartSource.includes('Strategy Visual Workbench') && strategyChartSource.includes('sv-content-card'), 'Strategy chart workbench must consume surface card tokens')
assert(pipelineSource.includes('pipeline-compression-visual') && pipelineSource.includes('sv-content-card-selected'), 'Pipeline compression visual must consume route-level surface tokens')
assert(pipelineSource.includes('sv-page-title') && pipelineSource.includes('sv-disclosure'), 'Pipeline header and drilldown surfaces must consume route-level surface tokens')
assert(inspectorSource.includes('visual-inspector-summary') && inspectorSource.includes('sv-content-card-selected'), 'Inspector visual summary must consume route-level selected surface tokens')
assert(inspectorSource.includes('sv-surface-input') && inspectorSource.includes('sv-data-table-head'), 'Inspector search and raw table must consume route-level surface tokens')
assert(appShellSource.includes("currentPath.startsWith('/obs')") && appShellSource.includes("currentPath.startsWith('/scheduler')") && appShellSource.includes("currentPath.startsWith('/data-quality')"), 'OBS and specialist drilldowns must share an operations route surface')
assert(obsSource.includes('data-testid="obs-signal-board"') && obsSource.includes('Scheduler SLO') && obsSource.includes('Deploy Gate'), 'OBS must visualize operational state before dense scheduler/data-quality rows')
assert(obsSource.includes('sv-content-card') && obsSource.includes('sv-disclosure'), 'OBS visual summaries and compact rows must consume operations surface tokens')
assert(schedulerSource.includes('data-testid="scheduler-signal-board"') && schedulerSource.includes('SchedulerCadenceChart'), 'Scheduler drilldown must visualize run health before dense virtualized rows')
assert(schedulerSource.includes('sv-content-card') && schedulerSource.includes('sv-muted-text') && schedulerSource.includes('sv-accent-text'), 'Scheduler drilldown must consume operations surface tokens')
assert(schedulerChartSource.includes('Scheduler Visual Workbench') && schedulerChartSource.includes('sv-content-card'), 'Scheduler chart workbench must consume surface card tokens')
assert(dataQualitySource.includes('data-testid="data-quality-signal-board"') && dataQualitySource.includes('DataQualityTrendChart'), 'Data Quality drilldown must visualize quality health before dense check rows')
assert(dataQualitySource.includes('sv-content-card') && dataQualitySource.includes('sv-muted-text') && dataQualitySource.includes('sv-accent-text'), 'Data Quality drilldown must consume operations surface tokens')
assert(dataQualityChartSource.includes('Data Quality Visual Workbench') && dataQualityChartSource.includes('sv-content-card'), 'Data Quality chart workbench must consume surface card tokens')
assert(dataQualityChartSource.includes('Current API data is a snapshot, not a historical trend'), 'Data Quality chart must avoid implying historical trend data')
assert(apiSource.includes("view?: 'full' | 'card'"), 'recommendation API client must expose card-view payload slimming')
assert(botSource.includes('PreDebateStagingPool'), 'Bot must own the private pre-debate staging surface')
assert(botSource.includes('shouldShowPreDebateStaging'), 'Bot must gate candidate staging by execution lifecycle state')
assert(botSource.includes('bot-position-risk-map'), 'Bot must summarize holdings visually before exposing position tables')
assert(botSource.includes('bot-position-table-drilldown'), 'Bot position table must stay behind a drilldown disclosure')
assert(botSource.includes('bot-order-flow-summary'), 'Bot must summarize order flow visually before exposing order tables')
assert(botSource.includes('bot-orders-table-drilldown'), 'Bot order table must stay behind a drilldown disclosure')
assert(botSource.includes('recommendationDailyKey'), 'Bot private staging must share the canonical recommendation query key')
assert(botSource.includes('selectRecommendationLanes'), 'Bot private staging must avoid recomputing payload lanes ad hoc')
assert(botSource.includes("view: 'card'"), 'Bot private staging must request the compact card payload')
assert(botSource.includes('staleTime: queryTtl.intraday'), 'Bot private staging must refresh quickly after historical reruns publish newer rows')
assert(botSource.includes("refetchOnMount: 'always'"), 'Bot private staging must not keep an old payload across route returns')
assert(dashboardSource.includes('DailyFocusRoutingPanel'), 'Dashboard should route users to Home/Bot instead of duplicating daily recommendations')
assert(!dashboardSource.includes('DailyRecommendationPanelV2'), 'Dashboard must not render the retired detailed recommendation panel')
assert(!dashboardSource.includes('RecommendationCardClean'), 'Dashboard must not render detailed recommendation cards in its empty state')
assert(queryPolicy.includes("href === '/bot'") && queryPolicy.includes("recommendationDailyKey(date), queryFn: () => recommendationsApi.daily(undefined, { view: 'card' }), staleTime: queryTtl.intraday"), 'Bot route prefetch must warm compact private staging without a long-lived fallback payload')
assert(!obsSource.includes('VirtualizedList'), 'OBS overview must avoid nested virtual scroll for small incident/job lists')
assert(!obsSource.includes('scrollIntoView({ behavior'), 'OBS incident open must not trigger smooth-scroll jank on every click')
assert(recommendationRouteSource.includes('compactRecommendationForCard'), 'Worker daily recommendations must support compact card payloads')
assert(recommendationRouteSource.includes("c.req.query('view') === 'card'"), 'Worker must make payload slimming an explicit request contract')
assert(viteConfigSource.includes('resolveBuildId'), 'Vite config must derive a build id for production cache busting')
assert(viteConfigSource.includes('entryFileNames') && viteConfigSource.includes('chunkFileNames'), 'Vite output filenames must include build id to prevent stale PWA chunks')
assert(viteConfigSource.includes('VITE_BUILD_ID'), 'Frontend must expose build id for deployment diagnostics')
