import * as fs from 'node:fs'
import * as path from 'node:path'

export {}

function assert(condition: unknown, message: string): void {
  if (!condition) throw new Error(message)
}

const root = path.join(process.cwd(), '..')
const frontend = path.join(root, 'frontend', 'src')
const appShell = fs.readFileSync(path.join(frontend, 'components', 'AppShell.tsx'), 'utf8')
const obs = fs.readFileSync(path.join(frontend, 'pages', 'ObservabilityPage.tsx'), 'utf8')
const executionChain = fs.readFileSync(path.join(frontend, 'components', 'observability', 'ExecutionChainPanel.tsx'), 'utf8')
const executionChainCss = fs.readFileSync(path.join(frontend, 'components', 'observability', 'ExecutionChainPanel.css'), 'utf8')
const standaloneJobs = fs.readFileSync(path.join(frontend, 'components', 'observability', 'StandaloneJobRegistry.tsx'), 'utf8')
const standaloneJobsCss = fs.readFileSync(path.join(frontend, 'components', 'observability', 'StandaloneJobRegistry.css'), 'utf8')
const scheduler = fs.readFileSync(path.join(frontend, 'pages', 'SchedulerPage.tsx'), 'utf8')
const dataQuality = fs.readFileSync(path.join(frontend, 'pages', 'DataQualityPage.tsx'), 'utf8')

assert(appShell.includes("href: '/obs'"), 'OBS must remain the main observability entry in sidebar')
assert(appShell.includes("href: '/model-pool'"), 'Model Pool must remain a specialist lifecycle explorer in sidebar')
assert(!appShell.includes("href: '/scheduler'"), 'Scheduler must remain an OBS drilldown rather than a primary sidebar item')
assert(!appShell.includes("href: '/data-quality'"), 'Data Quality must remain an OBS drilldown rather than a primary sidebar item')

assert(!obs.includes('Incident Inbox'), 'OBS must not restore the duplicate incident inbox')
assert(!obs.includes('Selected Incident Detail'), 'OBS must not restore the old selected-incident pane')
assert(!obs.includes('Reliability Map'), 'OBS must not render the low-signal reliability map')
assert(obs.includes('computeDataQualityScore'), 'OBS Data Quality score must be computed from checks')
assert(!obs.includes('setActiveTab'), 'OBS must not expose fake content tabs')

assert(obs.includes('ExecutionChainPanel'), 'OBS must render the callback-driven execution chain')
assert(!obs.includes('<ReadinessFlowMap'), 'OBS must not render the old readiness step-card grid')
assert(!obs.includes('<SchedulerReadinessGroupBoard'), 'OBS must not render the old scheduler card wall')
assert(!obs.includes('<SchedulerShortcutDeck'), 'OBS Source Gates must not duplicate scheduler scope cards')
assert(executionChain.includes("['screener'],") && executionChain.includes("['regime-compute'],") && executionChain.includes("['allocator-ev-readiness'],") && !executionChain.includes("['s12-structure-snapshot'],"), 'daily execution chain must expose screener -> regime -> allocator without a duplicate S12 evening stage')
assert(!executionChain.includes("id: 'daily_ops'"), 'independent scheduled roots must not be represented as a fake daily chain')
assert(executionChain.includes("id: 'weekly'") && executionChain.includes('Monthly artifact'), 'weekly research and monthly artifact cadences must each own an explicit lifecycle')
assert(executionChain.includes("['morning-setup'],") && executionChain.includes("['pre-market-warmup'],") && executionChain.includes("['intraday-check'],") && executionChain.includes("['eod-exit'],") && executionChain.includes("['post-close-price-refresh'],") && executionChain.includes("['daily-snapshot'],"), 'intraday main line must preserve verified readiness and post-close dependencies')
assert(executionChain.includes("id: 'premarket-context'") && executionChain.includes("['us-leading', 'news-analyst']") && executionChain.includes("['morning-briefing']") && executionChain.includes("relation: 'evidence'"), 'pre-market evidence producers must render as a non-gating Intraday branch')
assert(executionChain.includes("id: 'intraday-rescore-spots'") && executionChain.includes("['rescore-10']") && executionChain.includes("['rescore-11']") && executionChain.includes("['rescore-12']") && executionChain.includes("['rescore-1230']") && executionChain.includes("relation: 'shared_context'"), 'Intraday Re-score must expose four independent status-bearing spots')
assert(executionChain.includes('function scopeStageIds') && executionChain.includes('scope.branches ?? []'), 'branch jobs must participate in mapped scheduler coverage')
assert(executionChain.includes("'context with' : 'shares inputs with'") && executionChain.includes('${mainStageCount} main') && executionChain.includes('${branchStageCount} branch'), 'branch UI must state shared-input semantics and avoid a fake sequential phase number')
assert(!executionChain.includes("'intraday-rescore': {") && !executionChain.includes('Next up') && !executionChain.includes('obs-chain__detail--next'), 'legacy aggregate re-score and redundant Next Up detail must stay removed')
assert(executionChainCss.includes('.obs-chain__branches') && executionChainCss.includes('.obs-chain__branch-sequence') && executionChainCss.includes('grid-template-columns: minmax(0,1fr)'), 'branch layout and single-column detail must have explicit styling')
assert(executionChain.includes("['model-ic-rolling']") && !executionChain.includes('buildScopedJobMap') && !executionChain.includes('model-ic-tracker'), 'daily chain must consume the isolated rolling identity without timestamp inference')
assert(executionChain.includes("noop: 'Checked · no action'"), 'executed intraday no-op checks must not render as unexecuted skips')
assert(executionChain.includes('isAllocatorSafeAbstention'), 'Allocator model-quality abstention must be distinguished from infrastructure failure')
assert(executionChain.includes('no_validated_expected_return_lane|no_eligible_owner'), 'safe-abstention classification must use explicit serving-owner evidence')
assert(executionChain.includes('BUY/allocation remains fail-closed'), 'safe abstention must preserve the production fail-closed contract')
assert(executionChain.includes("job.lastStatus === 'sleep') return 'out_of_window'") && executionChain.includes("out_of_window: 'Not in window'"), 'sleep must render as Not in window rather than Not started')
assert(executionChainCss.includes('.obs-chain__stage.is-out_of_window'), 'out-of-window stages must retain neutral chain styling')
assert(executionChain.includes('Weekly validation & research chain'), 'weekly execution topology must be mapped')
assert(executionChain.includes("['allocator-ev-feature-snapshot-backfill']") && !executionChain.includes("['active8-oof-daily']"), 'daily evidence callback must be mapped while the independent Active-8 scheduler stays in Pipeline support')
assert(executionChain.includes("job.lastRunBasis === 'started'") && executionChain.includes("Started '"), 'callback containers must label their durable start time instead of implying a reversed execution order')
assert(executionChain.includes('StandaloneJobRegistry') && executionChain.includes('MAPPED_JOB_IDS'), 'execution chain must route non-chain jobs into the registry')
assert(standaloneJobs.includes('.filter((job) => !mappedJobIds.has(job.id))'), 'all unmapped scheduler API jobs must remain visible')
assert(standaloneJobs.includes('Standalone root') && standaloneJobs.includes('Topology missing'), 'registry must distinguish independent jobs from true topology gaps')
assert(standaloneJobs.includes('Consolidation tracked'), 'governed merge/evidence candidates must not be labeled as missing topology')
assert(standaloneJobs.includes('{jobs.length} / {jobs.length} accounted'), 'OBS must account for the full scheduler API universe')
assert(standaloneJobsCss.includes('.obs-standalone__group-card') && standaloneJobsCss.includes('.obs-standalone__job-grid') && !standaloneJobsCss.includes('.obs-standalone__rows'), 'standalone registry must preserve the grouped-card presentation')
assert(standaloneJobs.includes("['weekly', 'pipeline_chain', 'daily', 'intraday', 'monthly']") && standaloneJobsCss.includes("[aria-label='Weekly operations'] { grid-column: span 4;") && standaloneJobsCss.includes("[aria-label='Pipeline support'] { grid-column: span 2;") && standaloneJobsCss.includes("[aria-label='Daily operations'] { grid-column: span 4;"), 'standalone desktop top row must stay Weekly 4 / Pipeline 2 / Daily 4')
assert(executionChain.includes("lastStatus === 'running') ? 3_000 : 15_000"), 'callback sync must be 3s while running and 15s while idle')
assert(executionChain.includes('previousStatuses') && executionChain.includes('justCompleted'), 'final callback must trigger a completed-stage transition')
assert(executionChainCss.includes('@keyframes obs-running-orbit'), 'running stage must have an attention animation')
assert(executionChainCss.includes('@keyframes obs-progress-flow'), 'Overall progress must animate during active execution')
assert(executionChain.includes('aria-current={currentId === id') && executionChain.includes("currentId === id ? 'is-current'"), 'actual current stage must remain highlighted when selection changes')
assert(executionChain.includes('Running now') && executionChain.includes('No active runtime · latest checkpoint') && executionChain.includes('obs-chain__runtime'), 'toolbar must explicitly identify the current runtime or state that none is active')
assert(executionChainCss.includes('@keyframes obs-death-beacon') && executionChainCss.includes('@keyframes obs-death-wave'), 'death point must expose a visible blocked-stage animation')
assert(executionChainCss.includes('@keyframes obs-progress-track-flow'), 'Overall progress track must expose persistent active flow')
assert(executionChain.includes('JobStatusSummary') && executionChainCss.includes('.obs-chain__error-disclosure[open]'), 'long errors must use no-scroll progressive disclosure')
assert(executionChainCss.includes('-webkit-line-clamp: 3') && !executionChainCss.includes('max-height: 96px'), 'collapsed error preview must clamp without an internal scroll box')
assert(executionChainCss.includes('prefers-reduced-motion'), 'OBS animation must respect reduced-motion accessibility')

assert(obs.includes('aria-labelledby="source-gates-title"') && obs.includes('<DataQualityCompactMatrix gates={gates} compact />'), 'full Source Gates must remain beside the readiness summary')
assert(obs.includes('xl:grid-cols-[minmax(0,2fr)_minmax(0,3fr)]') && obs.includes("compact ? 'grid grid-cols-2 gap-2 lg:grid-cols-4'"), 'Readiness control and Source Gates must use a 4:6 desktop ratio with four Source Gate cards per row')
assert(obs.includes('truncate text-sm font-semibold text-[#f2ead8]">Source Gates'), 'Source Gates must remain on the homepage StockIntelli typography baseline')
assert(!obs.includes('SourceGateSummary'), 'OBS must not restore the replacement Source Gates summary card')
assert(obs.includes('Data Quality'), 'OBS must keep compact Data Quality evidence')
assert(!obs.includes('Model Health Snapshot'), 'OBS must not duplicate Model Pool health')
assert(!obs.includes('Cost / Resource'), 'OBS must not render low-signal resource blocks')
assert(obs.includes('/scheduler') && obs.includes('/data-quality'), 'OBS must keep specialist route deep links')

assert(scheduler.includes('Scheduler Drilldown'), 'Scheduler deep link should remain a drilldown')
assert(!scheduler.includes('dataQualityApi') && !scheduler.includes('deployGateApi') && !scheduler.includes('costsApi'), 'Scheduler drilldown must not duplicate other ownership')
assert(dataQuality.includes('Data Quality Drilldown'), 'Data Quality deep link should remain a drilldown')
assert(dataQuality.includes('freshness') && dataQuality.includes('schema') && dataQuality.includes('parity'), 'Data Quality drilldown must stay focused on freshness/schema/parity')
assert(!dataQuality.includes('deployGateApi') && !dataQuality.includes('Deploy Gate'), 'Data Quality drilldown must not duplicate Deploy Gate')

console.log('obsInformationArchitectureContract: execution chain + standalone registry passed')
