import assert from 'node:assert/strict'
import fs from 'node:fs'

const migration = fs.readFileSync('migrations/0119_pit_factor_shadow_daily_v1.sql', 'utf8')
const learningMigration = fs.readFileSync('domain-migrations/learning/0033_pit_factor_shadow_daily_v1.sql', 'utf8')
const screener = fs.readFileSync('src/lib/marketScreener.ts', 'utf8')
const pending = fs.readFileSync('src/lib/pendingBuyOrchestrator.ts', 'utf8')
const breeze2 = fs.readFileSync('src/lib/breeze2Runtime.ts', 'utf8')
const funnel = fs.readFileSync('src/lib/screenerFunnelEvidence.ts', 'utf8')
const route = fs.readFileSync('src/routes/other.ts', 'utf8')

assert(migration.includes('pit_factor_shadow_daily_v1'))
assert(learningMigration.includes('pit_factor_shadow_daily_v1'))
assert(learningMigration.includes("decision_effect = 'none'"))
assert(migration.includes("decision_effect = 'none'"))
assert(migration.includes('CHECK(residual_weight = 0.10)'))
assert(screener.includes("stage: 'pit_residual_momentum_shadow'"))
assert(screener.includes('scoreAfter: candidate.score'))
assert(screener.includes('candidateSetMutationAllowed: PIT_RESIDUAL_CANDIDATE_SET_MUTATION_ALLOWED'))
assert(screener.includes("auxiliaryAuthority: 'diagnostic_only'"))
assert(funnel.includes('pit_residual_momentum_shadow'))
assert(!pending.includes('rrg_soft_overlay'))
assert(!pending.includes('rrg_rotation_model'))
assert(!pending.includes('RRG_LAGGING_SOFT_RISK'))
assert(!pending.includes('RRG_WEAKENING_DOWNGRADE'))
assert(!breeze2.includes('hasRrg'))
assert(route.includes("recommendations.get('/factor-flow-map'"))
assert(route.includes("auxiliary_authority: 'diagnostic_only'"))
assert(route.includes("decision_effect: 'none'"))
