export type SchedulerConsolidationClass =
  | 'keep_scheduler'
  | 'merge_into_chain'
  | 'downstream_evidence'
  | 'manual_maintenance_candidate'
  | 'disable_candidate'

export interface SchedulerDependencySpec {
  task: string
  owner: 'gcp_scheduler' | 'worker_chain' | 'controller_chain' | 'manual_only'
  consolidationClass: SchedulerConsolidationClass
  currentFunction: string
  replacementOwner?: string
  upstream: string[]
  downstream: string[]
  requiredBeforeDisable: string[]
  operatorRisk: 'low' | 'medium' | 'high'
  recommendation: string
}

export const SCHEDULER_DEPENDENCY_MAP: Record<string, SchedulerDependencySpec> = {
  'daily-execution-paper-lineage': {
    task: 'daily-execution-paper-lineage', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Calls ensureDailyExecutionPaperClosureArtifacts after the paper account snapshot.',
    upstream: ['daily-snapshot'], downstream: ['storage-health-check', 'weekly-audit'], requiredBeforeDisable: [], operatorRisk: 'high',
    recommendation: 'Keep as the idempotent post-snapshot execution/paper lineage closure watchdog.',
  },
  'external-evidence': {
    task: 'external-evidence', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Durably materializes formal-shadow GDELT and official evidence for the latest recommendation date.',
    upstream: ['daily-recommendations'], downstream: ['strategy-learning', 'weekly-audit'], requiredBeforeDisable: [], operatorRisk: 'medium',
    recommendation: 'Keep as evidence-only input; never make external evidence a direct trading gate.',
  },
  'debate-memory-retention': {
    task: 'debate-memory-retention', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Deletes debate_memory rows older than the explicit 180-day retention window.',
    upstream: ['debate-memory'], downstream: ['storage-health-check'], requiredBeforeDisable: [], operatorRisk: 'medium',
    recommendation: 'Keep while debate memory remains a live producer; retention mutation must stay bounded by date.',
  },
  'artifact-reconcile': {
    task: 'artifact-reconcile', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Runs bounded R2 object, manifest and checksum reconciliation and fails on missing/mismatched artifacts.',
    upstream: ['run-artifacts', 'r2-artifacts'], downstream: ['storage-health-check'], requiredBeforeDisable: [], operatorRisk: 'medium',
    recommendation: 'Keep before storage health so integrity failures remain fail-visible.',
  },
  'retention-archive-only': {
    task: 'retention-archive-only', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Runs checksum-verified archive-only retention; the handler never deletes source rows.',
    upstream: ['learning-retention-readiness'], downstream: ['retention-hot-window-drain', 'r2-retention-sweep'], requiredBeforeDisable: [], operatorRisk: 'high',
    recommendation: 'Keep archive-only as the prerequisite to any separately approved drain action.',
  },
  'retention-hot-window-drain': {
    task: 'retention-hot-window-drain', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Runs the read-only hot-window drain preflight and reports eligible rows.',
    upstream: ['retention-archive-only'], downstream: ['storage-capacity-report'], requiredBeforeDisable: [], operatorRisk: 'medium',
    recommendation: 'Keep read-only until a separately approved archive-before-delete contract exists.',
  },
  'data-domain-shadow-backfill-next': {
    task: 'data-domain-shadow-backfill-next', owner: 'gcp_scheduler', consolidationClass: 'disable_candidate',
    replacementOwner: 'Codex daily backfill retirement qualification monitor',
    currentFunction: 'Requires the latest evening-chain closure, then queues the next incomplete domain or returns all_domains_caught_up.',
    upstream: ['evening-chain', 'data-domain-shadow-backfill'], downstream: ['storage-health-check', 'storage-capacity-report'], requiredBeforeDisable: ['all domain cursors and parity receipts must remain caught up'], operatorRisk: 'medium',
    recommendation: 'Pause after caught-up readback; retire only after an observation window and explicit approval.',
  },
  'legacy-strategy-evidence-migration': {
    task: 'legacy-strategy-evidence-migration', owner: 'gcp_scheduler', consolidationClass: 'manual_maintenance_candidate',
    currentFunction: 'Drains durable legacy strategy evidence into exact R2 artifacts and compact learning rows.',
    replacementOwner: 'manual legacy strategy evidence migration closure runbook',
    upstream: ['strategy-decision-log'], downstream: ['learning-retention-readiness', 'storage-health-check'], requiredBeforeDisable: ['migration backlog must be zero and artifact readback must remain complete'], operatorRisk: 'high',
    recommendation: 'Disable only after backlog and artifact readback both remain complete.',
  },
  'legacy-hot-data-retirement': {
    task: 'legacy-hot-data-retirement', owner: 'gcp_scheduler', consolidationClass: 'manual_maintenance_candidate',
    currentFunction: 'Runs the legacy hot-data retirement audit in dry-run mode unless an explicit confirmation phrase is supplied.',
    replacementOwner: 'manual archive-before-delete retirement runbook',
    upstream: ['legacy-db', 'data-domain-shadow-backfill-next'], downstream: ['storage-capacity-report'], requiredBeforeDisable: ['archive, rollback, and dry-run eligibility receipts must all pass'], operatorRisk: 'high',
    recommendation: 'Keep scheduled execution read-only; any mutation remains explicit manual maintenance.',
  },
  'r2-retention-sweep': {
    task: 'r2-retention-sweep', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Runs bounded lineage-aware R2 retention and reports failed deletions.',
    upstream: ['retention-archive-only', 'artifact-reconcile'], downstream: ['orphan-reachability-gc', 'storage-health-check'], requiredBeforeDisable: [], operatorRisk: 'high',
    recommendation: 'Keep behind verified archive and hard-reference reachability checks.',
  },
  'orphan-reachability-gc': {
    task: 'orphan-reachability-gc', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Runs bounded GC only for staging objects that are unreachable by hard references.',
    upstream: ['artifact-reconcile', 'artifact-hard-references'], downstream: ['storage-health-check'], requiredBeforeDisable: [], operatorRisk: 'high',
    recommendation: 'Keep after reconcile; reachability must remain the deletion authority.',
  },
  'storage-health-check': {
    task: 'storage-health-check', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Runs storage integrity, split-domain, lineage and producer-admission health and fails closed when unhealthy.',
    upstream: ['artifact-reconcile', 'daily-execution-paper-lineage', 'data-domain-shadow-backfill-next'], downstream: ['storage-capacity-report', 'producer-admission'], requiredBeforeDisable: [], operatorRisk: 'high',
    recommendation: 'Keep as the canonical storage-producer admission gate; trading paths remain exempt.',
  },
  'learning-retention-readiness': {
    task: 'learning-retention-readiness', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Inspects Learning and Ops authorities for hot/cold retention readiness without deletion.',
    upstream: ['learning-db', 'ops-db'], downstream: ['retention-archive-only', 'legacy-learning-deletion-readiness'], requiredBeforeDisable: [], operatorRisk: 'medium',
    recommendation: 'Keep as the read-only authority before retention or rollback decisions.',
  },
  'legacy-learning-deletion-readiness': {
    task: 'legacy-learning-deletion-readiness', owner: 'gcp_scheduler', consolidationClass: 'manual_maintenance_candidate',
    currentFunction: 'Audits legacy DB and Learning DB rollback, parity and Time Travel prerequisites without exposing DELETE.',
    replacementOwner: 'manual legacy Learning deletion readiness runbook',
    upstream: ['learning-retention-readiness', 'data-domain-shadow-backfill-next'], downstream: ['storage-health-check'], requiredBeforeDisable: ['rollback, parity, and Time Travel receipts must remain ready'], operatorRisk: 'high',
    recommendation: 'Keep read-only; any legacy deletion still requires explicit approval.',
  },
  'storage-capacity-report': {
    task: 'storage-capacity-report', owner: 'gcp_scheduler', consolidationClass: 'keep_scheduler',
    currentFunction: 'Runs storage health, reads D1/R2 capacity telemetry and writes the daily growth report.',
    upstream: ['storage-health-check', 'retention-hot-window-drain'], downstream: ['scheduler-dashboard'], requiredBeforeDisable: [], operatorRisk: 'medium',
    recommendation: 'Keep as the daily capacity and forecast reporting owner.',
  },
  'screener-v2-watchdog': {
    task: 'screener-v2-watchdog',
    owner: 'gcp_scheduler',
    consolidationClass: 'downstream_evidence',
    currentFunction: 'Reclaims expired screener leases and resumes only the canonical same-day callback owner.',
    replacementOwner: 'screener callback recovery fence',
    upstream: ['screener'],
    downstream: ['allocator-ev-readiness', 'pipeline'],
    requiredBeforeDisable: ['screener callback lease recovery must remain bounded and lineage-fenced'],
    operatorRisk: 'high',
    recommendation: 'Keep as a recovery watchdog and display it outside the primary DAG lane.',
  },
  'strategy-learning-watchdog': {
    task: 'strategy-learning-watchdog',
    owner: 'worker_chain',
    consolidationClass: 'downstream_evidence',
    currentFunction: 'Reclaims canonical queued or expired-running strategy-learning evidence after post-verify authority is complete.',
    replacementOwner: 'strategy-learning durable queue and finalizer checkpoints',
    upstream: ['post-verify-chain', 'strategy-learning'],
    downstream: ['strategy-learning'],
    requiredBeforeDisable: ['cross-midnight expired-lease recovery must remain canonical-lineage fenced and evidence-only'],
    operatorRisk: 'high',
    recommendation: 'Keep inside the existing post-market watchdog cadence until the durable queue can self-resume after DLQ exhaustion.',
  },
  'audit-json-retention': {
    task: 'audit-json-retention',
    owner: 'gcp_scheduler',
    consolidationClass: 'keep_scheduler',
    currentFunction: 'Archives verified audit JSON to R2 and scrubs only the corresponding D1 payload pointers.',
    upstream: [],
    downstream: [],
    requiredBeforeDisable: [],
    operatorRisk: 'medium',
    recommendation: 'Keep as an independent daily storage lifecycle root.',
  },
  'data-domain-shadow-backfill': {
    task: 'data-domain-shadow-backfill',
    owner: 'gcp_scheduler',
    consolidationClass: 'downstream_evidence',
    currentFunction: 'Runs bounded domain-specific parity workers beneath the sequential Multi-D1 coordinator.',
    replacementOwner: 'data-domain-shadow-backfill-next coordinator',
    upstream: ['data-domain-shadow-backfill-next'],
    downstream: ['data-domain-cutover-readiness'],
    requiredBeforeDisable: ['all domain workers must be retired or absorbed only after parity and writer-state closure'],
    operatorRisk: 'high',
    recommendation: 'Keep grouped under one logical worker owner; do not show each physical retry trigger as a separate DAG stage.',
  },
  'dataset-snapshot-export': {
    task: 'dataset-snapshot-export',
    owner: 'controller_chain',
    consolidationClass: 'downstream_evidence',
    currentFunction: 'Builds the immutable compute-tier research snapshot after the pipeline callback without blocking core evening-chain closure.',
    replacementOwner: 'pipeline deferred snapshot follow-up',
    upstream: ['pipeline', 'post-pipeline-chain'],
    downstream: ['active8-oof-daily'],
    requiredBeforeDisable: [
      'exact backtest_dataset snapshot must be ready in Learning D1',
      'snapshot success callback must durably enqueue the Active-8 daily evidence child ticket',
    ],
    operatorRisk: 'high',
    recommendation: 'Keep as an asynchronous evidence branch and close it with a durable logical ticket.',
  },
  'active8-oof-daily': {
    task: 'active8-oof-daily',
    owner: 'gcp_scheduler',
    consolidationClass: 'downstream_evidence',
    currentFunction: 'Materializes frozen-forward daily evidence from the exact ready immutable snapshot; never retrains.',
    replacementOwner: 'dataset snapshot ready callback with scheduler watchdog as recovery only',
    upstream: ['dataset-snapshot-export'],
    downstream: ['allocator-ev-readiness'],
    requiredBeforeDisable: [
      'snapshot-ready event ticket must reach a terminal callback state',
      'watchdog remains available for bounded recovery',
    ],
    operatorRisk: 'high',
    recommendation: 'Use the snapshot-ready callback as primary owner; keep the fixed scheduler only as an idempotent watchdog.',
  },
  'active8-oof-weekly': {
    task: 'active8-oof-weekly',
    owner: 'gcp_scheduler',
    consolidationClass: 'keep_scheduler',
    currentFunction: 'Creates the deterministic purged-OOF cohort, dispatches weekly full-fit training, validates the ensemble bundle, and attempts atomic promotion.',
    upstream: ['verified-outcomes', 'dataset-snapshot-export'],
    downstream: ['model-registry', 'serving-bundle', 'active8-oof-daily'],
    requiredBeforeDisable: [],
    operatorRisk: 'high',
    recommendation: 'Keep as a weekly release opportunity; promotion occurs only when the integrated ensemble bundle passes.',
  },
  'active8-oof-monthly': {
    task: 'active8-oof-monthly',
    owner: 'gcp_scheduler',
    consolidationClass: 'keep_scheduler',
    currentFunction: 'Repeats the full-fit, bundle validation, and atomic promotion lifecycle on the monthly research cadence.',
    upstream: ['active8-oof-weekly', 'monthly-optuna'],
    downstream: ['model-registry', 'serving-bundle'],
    requiredBeforeDisable: [],
    operatorRisk: 'high',
    recommendation: 'Keep as the monthly release opportunity; it is not the only cadence allowed to promote.',
  },
  'evening-chain': {
    task: 'evening-chain',
    owner: 'gcp_scheduler',
    consolidationClass: 'keep_scheduler',
    currentFunction: 'Post-market root chain: update -> indicators -> same-date regime -> screener -> allocator EV readiness -> pipeline, then callback chains.',
    upstream: [],
    downstream: ['indicator-queue', 'screener', 'regime-compute', 'allocator-ev-readiness', 'pipeline', 'post-pipeline-chain', 'post-verify-chain'],
    requiredBeforeDisable: [],
    operatorRisk: 'high',
    recommendation: 'Keep as the single post-market root scheduler.',
  },
  'allocator-ev-readiness': {
    task: 'allocator-ev-readiness',
    owner: 'worker_chain',
    consolidationClass: 'merge_into_chain',
    currentFunction: 'Refreshes L4 alpha EV and attempts fusion refresh before recommendation allocation.',
    replacementOwner: 'evening-chain/updateOrchestrator pre-pipeline stage',
    upstream: ['screener', 'regime-compute'],
    downstream: ['pipeline'],
    requiredBeforeDisable: [
      'L4 alpha EV refresh must promote or fail closed before recommendation allocation',
      'allocator EV fusion refresh failure must keep BUY/allocation fail closed while evidence collection continues',
    ],
    operatorRisk: 'high',
    recommendation: 'Keep inside evening-chain before pipeline; do not leave as manual-only artifact maintenance.',
  },
  'allocator-ev-feature-snapshot-backfill': {
    task: 'allocator-ev-feature-snapshot-backfill',
    owner: 'worker_chain',
    consolidationClass: 'merge_into_chain',
    currentFunction: 'Materializes same-date point-in-time allocator features after pipeline recommendation output and before verify.',
    replacementOwner: 'post-pipeline-chain callback stage',
    upstream: ['pipeline'],
    downstream: ['verify-v2', 'post-verify-chain'],
    requiredBeforeDisable: [
      'same-date daily_recommendations and ensemble prediction must exist',
      'snapshot build and D1 write counts must both be positive',
    ],
    operatorRisk: 'high',
    recommendation: 'Keep in the pipeline success callback; an empty snapshot must stop callback closure.',
  },
  'morning-setup': {
    task: 'morning-setup',
    owner: 'gcp_scheduler',
    consolidationClass: 'keep_scheduler',
    currentFunction: 'Settles T2 state, warms up control plane, creates debate/pending-buy candidates.',
    upstream: ['recommendation'],
    downstream: ['pre-market-warmup', 'intraday-check'],
    requiredBeforeDisable: [],
    operatorRisk: 'high',
    recommendation: 'Keep; this owns the morning pending-buy creation boundary.',
  },
  'morning-briefing': {
    task: 'morning-briefing',
    owner: 'gcp_scheduler',
    consolidationClass: 'keep_scheduler',
    currentFunction: 'Generates morning briefing/report from recommendation, news, US-leading, and account state.',
    upstream: ['us-leading', 'news-analyst', 'morning-setup'],
    downstream: ['notification-report'],
    requiredBeforeDisable: [],
    operatorRisk: 'medium',
    recommendation: 'Keep user-facing briefing output, but absorb news/us-leading as upstream evidence steps.',
  },
  'pre-market-warmup': {
    task: 'pre-market-warmup',
    owner: 'gcp_scheduler',
    consolidationClass: 'merge_into_chain',
    currentFunction: 'Runs control-plane warmup, reconciles pending-buy debates, and summarizes pre-market state.',
    replacementOwner: 'morning chain / pre-open quote sanity chain',
    upstream: ['morning-setup'],
    downstream: ['intraday-check'],
    requiredBeforeDisable: [
      'morning chain must reconcile pending-buy debates',
      'intraday-check must fail-close when quote sanity/restricted gate is missing',
      'Scheduler UI must show pre-open finalize as a chain step',
    ],
    operatorRisk: 'high',
    recommendation: 'Do not delete first; convert into a pre-open chain step after parity tests pass.',
  },
  'daily-snapshot': {
    task: 'daily-snapshot',
    owner: 'gcp_scheduler',
    consolidationClass: 'merge_into_chain',
    currentFunction: 'Writes paper account, position, PnL, Sharpe/MDD source snapshot.',
    replacementOwner: 'post-market / EOD chain',
    upstream: ['eod-exit'],
    downstream: ['risk-triggers', 'dashboard-performance', 'daily-report'],
    requiredBeforeDisable: [
      'post-market chain must write paper_daily_snapshots',
      'MDD/Sharpe/risk trigger readback must pass after chain run',
      'dashboard performance metrics must read the new chain-owned snapshot',
    ],
    operatorRisk: 'high',
    recommendation: 'Merge into post-market/EOD chain only after account metric parity is verified.',
  },
  'us-leading': {
    task: 'us-leading',
    owner: 'gcp_scheduler',
    consolidationClass: 'downstream_evidence',
    currentFunction: 'Fetches US/SOX/futures leading signal for pre-market context.',
    replacementOwner: 'morning-briefing upstream evidence step',
    upstream: [],
    downstream: ['morning-briefing', 'morning-setup-context'],
    requiredBeforeDisable: [
      'morning briefing must fetch or read latest US-leading signal',
      'stale US-leading signal must be visible in briefing diagnostics',
    ],
    operatorRisk: 'medium',
    recommendation: 'Move under morning briefing context builder; keep manual trigger for debugging.',
  },
  'news-analyst': {
    task: 'news-analyst',
    owner: 'gcp_scheduler',
    consolidationClass: 'downstream_evidence',
    currentFunction: 'Generates daily news bias/confidence/key factors.',
    replacementOwner: 'news queue / morning-briefing upstream evidence step',
    upstream: ['news-ingestion'],
    downstream: ['morning-briefing', 'recommendation-context'],
    requiredBeforeDisable: [
      'news queue or morning briefing must own report generation',
      'recommendation must degrade clearly when news evidence is stale',
    ],
    operatorRisk: 'medium',
    recommendation: 'Move into news queue or briefing chain; avoid separate scheduler if it only produces context.',
  },
  'weekly-audit': {
    task: 'weekly-audit',
    owner: 'gcp_scheduler',
    consolidationClass: 'merge_into_chain',
    currentFunction: 'Calls ml-controller weekly audit and optionally sends Discord report.',
    replacementOwner: 'weekly validation summary',
    upstream: ['verified-outcomes'],
    downstream: ['weekly-report'],
    requiredBeforeDisable: [
      'weekly validation summary must include audit report fields',
      'Discord/LINE delivery must use the new summary owner',
    ],
    operatorRisk: 'medium',
    recommendation: 'Merge into a single weekly validation summary report.',
  },
  'alpha-quality': {
    task: 'alpha-quality',
    owner: 'gcp_scheduler',
    consolidationClass: 'merge_into_chain',
    currentFunction: 'Checks alpha bucket/regime quality from config_pool outcomes.',
    replacementOwner: 'weekly validation summary',
    upstream: ['verified-outcomes', 'trading-config'],
    downstream: ['weekly-report', 'adaptive-meta-review'],
    requiredBeforeDisable: [
      'weekly validation summary must run alpha-quality and persist its evidence',
      'OBS must show alpha-quality stale/missing evidence if the weekly chain fails',
    ],
    operatorRisk: 'medium',
    recommendation: 'Merge with weekly backtest/MC/PBO because all are validation evidence.',
  },
  'sector-leaders': {
    task: 'sector-leaders',
    owner: 'gcp_scheduler',
    consolidationClass: 'downstream_evidence',
    currentFunction: 'Computes sector leaders/correlation rotation evidence from D1.',
    replacementOwner: 'screener/evening-chain evidence builder',
    upstream: ['market-close-refresh', 'update', 'sector-tags'],
    downstream: ['screener', 'dashboard-sector-flow'],
    requiredBeforeDisable: [
      'screener/evening-chain must compute or refresh sector leaders',
      'dashboard sector-flow freshness must point to the new owner',
    ],
    operatorRisk: 'medium',
    recommendation: 'Move to screener/evening-chain evidence path; sector data should refresh with market data.',
  },
  'model-ic-rolling': {
    task: 'model-ic-rolling',
    owner: 'worker_chain',
    consolidationClass: 'merge_into_chain',
    currentFunction: 'Refreshes rolling IC and live-gate evidence after each verify callback.',
    replacementOwner: 'post-verify chain',
    upstream: ['verify-v2'],
    downstream: ['adapt', 'live-gate', 'model-registry'],
    requiredBeforeDisable: [
      'post-verify chain must persist a terminal model-ic-rolling log for every completed verify callback',
    ],
    operatorRisk: 'high',
    recommendation: 'Keep as a post-verify child with no fixed-time scheduler ownership.',
  },
  'model-ic-full-check': {
    task: 'model-ic-full-check',
    owner: 'gcp_scheduler',
    consolidationClass: 'keep_scheduler',
    currentFunction: 'Runs the Friday full IC history append, promotion dry-run, and config-pool evaluation.',
    upstream: ['verified-outcomes', 'model-registry'],
    downstream: ['promotion-review', 'config-pool'],
    requiredBeforeDisable: [],
    operatorRisk: 'high',
    recommendation: 'Keep as the independently scheduled Friday evidence audit; never reuse the rolling status key.',
  },
  'paper-active-postmarket': {
    task: 'paper-active-postmarket',
    owner: 'worker_chain',
    consolidationClass: 'downstream_evidence',
    currentFunction: 'Persists paper-active challenger promotion packets and audit rows after verify/daily report.',
    replacementOwner: 'post-verify chain',
    upstream: ['verify-v2', 'model-ic-rolling', 'daily-report'],
    downstream: ['obsidian-sync', 'scheduler-dashboard', 'promotion-review'],
    requiredBeforeDisable: [
      'post-verify chain must run paper-active-postmarket after daily-report',
      'promotion audit rows and scheduler logs must be visible in OBS/dashboard',
      'paper-active promotion must remain non-critical and must not write orders or real trading state',
    ],
    operatorRisk: 'medium',
    recommendation: 'Keep non-critical in post-verify chain; it must never write orders or real trading state.',
  },
  'weekly-cleanup': {
    task: 'weekly-cleanup',
    owner: 'gcp_scheduler',
    consolidationClass: 'manual_maintenance_candidate',
    currentFunction: 'Runs local cleanup, lifecycle dry-run/audit, and weekly local maintenance.',
    replacementOwner: 'manual maintenance + model registry/promotion controller',
    upstream: [],
    downstream: ['model-registry-maintenance'],
    requiredBeforeDisable: [
      'production lifecycle mutation must be owned by model registry/promotion controller',
      'cleanup must be idempotent and available as an admin/manual maintenance action',
      'no production metric may depend on weekly-cleanup as the only writer',
    ],
    operatorRisk: 'medium',
    recommendation: 'Keep weekly cleanup audit-only; production lifecycle side effects require explicit promotion-controller action.',
  },
  'optuna-queue': {
    task: 'optuna-queue',
    owner: 'gcp_scheduler',
    consolidationClass: 'disable_candidate',
    currentFunction: 'Polls KV every 6h, pops one pending Optuna item, and calls a controller endpoint.',
    replacementOwner: 'weekly/monthly optuna research_sweep or explicit manual queue drain',
    upstream: ['optuna-kv-queue'],
    downstream: ['optimizer-kv-candidate'],
    requiredBeforeDisable: [
      'weekly/monthly research_sweep must own normal Optuna/GA parameter search',
      'manual drain endpoint must remain available for exceptional queued items',
      'KV pending queue must be empty or intentionally archived',
    ],
    operatorRisk: 'low',
    recommendation: 'Disable scheduled polling after queue readback proves empty; keep manual drain only.',
  },
  'monthly-strategy-mining': {
    task: 'monthly-strategy-mining',
    owner: 'gcp_scheduler',
    consolidationClass: 'keep_scheduler',
    currentFunction: 'Monthly pymoo NSGA-III + novelty strategy mining preflight and research ledger trigger.',
    upstream: ['feature-registry-materialization', 'formal137-similarity-contract'],
    downstream: ['strategy_mining_runs', 'strategy_backtest_results', 'strategy_promotion_ledger', 'monthly-optuna', 'active8-oof-monthly'],
    requiredBeforeDisable: [],
    operatorRisk: 'medium',
    recommendation: 'Keep as the monthly strategy discovery owner; endpoint is research-only until promotion gates and Wei approval pass.',
  },
}

export function getSchedulerDependencySpec(task: string): SchedulerDependencySpec | undefined {
  return SCHEDULER_DEPENDENCY_MAP[task]
}

export function schedulerConsolidationCandidates(kind?: SchedulerConsolidationClass): SchedulerDependencySpec[] {
  const specs = Object.values(SCHEDULER_DEPENDENCY_MAP)
  return kind ? specs.filter((spec) => spec.consolidationClass === kind) : specs
}
