const fs = require('fs')

export {}

function assert(condition: unknown, message: string): void {
  if (!condition) throw new Error(message)
}

const marketScreener = fs.readFileSync('src/lib/marketScreener.ts', 'utf8')
const pendingBuyOrchestrator = fs.readFileSync('src/lib/pendingBuyOrchestrator.ts', 'utf8')
const paperEntryTasks = fs.readFileSync('src/lib/paperEntryTasks.ts', 'utf8')
const updateOrchestrator = fs.readFileSync('src/lib/updateOrchestrator.ts', 'utf8')
const screenerMarketData = fs.readFileSync('src/lib/screenerMarketData.ts', 'utf8')
const screenerSeedQuality = fs.readFileSync('src/lib/screenerSeedQuality.ts', 'utf8')
const screenerPolicy = fs.readFileSync('src/lib/screenerPolicy.ts', 'utf8')
const tradingRestrictions = fs.readFileSync('src/lib/tradingRestrictions.ts', 'utf8')
const schema = fs.readFileSync('schema.sql', 'utf8')
const screenerFunnelMigration = fs.readFileSync('migration_screener_funnel.sql', 'utf8')
const sectorFlowTurnoverMigration = fs.readFileSync('migration_sector_flow_turnover_share_2026_05_26.sql', 'utf8')
const screenerStrategyConsumer = fs.readFileSync('src/lib/screenerStrategyConsumer.ts', 'utf8')
const strategyCandidatePool = fs.readFileSync('src/lib/strategyCandidatePool.ts', 'utf8')
const strategySpec = fs.readFileSync('src/lib/strategySpec.ts', 'utf8')
const strategyOwnerFreeze = fs.readFileSync('src/lib/strategyOwnerFreeze.ts', 'utf8')
const strategyLab = fs.readFileSync('src/lib/strategyLab.ts', 'utf8')
const researchExperimentRegistry = fs.readFileSync('src/lib/researchExperimentRegistry.ts', 'utf8')
const researchInternGate = fs.readFileSync('src/lib/researchInternGate.ts', 'utf8')
const researchEvaluationPlan = fs.readFileSync('src/lib/researchEvaluationPlan.ts', 'utf8')
const stocksRoute = fs.readFileSync('src/routes/stocks.ts', 'utf8')
const otherRoute = fs.readFileSync('src/routes/other.ts', 'utf8')
const screenerFunnelEvidence = fs.readFileSync('src/lib/screenerFunnelEvidence.ts', 'utf8')
const dailyPipeline = fs.readFileSync('../ml-controller/graphs/daily_pipeline_v2.py', 'utf8')

{
  assert(!fs.existsSync('src/lib/screenerPercentile.ts'), 'legacy 40/30/30 percentile screener owner should be removed')
  for (const source of [marketScreener, pendingBuyOrchestrator, paperEntryTasks, screenerMarketData, screenerPolicy]) {
    assert(!source.includes('screenerPercentile'), 'runtime screener paths must not import legacy percentile scorer')
  }
  assert(fs.existsSync('src/lib/screenerMarketData.ts'), 'screener market data loader should live in its own domain module')
  assert(marketScreener.includes("from './screenerMarketData'"), 'marketScreener should import the market data loader module')
  assert(!marketScreener.includes('async function loadMarketDataFromD1'), 'marketScreener should not own D1 market data loading')
  assert(marketScreener.includes('resolveScreenerRunDate'), 'screener must resolve an explicit rerun date instead of always using today')
  assert(marketScreener.includes('runBottomUpScreener(env: Bindings, runDate?: string | null)'), 'screener public contract must accept a backfill date')
  assert(screenerMarketData.includes('asOfDate?: string'), 'screener D1 loader must support as-of-date backfills')
  assert(screenerMarketData.includes('WHERE date <= ?'), 'screener D1 loader must cap price/chip data by requested date')
}

{
  assert(!marketScreener.includes("../routes/stocks"), 'screener lib must not import route modules')
  assert(!marketScreener.includes("from './stocks'"), 'screener lib must not import stocks route')
  assert(marketScreener.includes("from './technicalIndicators'"), 'screener should use technical indicator domain service')
  assert(screenerMarketData.includes('isAutoTradablePriceRow'), 'screener market data must own auto-tradable universe filtering')
  assert(screenerMarketData.includes("from './boardTradability'"), 'screener market data must consume the board/tradability contract')
  assert(screenerMarketData.includes('splitPriceRowsByBoard'), 'screener market data must expose board-lane splitting')
  assert(marketScreener.includes('emergingResearchPrices'), 'marketScreener must keep an explicit emerging research lane')
  assert(marketScreener.includes('emergingResearchCandidates'), 'marketScreener must produce emerging research candidates separately from tradable candidates')
  assert(marketScreener.includes("from './screenerPolicy'"), 'marketScreener must consume adaptive screener policy')
  assert(marketScreener.includes('resolveScreenerPolicy'), 'marketScreener must resolve top-pool/shortlist/emerging sizes from policy')
  assert(!marketScreener.includes('slice(0, 100)'), 'screener top pool must not use hardcoded 100')
  assert(!marketScreener.includes('slice(0, 80)'), 'screener shortlist probes must not use hardcoded 80')
  assert(marketScreener.includes('loadRestrictedScreenerSymbols'), 'screener must use a unified restricted-symbol gate')
  assert(tradingRestrictions.includes('market:attention_stocks'), 'screener restricted gate must include attention-list KV fallback')
  assert(tradingRestrictions.includes('market:tpex_attention_stocks'), 'screener restricted gate must reserve TPEX attention-list source')
  assert(tradingRestrictions.includes('canonical_trading_restrictions'), 'screener restricted gate must include canonical D1 restriction governance')
  assert(updateOrchestrator.includes('fetchPunishedStocks'), 'market data update must refresh punished-stock cache, not leave screener as the only owner')
  assert(updateOrchestrator.includes('market:punished_stocks'), 'market data update must write punished-stock KV for downstream gates')
  assert(pendingBuyOrchestrator.includes('market:attention_stocks'), 'morning setup restricted gate must include attention-list KV fallback')
  assert(pendingBuyOrchestrator.includes('market:tpex_attention_stocks'), 'morning setup restricted gate must reserve TPEX attention-list source')
  assert(pendingBuyOrchestrator.includes('market:delisting_risk'), 'morning setup restricted gate must include delisting-risk KV')
  assert(paperEntryTasks.includes('loadExecutionBlockedSymbols'), 'intraday execution must use the unified execution restricted-symbol gate')
  assert(paperEntryTasks.includes('market:restricted_execution_checked_at'), 'intraday execution restricted gate must have a freshness marker')
  assert(paperEntryTasks.includes('restricted_execution_gate'), 'intraday execution must record restricted-list skips with a dedicated reason')
  assert(marketScreener.includes('loadSelectionHistoryFlags'), 'screener repeat/new-money history must be a reusable domain helper')
  assert(marketScreener.includes('dedupeScreenerCandidatesBySymbol'), 'screener must dedupe symbols before writing funnel counts and daily seeds')
  assert(marketScreener.includes('finalCandidates = dedupeScreenerCandidatesBySymbol'), 'tradable funnel count must use the deduped ML shortlist')
  assert(marketScreener.includes('buildLayer1StrategyBreadthPlan'), 'L1 breadth pool must be strategy-quota driven from the full feature-enriched universe')
  assert(!marketScreener.includes('preRankPool = scoredSorted.slice(0, screenerPolicy.sizing.candidatePoolSize)'), 'L1 breadth pool must not be pre-ranked by score top 200')
  assert(marketScreener.includes('layer1BreadthPool'), 'marketScreener should name the Layer1 breadth pool explicitly')
  assert(marketScreener.includes('passesLayer1TopUpQualityGuard'), 'post-overlay L1 top-up must not bypass raw strategy quality guards')
  assert(marketScreener.includes('research_strategy_ids'), 'production funnel evidence must keep research strategy attribution separate from active strategy ids')
  assert(!marketScreener.includes("['layer1_breadth']"), 'Layer1 top-up must not masquerade as a registered strategy id')
  assert(marketScreener.includes('emergingResearchCandidates.push(...dedupeScreenerCandidatesBySymbol'), 'emerging funnel count must use the deduped research shortlist')
  assert(marketScreener.includes('highFreqPenalty'), 'screener high-frequency candidates must affect ranking, not only labels')
  assert(screenerMarketData.includes('dealer_buy'), 'screener chip data must include dealer flows for three-institution scoring')
  assert(schema.includes('screener_funnel_runs'), 'schema must include screener funnel run table')
  assert(schema.includes('screener_funnel_items'), 'schema must include screener funnel item table')
  assert(screenerFunnelMigration.includes('screener_funnel_items'), 'funnel migration must create item audit table')
  assert(marketScreener.includes('writeScreenerFunnel'), 'screener must persist per-run funnel evidence')
  assert(marketScreener.includes("stage: 'l1_candidate_seed_after_overlay'"), 'screener must persist semantic L1 candidate seed stage before legacy final_selection alias')
  assert(marketScreener.includes("legacy_alias_stage: 'final_selection'"), 'screener must mark final_selection as a legacy alias, not the semantic post-ML final')
  assert(marketScreener.includes('SCREENER_FUNNEL_MAX_ITEMS = 5000'), 'screener funnel audit cap must keep strategy/final stages, not truncate at universe+scoring')
  assert(marketScreener.includes('rrg_overlay'), 'RRG must be recorded as overlay evidence, not opaque bonus text')
  assert(marketScreener.includes('latestThemeUniverse'), 'RRG overlay must align FinLab taxonomy tags to the latest sector_flow taxonomy universe')
  assert(marketScreener.includes("SELECT sector, classification, quadrant"), 'screener RRG overlay must keep sector_flow classification with the sector')
  assert(marketScreener.includes('turnover_share_delta'), 'screener RRG overlay must consume sector turnover share delta as flow confirmation')
  assert(marketScreener.includes('rrg_overlay_turnover_share_tailwind'), 'positive sector turnover share delta must be a distinct RRG evidence reason')
  assert(schema.includes('turnover_share_delta'), 'sector_flow schema must persist turnover share delta')
  assert(sectorFlowTurnoverMigration.includes('ALTER TABLE sector_flow ADD COLUMN turnover_share_delta REAL'), 'sector_flow turnover-share migration must add turnover_share_delta')
  assert(marketScreener.includes("latestThemeUniverse.has(`${candidateTag.classification}:${candidateTag.tag}`)"), 'screener RRG overlay must match taxonomy by classification+tag')
  assert(marketScreener.includes('taxonomyKey'), 'screener RRG overlay evidence must expose classification-tag taxonomy key')
  assert(marketScreener.includes('rrg_overlay_unmapped_neutral'), 'RRG overlay must record unmapped taxonomy as neutral evidence')
  assert(pendingBuyOrchestrator.includes('loadRrgTaxonomyTags'), 'pending-buy RRG gate must share the FinLab taxonomy tag contract')
  assert(pendingBuyOrchestrator.includes('FROM finlab_taxonomy_tags'), 'pending-buy RRG gate must read FinLab taxonomy before concept fallback')
  assert(pendingBuyOrchestrator.includes("tag_type IN ('industry_theme', 'subindustry', 'industry')"), 'pending-buy RRG gate must include industry/subindustry taxonomy')
  assert(pendingBuyOrchestrator.includes("classification IN ('industry', 'industry_theme', 'subindustry', 'theme')"), 'pending-buy RRG gate must align to four-layer sector_flow')
  assert(dailyPipeline.includes("WHERE tag_type = 'concept' AND symbol IN"), 'pipeline persona concept sentiment must never mix industry/subindustry tags')
  assert(marketScreener.includes('buzz_evidence'), 'buzz concepts must be recorded as weighted evidence')
  assert(marketScreener.includes('materializeScreenerThemeRuntime'), 'screener seed write must materialize theme_signals/stock_theme_features for the same run date')
  assert(marketScreener.includes('refreshStockThemeFeaturesFromSignals'), 'theme runtime features must refresh from persisted same-date theme signals')
  assert(screenerPolicy.includes('candidate_pool_delta'), 'screener policy must support adaptive top-pool sizing')
  assert(screenerPolicy.includes('ml_shortlist_delta'), 'screener policy must support adaptive ML shortlist sizing')
  assert(screenerPolicy.includes('emerging_research_delta'), 'screener policy must support adaptive emerging research sizing')
  assert(screenerPolicy.includes('percentile_zscore'), 'screener scoring must support percentile/z-score calibration')
  assert(marketScreener.includes('research_only:emerging_not_for_auto_trade'), 'emerging screener rows must be tagged as research-only')
  assert(screenerSeedQuality.includes('market_segment'), 'screener seed SQL must persist market segment governance')
  assert(screenerSeedQuality.includes('recommendation_lane'), 'screener seed SQL must persist recommendation lane governance')
  assert(screenerSeedQuality.includes('eligible_for_pending_buy'), 'screener seed SQL must persist pending-buy eligibility')
  assert(pendingBuyOrchestrator.includes("from './boardTradability'"), 'pending-buy setup must consume the board/tradability contract')
  assert(pendingBuyOrchestrator.includes("NOT IN ('EMERGING', 'ESB')"), 'pending-buy setup must exclude explicit emerging-board stocks')
  assert(pendingBuyOrchestrator.includes('sp_exec.open'), 'pending-buy setup must reject emerging-style rows without an executable open price')
  assert(pendingBuyOrchestrator.includes('latest_avg_price'), 'pending-buy setup must inspect avg-price-only emerging-style rows')
  assert(pendingBuyOrchestrator.includes('candidateLimit'), 'pending-buy setup must fetch enough candidates before board/restriction filtering')
  assert(pendingBuyOrchestrator.includes('themeUniverse'), 'pending-buy RRG gate must align taxonomy tags to the latest sector_flow universe')
  assert(pendingBuyOrchestrator.includes('classification: quadrant.classification'), 'pending-buy RRG logs must expose which taxonomy layer gated the stock')
  assert(pendingBuyOrchestrator.includes('RRG_UNMAPPED_NEUTRAL'), 'pending-buy RRG gate must log unmapped taxonomy as neutral, not block')
  assert(otherRoute.includes("from '../lib/boardTradability'"), 'recommendation API must expose board/tradability contract fields')
  assert(otherRoute.includes('persistedLane'), 'recommendation API must prefer persisted governance lane before board fallback')
  assert(otherRoute.includes('emerging_recommendations'), 'recommendation API must split emerging watchlist from tradable recommendations')
  assert(otherRoute.includes('summarizeScreenerFunnelRows'), 'recommendation API must expose full screener funnel evidence, not only final rank')
  assert(otherRoute.includes('screener_funnel_timeline'), 'recommendation API must return UI-readable screener funnel timeline')
  assert(otherRoute.includes("'layer1_strategy_breadth_gate'"), 'recommendation API must read Layer 1 funnel evidence')
  assert(otherRoute.includes("'layer2_coarse_ml_gate'"), 'recommendation API must read Layer 2 funnel evidence')
  assert(otherRoute.includes("'l1_candidate_seed_after_overlay'"), 'recommendation API must read semantic L1 candidate seed evidence')
  assert(otherRoute.includes('resolveRecommendationGovernance'), 'recommendation API must apply board hard gates after persisted recommendation fields')
  assert(otherRoute.includes('turnover_share_delta'), 'sector-flow API trend payload must expose turnover share delta')
  assert(otherRoute.includes('latest_screener_run'), 'recommendation API must read funnel evidence from the latest screener run only')
  assert(screenerFunnelEvidence.includes('rrg_overlay'), 'funnel evidence summary must include RRG overlay')
  assert(screenerFunnelEvidence.includes('buzz_evidence'), 'funnel evidence summary must include buzz evidence')
  assert(screenerFunnelEvidence.includes('diversity_cooldown'), 'funnel evidence summary must include diversity/cooldown evidence')
  assert(screenerFunnelEvidence.includes('pickCandidateSeedStep'), 'funnel evidence must prefer semantic L1 candidate seed over legacy final_selection')
  assert(screenerFunnelEvidence.includes('finalSelection?.evidence?.strategy_pool_ids'), 'funnel evidence summary must expose final selection strategy ids when explicit strategy_pool rows are absent')
}

{
  assert(marketScreener.includes("from './screenerStrategyConsumer'"), 'marketScreener should consume strategy specs through the screener strategy consumer')
  assert(marketScreener.includes("import('./strategyCandidatePool')"), 'marketScreener should use strategy-first candidate pools before ML shortlist selection')
  assert(marketScreener.includes('strategyCandidatePool'), 'screener funnel metadata should include strategy candidate pool telemetry')
  assert(marketScreener.includes('layer1_strategy_breadth_gate'), 'screener must persist Layer 1 strategy breadth gate evidence')
  assert(marketScreener.includes('layer2_coarse_ml_gate'), 'screener must persist Layer 2 coarse queue evidence')
  assert(marketScreener.includes('core_ml_shortlist_size'), 'screener metadata must expose Layer 3 core ML target size')
  assert(strategyCandidatePool.includes('baseTotalBudget: 64'), 'strategy candidate pool should keep 64 as the base ML allocation budget')
  assert(strategyCandidatePool.includes('normalTotalCap: 96'), 'strategy candidate pool should expose adaptive 96 normal cap')
  assert(strategyCandidatePool.includes('lowLoadTotalCap: 128'), 'strategy candidate pool should expose adaptive 128 low-load cap')
  assert(strategyCandidatePool.includes('hardTotalCap: 160'), 'strategy candidate pool should expose hard 160 cap')
  assert(strategyCandidatePool.includes('researchOnlyQueue'), 'strategy candidate pool should route overflow into research-only queue instead of silently dropping')
  assert(strategyCandidatePool.includes('adaptive_empty_pool_ranked_near_match'), 'empty strict strategy pools must still emit explicit shadow near-match candidates instead of leaving UI untagged')
  assert(strategySpec.includes('canonicalFinal ?? snapshot.finalScore'), 'strategy pools must use canonical Score V2 finalScore or total, not scalar storage fallback')
  assert(strategySpec.includes("'bull', 'sideways', 'volatile'"), 'trend strategy must remain available in volatile regime for shadow candidate discovery')
  assert(strategySpec.includes("'bull', 'sideways', 'bear', 'volatile'"), 'defensive strategy must remain available in volatile regime for shadow candidate discovery')
  assert(screenerStrategyConsumer.includes("from './strategySpec'"), 'screener strategy consumer should read the strategy spec contract')
  assert(screenerStrategyConsumer.includes("from './strategyOwnerFreeze'"), 'screener strategy consumer should enforce owner freeze')
  assert(strategyOwnerFreeze.includes('STRATEGY_OWNER_BOUNDARIES'), 'owner freeze must be explicit and testable')
  assert(!strategySpec.includes('../routes/'), 'strategy spec must not import route modules')
  assert(!/from ['"].*pendingBuy/i.test(strategySpec), 'strategy spec must not import pending-buy orchestration')
  assert(!/from ['"].*paper|from ['"].*execution/i.test(strategySpec), 'strategy spec must not import execution modules')
  assert(!strategyLab.includes('../routes/'), 'strategy lab MVP must not import routes')
  assert(!strategyLab.includes('env.DB'), 'strategy lab MVP should stay pure until a route/controller is intentionally added')
  assert(researchExperimentRegistry.includes('can_retrain_prod: false'), 'research registry must explicitly block prod retrain')
  assert(researchExperimentRegistry.includes('can_promote: false'), 'research registry must explicitly block promote')
  assert(researchExperimentRegistry.includes('can_deploy: false'), 'research registry must explicitly block deploy')
  assert(researchExperimentRegistry.includes('can_trade: false'), 'research registry must explicitly block trading')
  assert(!/controllerFetch|runWeeklyRetrain|promoteSandbox|setTradingConfig/.test(researchExperimentRegistry), 'research registry must not call production mutation workflows')
  assert(researchInternGate.includes("'deploy_prod'"), 'research gate must explicitly model deploy attempts')
  assert(researchInternGate.includes('FORBIDDEN_ACTIONS'), 'research gate must keep forbidden action list explicit')
  assert(!/controllerFetch|runWeeklyRetrain|promoteSandbox|setTradingConfig|env\.DB|KV\.put/.test(researchInternGate), 'research gate must stay pure and not call mutation workflows')
  assert(researchEvaluationPlan.includes("mode: 'dry_run_only'"), 'research evaluation plan must stay dry-run only')
  assert(researchEvaluationPlan.includes('mutation_allowed: false'), 'research evaluation plan must mark every step non-mutating')
  assert(!/controllerFetch|runWeeklyRetrain|promoteSandbox|setTradingConfig|env\.DB|KV\.put/.test(researchEvaluationPlan), 'research evaluation plan must not execute workflows directly')
}

{
  assert(!stocksRoute.includes('function computeTechnicalIndicators'), 'stocks route must not own indicator formula implementation')
  assert(stocksRoute.includes("../lib/technicalIndicators"), 'stocks route should call technical indicator domain service')
}
