const fs = require('fs')

export {}

function assert(condition: unknown, message: string): void {
  if (!condition) throw new Error(message)
}

const marketScreener = fs.readFileSync('src/lib/marketScreener.ts', 'utf8')
const pendingBuyOrchestrator = fs.readFileSync('src/lib/pendingBuyOrchestrator.ts', 'utf8')
const screenerMarketData = fs.readFileSync('src/lib/screenerMarketData.ts', 'utf8')
const screenerSeedQuality = fs.readFileSync('src/lib/screenerSeedQuality.ts', 'utf8')
const screenerPolicy = fs.readFileSync('src/lib/screenerPolicy.ts', 'utf8')
const schema = fs.readFileSync('schema.sql', 'utf8')
const screenerFunnelMigration = fs.readFileSync('migration_screener_funnel.sql', 'utf8')
const screenerStrategyConsumer = fs.readFileSync('src/lib/screenerStrategyConsumer.ts', 'utf8')
const strategySpec = fs.readFileSync('src/lib/strategySpec.ts', 'utf8')
const strategyOwnerFreeze = fs.readFileSync('src/lib/strategyOwnerFreeze.ts', 'utf8')
const strategyLab = fs.readFileSync('src/lib/strategyLab.ts', 'utf8')
const researchExperimentRegistry = fs.readFileSync('src/lib/researchExperimentRegistry.ts', 'utf8')
const researchInternGate = fs.readFileSync('src/lib/researchInternGate.ts', 'utf8')
const researchEvaluationPlan = fs.readFileSync('src/lib/researchEvaluationPlan.ts', 'utf8')
const stocksRoute = fs.readFileSync('src/routes/stocks.ts', 'utf8')
const otherRoute = fs.readFileSync('src/routes/other.ts', 'utf8')

{
  assert(fs.existsSync('src/lib/screenerMarketData.ts'), 'screener market data loader should live in its own domain module')
  assert(marketScreener.includes("from './screenerMarketData'"), 'marketScreener should import the market data loader module')
  assert(!marketScreener.includes('async function loadMarketDataFromD1'), 'marketScreener should not own D1 market data loading')
  assert(marketScreener.includes('resolveScreenerRunDate'), 'screener must resolve an explicit rerun date instead of always using today')
  assert(marketScreener.includes('runBottomUpScreener(env: Bindings, runDate?: string | null)'), 'screener public contract must accept a backfill date')
  assert(screenerMarketData.includes('asOfDate?: string'), 'screener D1 loader must support as-of-date backfills')
  assert(screenerMarketData.includes('WHERE date <= ?'), 'screener D1 loader must cap price/chip data by requested date')
}

{
  assert(!marketScreener.includes("../routes/stocks"), 'screener lib must not import route modules')
  assert(!marketScreener.includes("from './stocks'"), 'screener lib must not import stocks route')
  assert(marketScreener.includes("from './technicalIndicators'"), 'screener should use technical indicator domain service')
  assert(screenerMarketData.includes('isAutoTradablePriceRow'), 'screener market data must own auto-tradable universe filtering')
  assert(screenerMarketData.includes("from './boardTradability'"), 'screener market data must consume the board/tradability contract')
  assert(screenerMarketData.includes('splitPriceRowsByBoard'), 'screener market data must expose board-lane splitting')
  assert(marketScreener.includes('emergingResearchPrices'), 'marketScreener must keep an explicit emerging research lane')
  assert(marketScreener.includes('emergingResearchCandidates'), 'marketScreener must produce emerging research candidates separately from tradable candidates')
  assert(marketScreener.includes("from './screenerPolicy'"), 'marketScreener must consume adaptive screener policy')
  assert(marketScreener.includes('resolveScreenerPolicy'), 'marketScreener must resolve top-pool/shortlist/emerging sizes from policy')
  assert(!marketScreener.includes('slice(0, 100)'), 'screener top pool must not use hardcoded 100')
  assert(!marketScreener.includes('slice(0, 80)'), 'screener shortlist probes must not use hardcoded 80')
  assert(marketScreener.includes('loadRestrictedScreenerSymbols'), 'screener must use a unified restricted-symbol gate')
  assert(marketScreener.includes('market:attention_stocks'), 'screener restricted gate must include attention-list KV fallback')
  assert(marketScreener.includes('loadSelectionHistoryFlags'), 'screener repeat/new-money history must be a reusable domain helper')
  assert(marketScreener.includes('highFreqPenalty'), 'screener high-frequency candidates must affect ranking, not only labels')
  assert(screenerMarketData.includes('dealer_buy'), 'screener chip data must include dealer flows for three-institution scoring')
  assert(schema.includes('screener_funnel_runs'), 'schema must include screener funnel run table')
  assert(schema.includes('screener_funnel_items'), 'schema must include screener funnel item table')
  assert(screenerFunnelMigration.includes('screener_funnel_items'), 'funnel migration must create item audit table')
  assert(marketScreener.includes('writeScreenerFunnel'), 'screener must persist per-run funnel evidence')
  assert(marketScreener.includes('rrg_overlay'), 'RRG must be recorded as overlay evidence, not opaque bonus text')
  assert(marketScreener.includes('buzz_evidence'), 'buzz concepts must be recorded as weighted evidence')
  assert(screenerPolicy.includes('candidate_pool_delta'), 'screener policy must support adaptive top-pool sizing')
  assert(screenerPolicy.includes('ml_shortlist_delta'), 'screener policy must support adaptive ML shortlist sizing')
  assert(screenerPolicy.includes('emerging_research_delta'), 'screener policy must support adaptive emerging research sizing')
  assert(screenerPolicy.includes('percentile_zscore'), 'screener scoring must support percentile/z-score calibration')
  assert(marketScreener.includes('research_only:emerging_not_for_auto_trade'), 'emerging screener rows must be tagged as research-only')
  assert(screenerSeedQuality.includes('market_segment'), 'screener seed SQL must persist market segment governance')
  assert(screenerSeedQuality.includes('recommendation_lane'), 'screener seed SQL must persist recommendation lane governance')
  assert(screenerSeedQuality.includes('eligible_for_pending_buy'), 'screener seed SQL must persist pending-buy eligibility')
  assert(pendingBuyOrchestrator.includes("from './boardTradability'"), 'pending-buy setup must consume the board/tradability contract')
  assert(pendingBuyOrchestrator.includes("NOT IN ('EMERGING', 'ESB')"), 'pending-buy setup must exclude explicit emerging-board stocks')
  assert(pendingBuyOrchestrator.includes('sp_exec.open'), 'pending-buy setup must reject emerging-style rows without an executable open price')
  assert(pendingBuyOrchestrator.includes('latest_avg_price'), 'pending-buy setup must inspect avg-price-only emerging-style rows')
  assert(pendingBuyOrchestrator.includes('candidateLimit'), 'pending-buy setup must fetch enough candidates before board/restriction filtering')
  assert(otherRoute.includes("from '../lib/boardTradability'"), 'recommendation API must expose board/tradability contract fields')
  assert(otherRoute.includes('persistedLane'), 'recommendation API must prefer persisted governance lane before board fallback')
  assert(otherRoute.includes('emerging_recommendations'), 'recommendation API must split emerging watchlist from tradable recommendations')
}

{
  assert(marketScreener.includes("from './screenerStrategyConsumer'"), 'marketScreener should consume strategy specs through the screener strategy consumer')
  assert(screenerStrategyConsumer.includes("from './strategySpec'"), 'screener strategy consumer should read the strategy spec contract')
  assert(screenerStrategyConsumer.includes("from './strategyOwnerFreeze'"), 'screener strategy consumer should enforce owner freeze')
  assert(strategyOwnerFreeze.includes('STRATEGY_OWNER_BOUNDARIES'), 'owner freeze must be explicit and testable')
  assert(!strategySpec.includes('../routes/'), 'strategy spec must not import route modules')
  assert(!/from ['"].*pendingBuy/i.test(strategySpec), 'strategy spec must not import pending-buy orchestration')
  assert(!/from ['"].*paper|from ['"].*execution/i.test(strategySpec), 'strategy spec must not import execution modules')
  assert(!strategyLab.includes('../routes/'), 'strategy lab MVP must not import routes')
  assert(!strategyLab.includes('env.DB'), 'strategy lab MVP should stay pure until a route/controller is intentionally added')
  assert(researchExperimentRegistry.includes('can_retrain_prod: false'), 'research registry must explicitly block prod retrain')
  assert(researchExperimentRegistry.includes('can_promote: false'), 'research registry must explicitly block promote')
  assert(researchExperimentRegistry.includes('can_deploy: false'), 'research registry must explicitly block deploy')
  assert(researchExperimentRegistry.includes('can_trade: false'), 'research registry must explicitly block trading')
  assert(!/controllerFetch|runWeeklyRetrain|promoteSandbox|setTradingConfig/.test(researchExperimentRegistry), 'research registry must not call production mutation workflows')
  assert(researchInternGate.includes("'deploy_prod'"), 'research gate must explicitly model deploy attempts')
  assert(researchInternGate.includes('FORBIDDEN_ACTIONS'), 'research gate must keep forbidden action list explicit')
  assert(!/controllerFetch|runWeeklyRetrain|promoteSandbox|setTradingConfig|env\.DB|KV\.put/.test(researchInternGate), 'research gate must stay pure and not call mutation workflows')
  assert(researchEvaluationPlan.includes("mode: 'dry_run_only'"), 'research evaluation plan must stay dry-run only')
  assert(researchEvaluationPlan.includes('mutation_allowed: false'), 'research evaluation plan must mark every step non-mutating')
  assert(!/controllerFetch|runWeeklyRetrain|promoteSandbox|setTradingConfig|env\.DB|KV\.put/.test(researchEvaluationPlan), 'research evaluation plan must not execute workflows directly')
}

{
  assert(!stocksRoute.includes('function computeTechnicalIndicators'), 'stocks route must not own indicator formula implementation')
  assert(stocksRoute.includes("../lib/technicalIndicators"), 'stocks route should call technical indicator domain service')
}
