const fs = require('fs')

export {}

function assert(condition: unknown, message: string): void {
  if (!condition) throw new Error(message)
}

const marketScreener = fs.readFileSync('src/lib/marketScreener.ts', 'utf8')
const pendingBuyOrchestrator = fs.readFileSync('src/lib/pendingBuyOrchestrator.ts', 'utf8')
const paperEntryTasks = fs.readFileSync('src/lib/paperEntryTasks.ts', 'utf8')
const updateOrchestrator = fs.readFileSync('src/lib/updateOrchestrator.ts', 'utf8')
const screenerMarketData = fs.readFileSync('src/lib/screenerMarketData.ts', 'utf8')
const screenerSeedQuality = fs.readFileSync('src/lib/screenerSeedQuality.ts', 'utf8')
const screenerPolicy = fs.readFileSync('src/lib/screenerPolicy.ts', 'utf8')
const tradingRestrictions = fs.readFileSync('src/lib/tradingRestrictions.ts', 'utf8')
const schema = fs.readFileSync('schema.sql', 'utf8')
const screenerFunnelMigration = fs.readFileSync('migration_screener_funnel.sql', 'utf8')
const sectorFlowTurnoverMigration = fs.readFileSync('migration_sector_flow_turnover_share_2026_05_26.sql', 'utf8')
const screenerStrategyConsumer = fs.readFileSync('src/lib/screenerStrategyConsumer.ts', 'utf8')
const strategyCandidatePool = fs.readFileSync('src/lib/strategyCandidatePool.ts', 'utf8')
const strategySpec = fs.readFileSync('src/lib/strategySpec.ts', 'utf8')
const strategyOwnerFreeze = fs.readFileSync('src/lib/strategyOwnerFreeze.ts', 'utf8')
const strategyLab = fs.readFileSync('src/lib/strategyLab.ts', 'utf8')
const researchExperimentRegistry = fs.readFileSync('src/lib/researchExperimentRegistry.ts', 'utf8')
const researchInternGate = fs.readFileSync('src/lib/researchInternGate.ts', 'utf8')
const researchEvaluationPlan = fs.readFileSync('src/lib/researchEvaluationPlan.ts', 'utf8')
const stocksRoute = fs.readFileSync('src/routes/stocks.ts', 'utf8')
const otherRoute = fs.readFileSync('src/routes/other.ts', 'utf8')
const screenerFunnelEvidence = fs.readFileSync('src/lib/screenerFunnelEvidence.ts', 'utf8')
const recommendationContext = fs.readFileSync('src/lib/recommendationContext.ts', 'utf8')
const multiStrategyPleRouter = fs.readFileSync('src/lib/multiStrategyPleRouter.ts', 'utf8')
const runtimeTeacherEvidence = fs.readFileSync('src/lib/runtimeTeacherEvidence.ts', 'utf8')
const adminReadRoutes = fs.readFileSync('src/routes/adminReadRoutes.ts', 'utf8')
const dailyPipeline = fs.readFileSync('../ml-controller/graphs/daily_pipeline_v2.py', 'utf8')

{
  assert(!fs.existsSync('src/lib/screenerPercentile.ts'), 'legacy 40/30/30 percentile screener owner should be removed')
  for (const source of [marketScreener, pendingBuyOrchestrator, paperEntryTasks, screenerMarketData, screenerPolicy]) {
    assert(!source.includes('screenerPercentile'), 'runtime screener paths must not import legacy percentile scorer')
  }
  assert(fs.existsSync('src/lib/screenerMarketData.ts'), 'screener market data loader should live in its own domain module')
  assert(marketScreener.includes("from './screenerMarketData'"), 'marketScreener should import the market data loader module')
  assert(!marketScreener.includes('async function loadMarketDataFromD1'), 'marketScreener should not own D1 market data loading')
  assert(marketScreener.includes('resolveScreenerRunDate'), 'screener must resolve an explicit rerun date instead of always using today')
  assert(marketScreener.includes('runBottomUpScreener(env: Bindings, runDate?: string | null)'), 'screener public contract must accept a backfill date')
  assert(screenerMarketData.includes('asOfDate?: string'), 'screener D1 loader must support as-of-date backfills')
  assert(screenerMarketData.includes('WHERE date <= ?'), 'screener D1 loader must cap price/chip data by requested date')
}

{
  assert(!marketScreener.includes("../routes/stocks"), 'screener lib must not import route modules')
  assert(!marketScreener.includes("from './stocks'"), 'screener lib must not import stocks route')
  assert(marketScreener.includes("from './technicalIndicators'"), 'screener should use technical indicator domain service')
  assert(screenerMarketData.includes('isAutoTradablePriceRow'), 'screener market data must own auto-tradable universe filtering')
  assert(screenerMarketData.includes("from './boardTradability'"), 'screener market data must consume the board/tradability contract')
  assert(screenerMarketData.includes('splitPriceRowsByBoard'), 'screener market data must expose board-lane splitting')
  assert(screenerMarketData.includes('emergingResearchPrices: []'), 'screener market data must keep emerging research prices retired')
  assert(marketScreener.includes('emerging research lane retired; skipped'), 'marketScreener must explicitly skip the retired emerging lane')
  assert(marketScreener.includes("from './screenerPolicy'"), 'marketScreener must consume adaptive screener policy')
  assert(marketScreener.includes('resolveScreenerPolicy'), 'marketScreener must resolve top-pool/shortlist/emerging sizes from policy')
  assert(!marketScreener.includes('slice(0, 100)'), 'screener top pool must not use hardcoded 100')
  assert(!marketScreener.includes('slice(0, 80)'), 'screener shortlist probes must not use hardcoded 80')
  assert(marketScreener.includes('loadRestrictedScreenerSymbols'), 'screener must use a unified restricted-symbol gate')
  assert(tradingRestrictions.includes('market:attention_stocks'), 'screener restricted gate must include attention-list KV fallback')
  assert(tradingRestrictions.includes('market:tpex_attention_stocks'), 'screener restricted gate must reserve TPEX attention-list source')
  assert(tradingRestrictions.includes('canonical_trading_restrictions'), 'screener restricted gate must include canonical D1 restriction governance')
  assert(tradingRestrictions.includes("normalizedType === 'attention'"), 'attention stocks must be explicit soft risk evidence, not hard blocks')
  assert(tradingRestrictions.includes("normalizedType === 'disposition'"), 'disposition/punish rows must be explicit soft risk evidence, not hard blocks')
  assert(!tradingRestrictions.includes("  'attention',\n"), 'attention must not be listed in hard restriction types')
  assert(!tradingRestrictions.includes("  'disposition',\n"), 'disposition must not be listed in hard restriction types')
  assert(updateOrchestrator.includes('fetchPunishedStocks'), 'market data update must refresh punished-stock cache, not leave screener as the only owner')
  assert(updateOrchestrator.includes('market:punished_stocks'), 'market data update must write punished-stock KV for downstream gates')
  assert(pendingBuyOrchestrator.includes('loadTradingRestrictionBuckets'), 'morning setup restricted gate must use shared hard/risk restriction buckets')
  assert(pendingBuyOrchestrator.includes('TRADING_ATTENTION_DEBATE_REQUIRED'), 'attention stocks must become debate-required risk evidence, not hard rejects')
  assert(pendingBuyOrchestrator.includes('trading_attention_risk_evidence'), 'morning setup must preserve attention-stock provenance in pending-buy watch points')
  assert(paperEntryTasks.includes('loadExecutionBlockedSymbols'), 'intraday execution must use the unified execution restricted-symbol gate')
  assert(paperEntryTasks.includes('loadTradingRestrictionBuckets'), 'intraday execution restricted gate must use shared hard/risk restriction buckets')
  assert(paperEntryTasks.includes('restricted_execution_gate'), 'intraday execution must record restricted-list skips with a dedicated reason')
  assert(!paperEntryTasks.includes('punished_or_attention_or_delisting'), 'intraday execution must not hard-block attention stocks after debate approval')
  assert(marketScreener.includes('loadSelectionHistoryFlags'), 'screener repeat/new-money history must be a reusable domain helper')
  assert(marketScreener.includes('dedupeScreenerCandidatesBySymbol'), 'screener must dedupe symbols before writing funnel counts and daily seeds')
  assert(marketScreener.includes('finalCandidates = dedupeScreenerCandidatesBySymbol'), 'tradable funnel count must use the deduped ML shortlist')
  assert(marketScreener.includes('buildLayer1StrategyBreadthPlan'), 'L1 breadth pool must be driven by the L1.5 adaptive router from the full feature-enriched universe')
  assert(!marketScreener.includes('preRankPool = scoredSorted.slice(0, screenerPolicy.sizing.candidatePoolSize)'), 'L1 breadth pool must not be pre-ranked by score top 200')
  assert(marketScreener.includes('layer1BreadthPool'), 'marketScreener should name the Layer1 breadth pool explicitly')
  assert(marketScreener.includes('passesLayer1TopUpQualityGuard'), 'post-overlay L1 top-up must not bypass raw strategy quality guards')
  assert(marketScreener.includes('research_strategy_ids'), 'production funnel evidence must keep research strategy attribution separate from active strategy ids')
  assert(!marketScreener.includes("['layer1_breadth']"), 'Layer1 top-up must not masquerade as a registered strategy id')
  assert(!marketScreener.includes('fallback to score-ranked L1 seed'), 'empty L1 breadth must not fall back to score-ranked tradable seeds')
  assert(marketScreener.includes('layer1_breadth_blocked_reason'), 'empty L1 breadth must surface a blocked reason')
  assert(marketScreener.includes('finalCandidates = []'), 'empty L1 breadth must fail closed before L2/L3 seeds')
  assert(marketScreener.includes('emergingMaxCandidates > 0 && emergingResearchPrices.length > 0'), 'retired emerging lane must be guarded behind explicit nonzero sizing and data')
  assert(marketScreener.includes('highFreqPenalty'), 'screener high-frequency candidates must affect ranking, not only labels')
  assert(screenerMarketData.includes('dealer_buy'), 'screener chip data must include dealer flows for three-institution scoring')
  assert(schema.includes('screener_funnel_runs'), 'schema must include screener funnel run table')
  assert(schema.includes('screener_funnel_items'), 'schema must include screener funnel item table')
  assert(screenerFunnelMigration.includes('screener_funnel_items'), 'funnel migration must create item audit table')
  assert(marketScreener.includes('writeScreenerFunnel'), 'screener must persist per-run funnel evidence')
  assert(marketScreener.includes("stage: 'l1_candidate_seed_after_overlay'"), 'screener must persist semantic L1 candidate seed stage before legacy final_selection alias')
  assert(marketScreener.includes("legacy_alias_stage: 'final_selection'"), 'screener must mark final_selection as a legacy alias, not the semantic post-ML final')
  assert(marketScreener.includes('SCREENER_FUNNEL_MAX_ITEMS = 5000'), 'screener funnel audit cap must keep strategy/final stages, not truncate at universe+scoring')
  assert(marketScreener.includes('SCREENER_FUNNEL_PIPELINE_SEED_STAGES'), 'screener funnel persistence must prioritize pipeline seed stages before large audit evidence')
  assert(
    marketScreener.includes("const initialStatus = input.status === 'success' ? 'error' : input.status"),
    'screener funnel persistence must use a non-success FK anchor until required item evidence is persisted',
  )
  assert(
    marketScreener.includes("status='error'") && marketScreener.includes('throw error'),
    'screener funnel persistence failure must mark the run error instead of leaving a partial success run',
  )
  assert(
    marketScreener.includes("console.warn('[Screener v2] funnel write failed:', e)") &&
    marketScreener.includes('throw e'),
    'screener must fail closed when funnel evidence persistence fails because pipeline requires L1 seed evidence',
  )
  assert(marketScreener.includes('rrg_overlay'), 'RRG must be recorded as overlay evidence, not opaque bonus text')
  assert(marketScreener.includes('latestThemeUniverse'), 'RRG overlay must align FinLab taxonomy tags to the latest sector_flow taxonomy universe')
  assert(marketScreener.includes("SELECT sector, classification, quadrant"), 'screener RRG overlay must keep sector_flow classification with the sector')
  assert(marketScreener.includes('AND rs_ratio IS NOT NULL'), 'screener RRG overlay must anchor to latest sector_flow snapshot with RS evidence, not stale latest non-null quadrant')
  assert(marketScreener.includes('turnover_share_delta'), 'screener RRG overlay must consume sector turnover share delta as flow confirmation')
  assert(marketScreener.includes('rrg_overlay_turnover_share_tailwind'), 'positive sector turnover share delta must be a distinct RRG evidence reason')
  assert(schema.includes('turnover_share_delta'), 'sector_flow schema must persist turnover share delta')
  assert(sectorFlowTurnoverMigration.includes('ALTER TABLE sector_flow ADD COLUMN turnover_share_delta REAL'), 'sector_flow turnover-share migration must add turnover_share_delta')
  assert(marketScreener.includes("latestThemeUniverse.has(`${candidateTag.classification}:${candidateTag.tag}`)"), 'screener RRG overlay must match taxonomy by classification+tag')
  assert(marketScreener.includes('taxonomyKey'), 'screener RRG overlay evidence must expose classification-tag taxonomy key')
  assert(marketScreener.includes('rrg_overlay_unmapped_neutral'), 'RRG overlay must record unmapped taxonomy as neutral evidence')
  assert(pendingBuyOrchestrator.includes('loadRrgTaxonomyTags'), 'pending-buy RRG gate must share the FinLab taxonomy tag contract')
  assert(pendingBuyOrchestrator.includes('FROM finlab_taxonomy_tags'), 'pending-buy RRG gate must read FinLab taxonomy before concept fallback')
  assert(pendingBuyOrchestrator.includes("tag_type IN ('industry_theme', 'subindustry', 'industry')"), 'pending-buy RRG gate must include industry/subindustry taxonomy')
  assert(pendingBuyOrchestrator.includes("classification IN ('industry', 'industry_theme', 'subindustry', 'theme')"), 'pending-buy RRG gate must align to four-layer sector_flow')
  assert(pendingBuyOrchestrator.includes('AND rs_ratio IS NOT NULL'), 'pending-buy RRG gate must not fall back to stale latest non-null quadrant dates')
  assert(dailyPipeline.includes("WHERE tag_type = 'concept' AND symbol IN"), 'pipeline persona concept sentiment must never mix industry/subindustry tags')
  assert(marketScreener.includes('buzz_evidence'), 'buzz concepts must be recorded as weighted evidence')
  assert(marketScreener.includes('materializeScreenerThemeRuntime'), 'screener seed write must materialize theme_signals/stock_theme_features for the same run date')
  assert(marketScreener.includes('refreshStockThemeFeaturesFromSignals'), 'theme runtime features must refresh from persisted same-date theme signals')
  assert(screenerPolicy.includes('candidate_pool_delta'), 'screener policy must support adaptive top-pool sizing')
  assert(screenerPolicy.includes('ml_shortlist_delta'), 'screener policy must support adaptive ML shortlist sizing')
  assert(screenerPolicy.includes('EMERGING_RESEARCH_SIZE = 0'), 'screener policy must keep emerging research sizing retired')
  assert(screenerPolicy.includes('percentile_zscore'), 'screener scoring must support percentile/z-score calibration')
  assert(marketScreener.includes('research_only:emerging_not_for_auto_trade'), 'emerging screener rows must be tagged as research-only')
  assert(screenerSeedQuality.includes('market_segment'), 'screener seed SQL must persist market segment governance')
  assert(screenerSeedQuality.includes('recommendation_lane'), 'screener seed SQL must persist recommendation lane governance')
  assert(screenerSeedQuality.includes('eligible_for_pending_buy'), 'screener seed SQL must persist pending-buy eligibility')
  assert(pendingBuyOrchestrator.includes("from './boardTradability'"), 'pending-buy setup must consume the board/tradability contract')
  assert(pendingBuyOrchestrator.includes("NOT IN ('EMERGING', 'ESB')"), 'pending-buy setup must exclude explicit emerging-board stocks')
  assert(pendingBuyOrchestrator.includes('sp_exec.open'), 'pending-buy setup must reject emerging-style rows without an executable open price')
  assert(pendingBuyOrchestrator.includes('latest_avg_price'), 'pending-buy setup must inspect avg-price-only emerging-style rows')
  assert(pendingBuyOrchestrator.includes("execution_pool_policy: 'l4_sparse_final_buy_only'"), 'pending-buy setup must only execute L4 sparse final BUY rows')
  assert(pendingBuyOrchestrator.includes("json_extract(dr.alpha_allocation, '$.selected') = 1"), 'pending-buy setup must require L4 sparse selected allocation evidence')
  assert(!pendingBuyOrchestrator.includes('candidateLimit'), 'pending-buy setup must not expand into a pre-L4 watch candidate pool')
  assert(pendingBuyOrchestrator.includes('themeUniverse'), 'pending-buy RRG gate must align taxonomy tags to the latest sector_flow universe')
  assert(pendingBuyOrchestrator.includes('classification: quadrant.classification'), 'pending-buy RRG logs must expose which taxonomy layer gated the stock')
  assert(pendingBuyOrchestrator.includes('RRG_UNMAPPED_NEUTRAL'), 'pending-buy RRG gate must log unmapped taxonomy as neutral, not block')
  assert(otherRoute.includes("from '../lib/boardTradability'"), 'recommendation API must expose board/tradability contract fields')
  assert(otherRoute.includes('persistedLane'), 'recommendation API must prefer persisted governance lane before board fallback')
  assert(otherRoute.includes('emerging_recommendations'), 'recommendation API must keep empty emerging payload compatibility while hiding the retired lane')
  assert(otherRoute.includes('summarizeScreenerFunnelRows'), 'recommendation API must expose full screener funnel evidence, not only final rank')
  assert(otherRoute.includes('summarizeStrategyPortfolioIntelligenceHealth'), 'recommendation API must expose top-level L1.25 strategy portfolio intelligence health')
  assert(otherRoute.includes('strategy_portfolio_intelligence_health'), 'daily recommendations response must include L1.25 strategy-as-asset metric health')
  assert(otherRoute.includes('screener_funnel_timeline'), 'recommendation API must return UI-readable screener funnel timeline')
  assert(otherRoute.includes("'universe'"), 'recommendation API must read Layer 0 universe evidence')
  assert(otherRoute.includes("'layer1_strategy_breadth_gate'"), 'recommendation API must read Layer 1 funnel evidence')
  assert(otherRoute.includes("'l15_ml_slate_queue'"), 'recommendation API must read L1.5 ML slate queue evidence')
  assert(otherRoute.includes("'layer2_timesfm_enrichment'"), 'recommendation API must read formal Layer 2 TimesFM funnel evidence')
  assert(otherRoute.includes("'layer3_formal_ml_gate'"), 'recommendation API must read Layer 3 formal ML funnel evidence')
  assert(otherRoute.includes("'l1_candidate_seed_after_overlay'"), 'recommendation API must read semantic L1 candidate seed evidence')
  assert(otherRoute.includes('buildSparseAllocationSummary'), 'recommendation API must summarize L4 sparse allocation evidence')
  assert(otherRoute.includes('buildHardGateSummary'), 'recommendation API must summarize L0.5 hard-gate evidence')
  assert(otherRoute.includes('l05_hard_gate'), 'recommendation API must expose L0.5 hard gate as a first-class response field')
  assert(otherRoute.includes('layer05_hard_gate'), 'recommendation API must attach L0.5 hard gate evidence to the funnel summary')
  assert(otherRoute.includes('l4_sparse_allocation'), 'recommendation API must expose L4 sparse allocation as a first-class response field')
  assert(otherRoute.includes('layer4_sparse_allocation'), 'recommendation API must attach L4 sparse allocation evidence to the funnel summary')
  assert(otherRoute.includes('resolveRecommendationGovernance'), 'recommendation API must apply board hard gates after persisted recommendation fields')
  assert(otherRoute.includes('turnover_share_delta'), 'sector-flow API trend payload must expose turnover share delta')
  assert(otherRoute.includes('latest_screener_run'), 'recommendation API must read funnel evidence from the latest screener run only')
  assert(screenerFunnelEvidence.includes('rrg_overlay'), 'funnel evidence summary must include RRG overlay')
  assert(screenerFunnelEvidence.includes('layer0_universe_features_summary_v1'), 'funnel evidence summary must expose stable L0 universe/features schema')
  assert(screenerFunnelEvidence.includes('feature_materialization_only_not_selector'), 'L0 features must stay materialization evidence, not selector/ranker evidence')
  assert(screenerFunnelEvidence.includes('no_topk_no_shrink'), 'L0 universe/features summary must explicitly reject top-k/shrink semantics')
  assert(screenerFunnelEvidence.includes('layer1_strategy_labeler_summary_v1'), 'funnel evidence summary must expose stable L1 strategy labeler schema')
  assert(screenerFunnelEvidence.includes('label_all_candidates_not_selector'), 'L1 strategy labeler must stay label-only, not selector/ranker evidence')
  assert(screenerFunnelEvidence.includes('strategy_affinity_family_affinity_weak_labels'), 'L1 strategy labeler must expose strategy/family affinity and weak-label scope')
  assert(screenerFunnelEvidence.includes('runtime_l0_universe_count_by_current_strategy_count'), 'L1 strategy labeler matrix must derive from runtime L0 universe and current strategy count')
  assert(screenerFunnelEvidence.includes('complete_strategy_dimension_with_zero_for_non_hits'), 'L1 strategy matrix must keep non-hit strategies as zero columns instead of sparse omissions')
  assert(screenerFunnelEvidence.includes('no_topk_no_shrink_no_minimum_fill'), 'L1 strategy labeler summary must explicitly reject top-k/shrink/minimum-fill semantics')
  assert(screenerFunnelEvidence.includes('layer125_finlab_portfolio_intelligence_summary_v1'), 'funnel evidence summary must expose stable L1.25 FinLab portfolio intelligence schema')
  assert(screenerFunnelEvidence.includes('daily_strategy_portfolio_intelligence_health_v1'), 'funnel evidence summary must expose stable daily L1.25 metric health schema')
  assert(screenerFunnelEvidence.includes('strategy_asset_weighting_not_stock_selector'), 'L1.25 FinLab portfolio intelligence must stay strategy-as-asset evidence, not stock selector evidence')
  assert(screenerFunnelEvidence.includes('strategy_prior_family_prior_reliability_crowding_diversification'), 'L1.25 FinLab portfolio intelligence must expose strategy prior/reliability/crowding/diversification scope')
  assert(screenerFunnelEvidence.includes('finlab_style_strategy_as_asset_portfolio_metrics'), 'L1.25 FinLab portfolio intelligence must document FinLab-style strategy-as-asset method')
  assert(screenerFunnelEvidence.includes('buzz_evidence'), 'funnel evidence summary must include buzz evidence')
  assert(screenerFunnelEvidence.includes('diversity_cooldown'), 'funnel evidence summary must include diversity/cooldown evidence')
  assert(screenerFunnelEvidence.includes('layer15_multi_strategy_router'), 'funnel evidence summary must include L1.25/L1.5 multi-strategy router evidence')
  assert(screenerFunnelEvidence.includes('multi_strategy_ple_listwise_distillation_router'), 'L1.5 router summary must expose PLE/Listwise router method')
  assert(screenerFunnelEvidence.includes('full_candidate_slate_to_diversified_ml_slate'), 'L1.5 router summary must route full slate into diversified ML slate')
  assert(screenerFunnelEvidence.includes('diversified_ml_slate_not_topk'), 'L1.5 router summary must stay diversified-slate based, not top-k')
  assert(screenerFunnelEvidence.includes('quality_floor_max_capacity_no_forced_fill'), 'L1.5 router summary must expose quality-floor max-capacity policy')
  assert(screenerFunnelEvidence.includes('candidate_route_score_ml_slate_eligibility_family_exposure_diversity_risk_uncertainty'), 'L1.5 router summary must expose router output scope')
  assert(screenerFunnelEvidence.includes('training_teacher_labels_offline_runtime_teacher_evidence_optional'), 'L1.5 router summary must distinguish offline training labels from optional runtime teacher evidence')
  assert(screenerFunnelEvidence.includes('previous_trading_day_or_latest_verified_cache_no_same_day_l2_l3_dependency'), 'L1.5 runtime teacher evidence must not depend on same-day L2/L3')
  assert(screenerFunnelEvidence.includes('ACTIVE_8_DIRECT_ALPHA_TEACHER_MODELS'), 'L1.5 router summary must keep the active 8ML teacher model contract visible')
  assert(screenerFunnelEvidence.includes('max_only_no_minimum_no_topup'), 'L1.5 router summary must expose max-only capacity with no garbage top-up')
  assert(screenerFunnelEvidence.includes('formal_ml_slate_no_minimum_fill'), 'L1.5 no-topup policy must scope to formal ML slate, not hide observe-only audit rows')
  assert(screenerFunnelEvidence.includes('research_observe_only_never_formal_l2'), 'raw-signal top-up must stay research/observe only and never formal L2')
  assert(screenerFunnelEvidence.includes('formal_l2_queue'), 'L1.5 router summary must expose whether the candidate entered formal L2')
  assert(screenerFunnelEvidence.includes('observe_only_top_up'), 'L1.5 router summary must expose observe-only top-up rows explicitly')
  assert(screenerFunnelEvidence.includes('layer3_formal_ml_gate'), 'funnel evidence summary must include Layer 3 formal ML evidence')
  assert(screenerFunnelEvidence.includes('layer2_timesfm_enrichment_summary_v1'), 'funnel evidence summary must expose stable L2 TimesFM schema')
  assert(screenerFunnelEvidence.includes('timesfm_sequence_sidecar_feature_enrichment_not_selector'), 'L2 TimesFM must stay feature enrichment, not selector/ranker evidence')
  assert(screenerFunnelEvidence.includes('layer3_8ml_formal_summary_v1'), 'funnel evidence summary must expose stable L3 8ML formal schema')
  assert(screenerFunnelEvidence.includes('eight_ml_formal_family_evidence_not_topk'), 'L3 8ML formal must stay family evidence, not top-k')
  assert(screenerFunnelEvidence.includes("'TimesFM'"), 'L2 TimesFM model id must stay visible in the funnel summary contract')
  assert(screenerFunnelEvidence.includes("'LightGBM', 'XGBoost', 'ExtraTrees', 'TabM', 'GNN', 'DLinear', 'PatchTST', 'iTransformer'"), 'L3 8ML model ids must stay visible in the funnel summary contract')
  assert(screenerFunnelEvidence.includes('layer35_evidence_fusion'), 'funnel evidence summary must include L3.5 strategy-vs-ML evidence fusion')
  assert(screenerFunnelEvidence.includes('strategy_router_vs_8ml_formal_family_evidence_calibration'), 'L3.5 evidence fusion must expose strategy-vs-8ML calibration method')
  assert(screenerFunnelEvidence.includes('layer15_route_score_layer3_formal_family_score_uncertainty_active_family_count'), 'L3.5 evidence fusion must expose input scope')
  assert(screenerFunnelEvidence.includes('observe_only_no_hard_shrink'), 'L3.5 evidence fusion must stay observable and never hard-shrink candidates')
  assert(screenerFunnelEvidence.includes('no_candidate_drop_no_topk_no_minimum_fill'), 'L3.5 evidence fusion must not drop/top-k/fill candidates')
  assert(screenerFunnelEvidence.includes('hard_shrink_allowed: false'), 'L3.5 evidence fusion must explicitly keep hard shrink disabled')
  assert(screenerFunnelEvidence.includes("final_allocation_owner: 'layer4_sparse_allocation'"), 'L3.5 evidence fusion must defer final allocation to L4 sparse')
  assert(screenerFunnelEvidence.includes('flag_conflict_for_l4_sparse_without_hard_drop'), 'L3.5 high conflict must flag L4 sparse without hard-dropping')
  assert(screenerFunnelEvidence.includes('pickCandidateSeedStep'), 'funnel evidence must prefer semantic L1 candidate seed over legacy final_selection')
  assert(screenerFunnelEvidence.includes('finalSelection?.evidence?.strategy_pool_ids'), 'funnel evidence summary must expose final selection strategy ids when explicit strategy_pool rows are absent')
  assert(recommendationContext.includes('l4_sparse_allocation_summary_v1'), 'recommendation context must expose a stable L4 sparse allocation summary schema')
  assert(recommendationContext.includes('l05_hard_gate_summary_v1'), 'recommendation context must expose a stable L0.5 hard gate summary schema')
  assert(recommendationContext.includes('exclude_untradable_or_untrusted_only_not_alpha_ranker'), 'L0.5 hard gate must document that it is not an alpha ranker')
  assert(recommendationContext.includes('tradeability_data_trust_pending_buy'), 'L0.5 hard gate must document tradability/data trust/pending-buy scope')
  assert(recommendationContext.includes('final_owner_no_topk_fallback'), 'L4 sparse allocation summary must document no legacy top-k fallback')
  assert(recommendationContext.includes('sparse_tangent_inverse_risk_final_allocation'), 'L4 sparse allocation summary must expose sparse final allocation method')
  assert(recommendationContext.includes('post_l3_5_evidence_fusion_candidates'), 'L4 sparse allocation summary must consume post-L3.5 evidence candidates')
  assert(recommendationContext.includes('positive_expected_edge_sparse_weights_no_forced_fill'), 'L4 sparse allocation summary must require positive expected edge without forced fill')
  assert(recommendationContext.includes('l3_5_flags_conflict_l4_decides_weight_not_drop'), 'L4 sparse allocation summary must consume L3.5 conflict flags without hard-dropping')
  assert(recommendationContext.includes('buy_hold_weight_zero_to_capacity'), 'L4 sparse allocation summary must own final BUY/HOLD/weight decisions')
  assert(recommendationContext.includes('maximum_capacity_not_minimum_fill'), 'L4 sparse allocation summary must document capacity as maximum, not minimum fill')
  assert(recommendationContext.includes('max_capacity_not_target: true'), 'L4 sparse allocation summary must document max-capacity-not-target semantics')
  assert(recommendationContext.includes('hard_minimum_fill: false'), 'L4 sparse allocation summary must keep hard minimum fill disabled')
  assert(recommendationContext.includes('allows_empty_portfolio: true'), 'L4 sparse allocation summary must allow empty portfolio output')
  assert(recommendationContext.includes('zero_selection_allowed'), 'L4 sparse allocation summary must document that final allocation can select zero rows')
  assert(recommendationContext.includes('legacy_topk_fallback_allowed: false'), 'L4 sparse allocation summary must keep legacy top-k fallback explicitly disabled')
  assert(recommendationContext.includes('legacy_rank_topk_fallback_allowed: false'), 'L4 sparse allocation summary must keep rank-topK fallback explicitly disabled')
  assert(marketScreener.includes('strategy_affinity_vector'), 'screener must persist L1 strategy affinity vectors into funnel evidence')
  assert(marketScreener.includes('strategy_matrix_strategy_count'), 'screener must persist dynamic L1 strategy matrix strategy count into funnel evidence')
  assert(marketScreener.includes('production_seed_allowed: false'), 'strategy_pool_ml_queue must be audit-only and blocked from production seed ownership')
  assert(dailyPipeline.includes("sfi.stage = 'l1_candidate_seed_after_overlay' AND sfi.decision = 'selected'"), 'daily pipeline production seed must be L1.5 router slate')
  assert(!dailyPipeline.includes('strategy_pool_ml_queue'), 'daily pipeline must not use strategy_pool_ml_queue as production ML seed')
  assert(marketScreener.includes('strategy_family_affinity'), 'screener must persist L1 family affinity vectors into funnel evidence')
  assert(marketScreener.includes('strategy_weak_label_vector'), 'screener must persist L1 weak-label vectors into funnel evidence')
  assert(marketScreener.includes('finlab_portfolio_intelligence_version'), 'screener must persist L1.25 FinLab portfolio intelligence version into funnel evidence')
  assert(marketScreener.includes("import { loadRuntimeTeacherEvidence } from './runtimeTeacherEvidence'"), 'screener must load runtime teacher evidence through the dedicated owner module')
  assert(marketScreener.includes('const runtimeTeacherEvidence = await loadRuntimeTeacherEvidence'), 'daily L1.5 must load optional historical runtime teacher evidence before routing')
  assert(marketScreener.includes('runtimeTeacherEvidence: runtimeTeacherEvidence.labels'), 'daily L1.5 must pass runtimeTeacherEvidence, not deprecated mlTeacherLabels')
  assert(!marketScreener.includes('mlTeacherLabels:'), 'daily screener must not pass deprecated mlTeacherLabels as the formal router input')
  assert(strategyCandidatePool.includes('runtimeTeacherEvidence?: Record<string, Record<string, number>>'), 'Layer1 breadth plan must accept runtimeTeacherEvidence as optional input')
  assert(strategyCandidatePool.includes('runtimeTeacherEvidence: options.runtimeTeacherEvidence'), 'Layer1 breadth plan must forward runtimeTeacherEvidence into L1.5 router')
  assert(multiStrategyPleRouter.includes('/** @deprecated Daily routing should pass runtimeTeacherEvidence'), 'router may keep mlTeacherLabels only as a deprecated compatibility alias')
  assert(runtimeTeacherEvidence.includes('p.prediction_date < ?'), 'runtime teacher evidence must not read same-day L2/L3 rows')
  assert(runtimeTeacherEvidence.includes('p.verified_at IS NOT NULL'), 'runtime teacher evidence must default to verified teacher cache only')
  assert(marketScreener.includes('runtime_teacher_evidence'), 'screener must persist L1.5 runtime teacher evidence into funnel evidence')
  assert(marketScreener.includes('ml_teacher_labels'), 'screener may keep ml_teacher_labels as legacy funnel alias')
}

{
  assert(marketScreener.includes("from './screenerStrategyConsumer'"), 'marketScreener should consume strategy specs through the screener strategy consumer')
  assert(marketScreener.includes("import('./strategyCandidatePool')"), 'marketScreener should use strategy-first candidate pools before ML shortlist selection')
  assert(marketScreener.includes('strategyCandidatePool'), 'screener funnel metadata should include strategy candidate pool telemetry')
  assert(marketScreener.includes('layer1_strategy_breadth_gate'), 'screener must persist Layer 1 strategy breadth gate evidence')
  assert(marketScreener.includes("stage: 'l15_ml_slate_queue'"), 'screener must persist L1.5 ML slate queue evidence before controller L2')
  assert(marketScreener.includes("downstream_stage: 'layer2_timesfm_enrichment'"), 'Worker ML slate queue must point to ml-controller formal L2 owner without owning L2')
  assert(!/\bstage:\s*'layer2_coarse_ml_gate'/.test(marketScreener), 'Worker screener must not persist itself as formal L2 coarse gate owner')
  assert(strategyCandidatePool.includes('baseTotalBudget: 64'), 'strategy candidate pool should keep 64 as the base ML allocation budget')
  assert(strategyCandidatePool.includes('normalTotalCap: 96'), 'strategy candidate pool should expose adaptive 96 normal cap')
  assert(strategyCandidatePool.includes('lowLoadTotalCap: 128'), 'strategy candidate pool should expose adaptive 128 low-load cap')
  assert(strategyCandidatePool.includes('hardTotalCap: 160'), 'strategy candidate pool should expose hard 160 cap')
  assert(strategyCandidatePool.includes('researchOnlyQueue'), 'strategy candidate pool should route overflow into research-only queue instead of silently dropping')
  assert(strategyCandidatePool.includes('adaptive_empty_pool_ranked_near_match'), 'empty strict strategy pools must still emit explicit shadow near-match candidates instead of leaving UI untagged')
  assert(strategySpec.includes('canonicalFinal ?? snapshot.finalScore'), 'strategy pools must use canonical Score V2 finalScore or total, not scalar storage fallback')
  assert(strategySpec.includes("'bull', 'sideways', 'volatile'"), 'trend strategy must remain available in volatile regime for shadow candidate discovery')
  assert(strategySpec.includes("'bull', 'sideways', 'bear', 'volatile'"), 'defensive strategy must remain available in volatile regime for shadow candidate discovery')
  assert(screenerStrategyConsumer.includes("from './strategySpec'"), 'screener strategy consumer should read the strategy spec contract')
  assert(screenerStrategyConsumer.includes("from './strategyOwnerFreeze'"), 'screener strategy consumer should enforce owner freeze')
  assert(strategyOwnerFreeze.includes('STRATEGY_OWNER_BOUNDARIES'), 'owner freeze must be explicit and testable')
  assert(!strategySpec.includes('../routes/'), 'strategy spec must not import route modules')
  assert(!/from ['"].*pendingBuy/i.test(strategySpec), 'strategy spec must not import pending-buy orchestration')
  assert(!/from ['"].*paper|from ['"].*execution/i.test(strategySpec), 'strategy spec must not import execution modules')
  assert(!strategyLab.includes('../routes/'), 'strategy lab MVP must not import routes')
  assert(!strategyLab.includes('env.DB'), 'strategy lab MVP should stay pure until a route/controller is intentionally added')
  assert(!strategyLab.includes('DEFAULT_STRATEGY_SPECS'), 'strategy lab must not own runtime strategy defaults')
  assert(adminReadRoutes.includes('listStrategySpecsForLearning'), 'strategy admin dry-run must load runtime specs from D1 registry')
  assert(adminReadRoutes.includes('listStrategyLearningCandidates'), 'strategy admin dry-run must use L0/scoring funnel candidates by default')
  assert(adminReadRoutes.includes("source: candidateSource"), 'strategy admin dry-run must disclose its candidate source')
  assert(!/FROM daily_recommendations[\s\S]{0,260}strategy\/dry-run/.test(adminReadRoutes), 'strategy admin dry-run must not fall back to daily_recommendations candidates')
  assert(researchExperimentRegistry.includes('can_retrain_prod: false'), 'research registry must explicitly block prod retrain')
  assert(researchExperimentRegistry.includes('can_promote: false'), 'research registry must explicitly block promote')
  assert(researchExperimentRegistry.includes('can_deploy: false'), 'research registry must explicitly block deploy')
  assert(researchExperimentRegistry.includes('can_trade: false'), 'research registry must explicitly block trading')
  assert(!/controllerFetch|runWeeklyRetrain|promoteSandbox|setTradingConfig/.test(researchExperimentRegistry), 'research registry must not call production mutation workflows')
  assert(researchInternGate.includes("'deploy_prod'"), 'research gate must explicitly model deploy attempts')
  assert(researchInternGate.includes('FORBIDDEN_ACTIONS'), 'research gate must keep forbidden action list explicit')
  assert(!/controllerFetch|runWeeklyRetrain|promoteSandbox|setTradingConfig|env\.DB|KV\.put/.test(researchInternGate), 'research gate must stay pure and not call mutation workflows')
  assert(researchEvaluationPlan.includes("mode: 'dry_run_only'"), 'research evaluation plan must stay dry-run only')
  assert(researchEvaluationPlan.includes('mutation_allowed: false'), 'research evaluation plan must mark every step non-mutating')
  assert(!/controllerFetch|runWeeklyRetrain|promoteSandbox|setTradingConfig|env\.DB|KV\.put/.test(researchEvaluationPlan), 'research evaluation plan must not execute workflows directly')
}

{
  assert(!stocksRoute.includes('function computeTechnicalIndicators'), 'stocks route must not own indicator formula implementation')
  assert(stocksRoute.includes("../lib/technicalIndicators"), 'stocks route should call technical indicator domain service')
}
