import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const router = readFileSync(new URL('./multiStrategyPleRouter.ts', import.meta.url), 'utf8')
const spec = readFileSync(new URL('./strategySpec.ts', import.meta.url), 'utf8')
const calibration = readFileSync(new URL('./strategyRouteCalibration.ts', import.meta.url), 'utf8')
const maturity = readFileSync(new URL('./pipelineDecisionMaturity.ts', import.meta.url), 'utf8')
const backfill = readFileSync(new URL('./strategyRouteBackfillEligibility.ts', import.meta.url), 'utf8')
const eveningClosure = readFileSync(new URL('./eveningChainEvidenceClosure.ts', import.meta.url), 'utf8')
const migration = readFileSync(new URL('../../domain-migrations/learning/0025_strategy_route_versioned_evidence.sql', import.meta.url), 'utf8')
const materializer = readFileSync(new URL('../../../tools/materialize_l1_l15_v4_evidence.mjs', import.meta.url), 'utf8')

assert.match(router, /strategySpecForSemanticV2Challenger/)
assert.match(router, /const challengerStates = buildCandidateLabelStates\(candidates, semanticV2ChallengerSpecs, options\)/)
assert.match(router, /strategy_incumbent_route_score: routeScore/)
assert.match(router, /strategy_challenger_route_score: challengerRouteScore/)
assert.match(spec, /STRATEGY_SEMANTIC_V2_ALPHA_IDS/)
assert.match(spec, /capital_normalized_cross_sectional_percentile/)
assert.match(spec, /finlabCsV2TechGapDownNoGapRank/)

assert.match(calibration, /STRATEGY_ROUTE_CHALLENGER_VERSION = 'strategy-semantic-continuous-affinity-v4'/)
assert.match(calibration, /STRATEGY_ROUTE_AFFINITY_VERSION = 'strategy-threshold-margin-affinity-v2'/)
assert.match(maturity, /version: STRATEGY_ROUTE_AFFINITY_VERSION/)
assert.match(maturity, /LEFT JOIN strategy_route_versioned_evidence_v1 e/)
assert.match(backfill, /STRATEGY_ROUTE_AFFINITY_VERSION/)
assert.match(backfill, /LEFT JOIN strategy_route_versioned_evidence_v1 e/)
assert.match(eveningClosure, /STRATEGY_ROUTE_AFFINITY_VERSION/)
assert.doesNotMatch(eveningClosure, /STRATEGY_ROUTE_CHALLENGER_VERSION/)
assert.match(calibration, /FROM strategy_route_versioned_evidence_v1 e/)
assert.match(calibration, /UNION ALL/)
assert.match(calibration, /NOT EXISTS \(/)
assert.match(calibration, /l\.outcome_known_date <= \?/)
assert.match(calibration, /canonicalRunIds/)

assert.match(migration, /PRIMARY KEY\(route_version, signal_date, symbol, producer_run_id\)/)
assert.match(migration, /CHECK\(production_effect = 0\)/)
assert.match(migration, /source_sha TEXT NOT NULL/)
assert.match(materializer, /--confirm-production-effect-none/)
assert.match(materializer, /immutable_v4_evidence_conflict/)
assert.match(materializer, /INSERT OR IGNORE INTO strategy_route_versioned_evidence_v1/)
assert.match(materializer, /materializer_requires_clean_tracked_worktree/)
assert.doesNotMatch(materializer, /UPDATE strategy_route_versioned_evidence_v1/)
assert.doesNotMatch(materializer, /DELETE FROM strategy_route_versioned_evidence_v1/)

console.log('strategy route versioned evidence contract passed')
