import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const router = readFileSync(new URL('./multiStrategyPleRouter.ts', import.meta.url), 'utf8')
const spec = readFileSync(new URL('./strategySpec.ts', import.meta.url), 'utf8')
const calibration = readFileSync(new URL('./strategyRouteCalibration.ts', import.meta.url), 'utf8')
const maturity = readFileSync(new URL('./pipelineDecisionMaturity.ts', import.meta.url), 'utf8')
const backfill = readFileSync(new URL('./strategyRouteBackfillEligibility.ts', import.meta.url), 'utf8')
const eveningClosure = readFileSync(new URL('./eveningChainEvidenceClosure.ts', import.meta.url), 'utf8')
const migration = readFileSync(new URL('../../domain-migrations/learning/0025_strategy_route_versioned_evidence.sql', import.meta.url), 'utf8')
const materializer = readFileSync(new URL('../../../tools/materialize_l1_l15_v4_evidence.mjs', import.meta.url), 'utf8')
const comparison = readFileSync(new URL('../../../tools/compare_l1_l15_semantic_versions.ts', import.meta.url), 'utf8')
const v5Replay = readFileSync(new URL('../../../tools/replay_l1_l15_v5_evidence.ts', import.meta.url), 'utf8')

assert.match(router, /strategySpecForSemanticV2Challenger/)
assert.match(router, /const challengerStates = buildCandidateLabelStates\(candidates, semanticV2ChallengerSpecs, options\)/)
assert.match(router, /strategy_incumbent_route_score: routeScore/)
assert.match(router, /strategy_challenger_route_score: challengerRouteScore/)
assert.match(spec, /STRATEGY_SEMANTIC_V2_ALPHA_IDS/)
assert.match(spec, /capital_normalized_cross_sectional_percentile/)
assert.match(spec, /finlabCsV2TechGapDownNoGapRank/)

assert.match(calibration, /STRATEGY_ROUTE_CHALLENGER_VERSION = SELECTION_ROUTE_SEMANTIC_VERSION/)
assert.match(calibration, /STRATEGY_ROUTE_AFFINITY_VERSION = 'strategy-threshold-margin-affinity-v2'/)
assert.match(maturity, /version: STRATEGY_ROUTE_AFFINITY_VERSION/)
assert.match(maturity, /LEFT JOIN strategy_route_versioned_evidence_v1 e/)
assert.match(backfill, /STRATEGY_ROUTE_AFFINITY_VERSION/)
assert.match(backfill, /LEFT JOIN strategy_route_versioned_evidence_v1 e/)
assert.match(eveningClosure, /STRATEGY_ROUTE_AFFINITY_VERSION/)
assert.doesNotMatch(eveningClosure, /STRATEGY_ROUTE_CHALLENGER_VERSION/)
assert.match(calibration, /FROM strategy_route_versioned_evidence_v1 e/)
assert.match(calibration, /UNION ALL/)
assert.match(calibration, /NOT EXISTS \(/)
assert.match(calibration, /l\.outcome_known_date <= \?/)
assert.match(calibration, /canonicalRunIds/)

assert.match(migration, /PRIMARY KEY\(route_version, signal_date, symbol, producer_run_id\)/)
assert.match(migration, /CHECK\(production_effect = 0\)/)
assert.match(migration, /source_sha TEXT NOT NULL/)
assert.match(materializer, /--confirm-production-effect-none/)
assert.match(materializer, /immutable_route_evidence_conflict/)
assert.match(materializer, /--route-version/)
assert.match(materializer, /strategy-semantic-continuous-affinity-v5/)
assert.match(materializer, /INSERT OR IGNORE INTO strategy_route_versioned_evidence_v1/)
assert.match(materializer, /materializer_requires_clean_tracked_worktree/)
assert.match(materializer, /validateStoredRows\(existing, 'existing'\)/)
assert.match(materializer, /strategy-route-evidence-/)
assert.match(comparison, /for \(const context of contexts\)/)
assert.match(comparison, /evidence_rows: versionedEvidenceRows\.length/)
assert.match(comparison, /full_reference_route_missing/)
assert.match(v5Replay, /l1-l15-v5-immutable-deterministic-replay-v2/)
assert.match(v5Replay, /evidence_method: "canonical_v5_carrier"/)
assert.match(v5Replay, /eligibility\?\.status === "pending_maturity"/)
assert.match(v5Replay, /pending_dates: pending/)
assert.match(v5Replay, /strategyRegistryFingerprintPayload\(historicalRegistry\)/)
assert.match(v5Replay, /historical_strategy_registry_fingerprint_mismatch/)
assert.match(v5Replay, /matrix_strategy_grid_shape_mismatch/)
assert.match(v5Replay, /SELECTION_REFERENCE_CONTRACT_VERSION/)
assert.match(v5Replay, /FROM strategy_spec_registry ORDER BY strategy_id, version/)
assert.match(v5Replay, /score_generation_uses_outcomes: false/)
assert.match(v5Replay, /incumbent_replay_parity_mismatch/)
assert.match(v5Replay, /strategy_label_matrix_runs_v4/)
assert.match(v5Replay, /strategy_candidate_contexts/)
assert.match(v5Replay, /outcome_known_date/)
assert.doesNotMatch(v5Replay, /slice(0,s*w+)/)
assert.doesNotMatch(materializer, /UPDATE strategy_route_versioned_evidence_v1/)
assert.doesNotMatch(materializer, /DELETE FROM strategy_route_versioned_evidence_v1/)

console.log('strategy route versioned evidence contract passed')
