INSERT INTO strategy_spec_registry (
  strategy_id,
  version,
  name,
  status,
  owner,
  alpha_bucket,
  family_id,
  variant_id,
  owner_type,
  promotion_status,
  supported_regimes_json,
  thesis,
  thresholds_json,
  candidate_policy_json,
  risk_notes_json,
  source_refs_json,
  created_by,
  created_at,
  updated_at
)
VALUES
(
  'alpha_miner_pymoo_nsga3_novelty_0081',
  'strategy-spec-v1',
  'Pymoo NSGA-III novelty 0081 breadth trend impulse',
  'active',
  'strategy',
  'trend_following',
  'TREND_RECLAIM_CONTINUATION',
  'canonical114_klow2_advance_cntd_ksft_v1',
  'strategy',
  'production',
  '["bull","sideways","volatile"]',
  'Promoted mined strategy 0081: market breadth plus short-term trend and volume continuation evidence discovered by pymoo NSGA-III plus novelty search.',
  '{"minPrice":10,"minVolumeExpansion20":0.7,"minFactorSignals":{"alphaMinerPymoo0081Score":0.62}}',
  '{"poolQuota":16,"costBudget":18,"evidenceRequirements":["alpha_mining:pymoo_nsga3_novelty","canonical114","runtime_composite:alphaMinerPymoo0081Score"],"maxMlShare":0.2}',
  '["Original mined factors: KLOW2 0.415128, advance_ratio 0.117772, CNTD_20 0.20684, KSFT 0.260259.","FinLab confirm: CAGR 53.0%, monthly Sharpe 1.36, max drawdown -16.5%, Calmar 3.21."]',
  '["alpha_miner:pymoo_nsga3_novelty","finlab_confirm:20230101_20260615","strategy_registry_seed:20260617"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'alpha_miner_pymoo_nsga3_novelty_0193',
  'strategy-spec-v1',
  'Pymoo NSGA-III novelty 0193 sentiment margin flow',
  'active',
  'strategy',
  'defensive_accumulation',
  'SMART_MONEY_ACCUMULATION',
  'us_sentiment_margin_balance_v1',
  'strategy',
  'production',
  '["bull","sideways","volatile"]',
  'Promoted mined strategy 0193: US leading sentiment and margin-balance participation evidence discovered by pymoo NSGA-III plus novelty search.',
  '{"minPrice":10,"minVolumeExpansion20":0.5,"minFactorSignals":{"alphaMinerPymoo0193Score":0.58}}',
  '{"poolQuota":16,"costBudget":18,"evidenceRequirements":["alpha_mining:pymoo_nsga3_novelty","us_market_signals","margin_balance","runtime_composite:alphaMinerPymoo0193Score"],"maxMlShare":0.2}',
  '["Original mined factors: us_sentiment_score 0.479025, margin_balance 0.520975.","FinLab confirm: CAGR 50.6%, monthly Sharpe 1.23, max drawdown -21.3%, Calmar 2.38."]',
  '["alpha_miner:pymoo_nsga3_novelty","finlab_confirm:20230101_20260615","strategy_registry_seed:20260617"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'alpha_miner_pymoo_nsga3_novelty_0187',
  'strategy-spec-v1',
  'Pymoo NSGA-III novelty 0187 revenue short trend',
  'active',
  'strategy',
  'trend_following',
  'REVENUE_QUALITY_MOMENTUM',
  'revenue_mom_ma10_return5_v1',
  'strategy',
  'production',
  '["bull","sideways","volatile"]',
  'Promoted mined strategy 0187: revenue momentum plus MA10 and 5-day continuation evidence discovered by pymoo NSGA-III plus novelty search.',
  '{"minPrice":10,"minVolumeExpansion20":0.55,"minFactorSignals":{"alphaMinerPymoo0187Score":0.6}}',
  '{"poolQuota":16,"costBudget":18,"evidenceRequirements":["alpha_mining:pymoo_nsga3_novelty","canonical114","monthly_revenue","runtime_composite:alphaMinerPymoo0187Score"],"maxMlShare":0.2}',
  '["Original mined factors: KSFT2 0.300141, l1_monthlyRevenueMoM 0.056417, CNTN_20 0.106408, ma10_bias 0.351215, return_5d 0.185819.","FinLab confirm: CAGR 29.9%, monthly Sharpe 0.73, max drawdown -27.6%, Calmar 1.08."]',
  '["alpha_miner:pymoo_nsga3_novelty","finlab_confirm:20230101_20260615","strategy_registry_seed:20260617"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT(strategy_id, version) DO UPDATE SET
  name=excluded.name,
  status=excluded.status,
  owner=excluded.owner,
  alpha_bucket=excluded.alpha_bucket,
  family_id=excluded.family_id,
  variant_id=excluded.variant_id,
  owner_type=excluded.owner_type,
  promotion_status=excluded.promotion_status,
  supported_regimes_json=excluded.supported_regimes_json,
  thesis=excluded.thesis,
  thresholds_json=excluded.thresholds_json,
  candidate_policy_json=excluded.candidate_policy_json,
  risk_notes_json=excluded.risk_notes_json,
  source_refs_json=excluded.source_refs_json,
  created_by=excluded.created_by,
  updated_at=CURRENT_TIMESTAMP;

UPDATE strategy_spec_registry
   SET status='retired',
       owner_type='retired',
       promotion_status='retired',
       updated_at=CURRENT_TIMESTAMP
 WHERE status != 'retired'
   AND strategy_id NOT IN (
     'trend_following_seed_v1',
     'breakout_vol_expansion_seed_v1',
     'defensive_accumulation_seed_v1',
     'finlab_ai_skill_quality_trend_v1',
     'finlab_ai_skill_reversion_value_v1',
     'finlab_ai_skill_revenue_revision_breakout_v1',
     'finlab_ai_skill_broker_accumulation_reclaim_v1',
     'alphabuilders_multifactor_revenue_quality_momentum_v1',
     'alpha_miner_pymoo_nsga3_novelty_0081',
     'alpha_miner_pymoo_nsga3_novelty_0193',
     'alpha_miner_pymoo_nsga3_novelty_0187'
   );
