-- StockVision 12 technical StrategySpec challenger candidates.
-- Research/challenger registry only; no production-active promotion.
-- Apply after review:
--   cd worker
--   npx wrangler@4 d1 execute stockvision-db --remote --file=./migration_stock_technical_strategy12_challengers_2026_06_25.sql

INSERT INTO strategy_spec_registry (
  strategy_id,
  version,
  name,
  status,
  owner,
  alpha_bucket,
  family_id,
  variant_id,
  owner_type,
  promotion_status,
  supported_regimes_json,
  thesis,
  thresholds_json,
  candidate_policy_json,
  risk_notes_json,
  source_refs_json,
  created_by,
  created_at,
  updated_at
)
VALUES
(
  'stock_tech_s01_55d_trend_volume_breakout_v1',
  'strategy-spec-v1',
  'S1 55d trend volume breakout',
  'candidate',
  'strategy',
  'breakout_vol_expansion',
  'TREND_RECLAIM_CONTINUATION',
  's01_55d_trend_volume_breakout_v1',
  'strategy',
  'candidate',
  '["bull","volatile"]',
  '55-day trend and volume breakout challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS01Score","op":">=","value":1}]},"technicalStrategy":{"id":"S1","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS01Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_price_structure","raw_volume","materialized_score:stockTechS01Score"],"maxMlShare":0}',
  '["Candidate only. FinLab research benchmark required before paper-active approval.","Runtime matching is fail-closed until stockTechS01Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s02_52w_dual_momentum_v1',
  'strategy-spec-v1',
  'S2 52w dual momentum',
  'candidate',
  'strategy',
  'trend_following',
  'TREND_RECLAIM_CONTINUATION',
  's02_52w_dual_momentum_v1',
  'strategy',
  'candidate',
  '["bull","sideways"]',
  '52-week high and 12-1 momentum monthly challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS02Score","op":">=","value":1}]},"technicalStrategy":{"id":"S2","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS02Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_momentum","monthly_rebalance","materialized_score:stockTechS02Score"],"maxMlShare":0}',
  '["Candidate only. Monthly strategy; compare separately from daily event strategies.","Runtime matching is fail-closed until stockTechS02Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s03_vcp_contraction_breakout_v1',
  'strategy-spec-v1',
  'S3 VCP contraction breakout',
  'candidate',
  'strategy',
  'breakout_vol_expansion',
  'VOLATILITY_CONTRACTION_BREAKOUT',
  's03_vcp_contraction_breakout_v1',
  'strategy',
  'candidate',
  '["bull","volatile"]',
  'VCP contraction and breakout challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS03Score","op":">=","value":1}]},"technicalStrategy":{"id":"S3","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS03Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_price_structure","raw_volume","materialized_score:stockTechS03Score"],"maxMlShare":0}',
  '["Candidate only. Boolean FinLab position cannot fully model ATR trailing exit.","Runtime matching is fail-closed until stockTechS03Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s04_ma_deduct_turn_breakout_v1',
  'strategy-spec-v1',
  'S4 MA deduct turn breakout',
  'candidate',
  'strategy',
  'trend_following',
  'TREND_RECLAIM_CONTINUATION',
  's04_ma_deduct_turn_breakout_v1',
  'strategy',
  'candidate',
  '["bull","sideways"]',
  'Moving-average deduct turn plus range breakout challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS04Score","op":">=","value":1}]},"technicalStrategy":{"id":"S4","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS04Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_price_structure","raw_volume","materialized_score:stockTechS04Score"],"maxMlShare":0}',
  '["Candidate only. FinLab benchmark is research-only, not a promotion gate override.","Runtime matching is fail-closed until stockTechS04Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s05_first_dry_pullback_v1',
  'strategy-spec-v1',
  'S5 first dry pullback',
  'candidate',
  'strategy',
  'trend_following',
  'TREND_RECLAIM_CONTINUATION',
  's05_first_dry_pullback_v1',
  'strategy',
  'candidate',
  '["bull","sideways"]',
  'First dry pullback after strong breakout challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS05Score","op":">=","value":1}]},"technicalStrategy":{"id":"S5","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS05Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_price_structure","raw_volume","event_state:first_breakout_pullback","materialized_score:stockTechS05Score"],"maxMlShare":0}',
  '["Candidate only. Requires event-state validation before paper-active.","Runtime matching is fail-closed until stockTechS05Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s06_nr7_inside_bar_breakout_v1',
  'strategy-spec-v1',
  'S6 NR7 inside bar breakout',
  'candidate',
  'strategy',
  'breakout_vol_expansion',
  'VOLATILITY_CONTRACTION_BREAKOUT',
  's06_nr7_inside_bar_breakout_v1',
  'strategy',
  'candidate',
  '["bull","volatile"]',
  'NR7 inside bar breakout challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS06Score","op":">=","value":1}]},"technicalStrategy":{"id":"S6","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS06Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_price_structure","raw_volume","materialized_score:stockTechS06Score"],"maxMlShare":0}',
  '["Candidate only. Needs slippage review because signals are breakout-at-open sensitive.","Runtime matching is fail-closed until stockTechS06Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s07_2b_false_break_reversal_v1',
  'strategy-spec-v1',
  'S7 2B false break reversal',
  'candidate',
  'strategy',
  'mean_reversion',
  'TREND_RECLAIM_CONTINUATION',
  's07_2b_false_break_reversal_v1',
  'strategy',
  'candidate',
  '["bull","sideways","volatile"]',
  '2B false breakdown reclaim challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS07Score","op":">=","value":1}]},"technicalStrategy":{"id":"S7","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS07Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_reversion","raw_price_structure","materialized_score:stockTechS07Score"],"maxMlShare":0}',
  '["Candidate only. Needs event-level MAE/MFE review before paper-active.","Runtime matching is fail-closed until stockTechS07Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s08_rsi2_bull_mean_reversion_v1',
  'strategy-spec-v1',
  'S8 RSI2 bull mean reversion',
  'candidate',
  'strategy',
  'mean_reversion',
  'TREND_RECLAIM_CONTINUATION',
  's08_rsi2_bull_mean_reversion_v1',
  'strategy',
  'candidate',
  '["bull","sideways"]',
  'RSI2 long-trend mean reversion challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS08Score","op":">=","value":1}]},"technicalStrategy":{"id":"S8","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS08Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_reversion","raw_trend_filter","materialized_score:stockTechS08Score"],"maxMlShare":0}',
  '["Candidate only. RSI2 thresholds must be tested as fixed variants, not post-hoc tuned.","Runtime matching is fail-closed until stockTechS08Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s09_three_soldiers_base_breakout_v1',
  'strategy-spec-v1',
  'S9 three soldiers base breakout',
  'candidate',
  'strategy',
  'breakout_vol_expansion',
  'VOLATILITY_CONTRACTION_BREAKOUT',
  's09_three_soldiers_base_breakout_v1',
  'strategy',
  'candidate',
  '["bull","sideways"]',
  'Three soldiers plus base breakout challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS09Score","op":">=","value":1}]},"technicalStrategy":{"id":"S9","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS09Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_price_pattern","raw_volume","materialized_score:stockTechS09Score"],"maxMlShare":0}',
  '["Candidate only. Pattern sample count and industry concentration must be reviewed.","Runtime matching is fail-closed until stockTechS09Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s10_island_reversal_v1',
  'strategy-spec-v1',
  'S10 island reversal',
  'candidate',
  'strategy',
  'mean_reversion',
  'VOLATILITY_CONTRACTION_BREAKOUT',
  's10_island_reversal_v1',
  'strategy',
  'candidate',
  '["sideways","volatile"]',
  'Island reversal challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS10Score","op":">=","value":1}]},"technicalStrategy":{"id":"S10","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS10Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_gap_pattern","raw_reversion","materialized_score:stockTechS10Score"],"maxMlShare":0}',
  '["Candidate only. Low sample count is expected; year/industry concentration must be reported.","Runtime matching is fail-closed until stockTechS10Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s11_gap_breakout_continuation_v1',
  'strategy-spec-v1',
  'S11 gap breakout continuation',
  'candidate',
  'strategy',
  'breakout_vol_expansion',
  'VOLATILITY_CONTRACTION_BREAKOUT',
  's11_gap_breakout_continuation_v1',
  'strategy',
  'candidate',
  '["bull","volatile"]',
  'Daily gap breakout continuation challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS11Score","op":">=","value":1}]},"technicalStrategy":{"id":"S11","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresMaterializedScore":"technicalIndicators.stockTechS11Score"}}',
  '{"poolQuota":10,"costBudget":12,"evidenceRequirements":["technical_strategy12","finlab_backtest","raw_gap_pattern","raw_volume","materialized_score:stockTechS11Score"],"maxMlShare":0}',
  '["Candidate only. Gap execution requires open/slippage validation before paper-active.","Runtime matching is fail-closed until stockTechS11Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'stock_tech_s12_multitimeframe_smc_reclaim_v1',
  'strategy-spec-v1',
  'S12 multi-timeframe SMC reclaim',
  'candidate',
  'strategy',
  'breakout_vol_expansion',
  'SMC_STRUCTURE_RECLAIM',
  's12_multitimeframe_smc_reclaim_v1',
  'strategy',
  'candidate',
  '["bull","bear","sideways","volatile"]',
  'Multi-timeframe 4H/1H/15M SMC reclaim challenger from 2026-06-25 technical StrategySpec batch.',
  '{"minPrice":10,"dsl":{"all":[{"signal":"technicalIndicators.stockTechS12Score","op":">=","value":1}]},"technicalStrategy":{"id":"S12","sourceSpec":"C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","requiresIntradayBars":["15m","1h","4h"],"requiresMaterializedScore":"technicalIndicators.stockTechS12Score"}}',
  '{"poolQuota":5,"costBudget":8,"evidenceRequirements":["technical_strategy12","intraday_15m_1h_4h","event_state:zone_sweep_choch_bos_retest","materialized_score:stockTechS12Score"],"maxMlShare":0}',
  '["Candidate only. Daily OHLCV is not a valid proxy; requires completed 15m/1h/4h bars and event-state replay.","Runtime matching is fail-closed until stockTechS12Score is materialized into raw_signals."]',
  '["user_spec:C:/Users/Wei/Downloads/stock_technical_strategies_12_complete_spec.md","finlab_runner:tools/finlab_technical_strategy12_backtest.py","registry_seed:20260625"]',
  'p5_strategy_governance',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT(strategy_id, version) DO UPDATE SET
  name=excluded.name,
  status=excluded.status,
  owner=excluded.owner,
  alpha_bucket=excluded.alpha_bucket,
  family_id=excluded.family_id,
  variant_id=excluded.variant_id,
  owner_type=excluded.owner_type,
  promotion_status=excluded.promotion_status,
  supported_regimes_json=excluded.supported_regimes_json,
  thesis=excluded.thesis,
  thresholds_json=excluded.thresholds_json,
  candidate_policy_json=excluded.candidate_policy_json,
  risk_notes_json=excluded.risk_notes_json,
  source_refs_json=excluded.source_refs_json,
  created_by=excluded.created_by,
  updated_at=CURRENT_TIMESTAMP;
