/* Local UI smoke test. Auth/NAV reads are explicit fixtures; research accounts are real frozen evidence. */
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')

async function main() {
  const output = path.resolve('audits/native-model-comparison-20260920/candidate-comparison-page')
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE } : {}) })
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, deviceScaleFactor: 1 })
    const errors = [], writes = []
    page.on('pageerror', error => errors.push(String(error)))
    await page.route('**/*', async route => {
      const request = route.request(), url = new URL(request.url())
      if (url.hostname !== '127.0.0.1') return route.abort()
      if (!url.pathname.startsWith('/api/')) return route.continue()
      if (request.method() !== 'GET') writes.push(request.method() + ' ' + url.pathname)
      if (url.pathname === '/api/auth/me') return route.fulfill({ json: { email: 'local-ui-test@example.invalid', role: 'admin', is_primary_admin: true } })
      if (url.pathname === '/api/dashboard/v4/nav/comparisons') return route.fulfill({ json: { status: 'not_started', pairs: [], allocation_context_dates: 0, blockers: [] } })
      return route.fulfill({ status: 503, json: { error: 'Unmocked local read' } })
    })
    await page.goto('http://127.0.0.1:5176/bot?tab=nav')
    await page.getByRole('heading', { name: '主候選 vs 第一挑戰', exact: true }).waitFor()
    const comparison = page.getByRole('region', { name: '主候選與第一挑戰比較', exact: true })
    assert.match(await comparison.innerText(), /研究回放 · 固定快照/)
    assert.match(await comparison.innerText(), /19\.27%/)
    assert.match(await comparison.innerText(), /14\.99%/)
    assert.match(await comparison.innerText(), /19\.50%/)
    assert.match(await comparison.innerText(), /15\.58%/)
    const toggle = page.getByRole('checkbox', { name: '曲線含預估月退' })
    assert.equal(await toggle.isChecked(), true)
    await toggle.uncheck()
    assert.equal(await toggle.isChecked(), false)
    await toggle.check()
    const selector = page.getByRole('combobox', { name: '研究比較情境' })
    assert.equal(await selector.locator('option').count(), 10)
    await selector.selectOption('2026-08-05_5')
    assert.match(await comparison.innerText(), /7,191\.00/)
    assert.match(await comparison.innerText(), /18,218\.00/)
    assert.match(await comparison.innerText(), /5,324\.50/)
    assert.match(await comparison.innerText(), /13,557\.50/)
    assert.match(await comparison.innerText(), /17\.03%/)
    assert.match(await comparison.innerText(), /21\.44%/)
    assert.match(await comparison.innerText(), /2026-09-10/)
    assert.match(await comparison.innerText(), /2026-10-10/)
    await page.screenshot({ path: path.join(output, 'desktop.png'), fullPage: true })
    await selector.selectOption('2026-09-02_30')
    assert.match(await comparison.innerText(), /16\.89%/)
    await page.getByText('兩邊完整成交紀錄與資料來源', { exact: true }).click()
    assert.match(await comparison.innerText(), /SHA-256/)
    await page.getByText('兩邊完整成交紀錄與資料來源', { exact: true }).click()
    await selector.selectOption('2026-09-02_5')
    await page.setViewportSize({ width: 390, height: 844 })
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: path.join(output, 'mobile.png'), fullPage: true })
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
    assert.equal(overflow, false, 'Mobile page must not overflow horizontally')
    assert.deepEqual(errors, [])
    assert.deepEqual(writes, [])
    fs.writeFileSync(path.join(output, 'browser-check.json'), JSON.stringify({ passed: true, desktop: '1440x1080', mobile: '390x844', scenarios: 10, writes, errors, auth_nav_fixture: true, research_data_mocked: false }, null, 2))
    console.log('Browser comparison checks passed; real research evidence, mocked local auth and empty prospective NAV.')
  } finally { await browser.close() }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
