import { readFileSync } from 'node:fs'

function assert(condition: unknown, message: string): void {
  if (!condition) throw new Error(message)
}

const page = readFileSync('src/pages/BotDashboard.tsx', 'utf8')

assert(page.includes('Exit Review'), 'BotDashboard positions table should expose an Exit Review column')
assert(page.includes('p.exit_review'), 'BotDashboard positions table should read exit_review from /paper/positions')
assert(page.includes('baseline_counterfactual'), 'BotDashboard should display the baseline counterfactual action')
assert(page.includes('Exit Learning'), 'BotDashboard should expose adaptive exit learning state near positions')
assert(page.includes('paperApi.exitLearning'), 'BotDashboard should fetch /paper/exit-learning for adaptive learning visibility')
assert(page.includes('moving_tp_target'), 'BotDashboard should display moving TP target evidence when present')
assert(page.includes('paperApi.exitOutcomes'), 'BotDashboard should fetch /paper/exit-outcomes for baseline-vs-active analytics')
assert(page.includes('avg reward'), 'BotDashboard should display average active exit reward')
assert(page.includes('Exit Outcome Analytics'), 'BotDashboard should display baseline-vs-active outcome detail analytics')
assert(page.includes('avg vs base'), 'BotDashboard should display active-vs-baseline return delta')
assert(page.includes('cf samples'), 'BotDashboard should display counterfactual reward sample coverage')
assert(page.includes('cf score'), 'BotDashboard should display average counterfactual reward score')
assert(page.includes('avg Q'), 'BotDashboard should display average feature-quality coverage')
assert(page.includes('flow Q'), 'BotDashboard should display average flow-evidence coverage')
assert(page.includes('low Q'), 'BotDashboard should display low-quality outcome count')
assert(page.includes('eligible'), 'BotDashboard should display adaptive-learning eligible outcome count')
assert(page.includes('skipped'), 'BotDashboard should display observed-but-not-learned outcome count')
assert(page.includes('audit skips'), 'BotDashboard should display skipped holding-exit outcome audit count')
assert(page.includes('avg share'), 'BotDashboard should display average sold share ratio')
assert(page.includes('avg impact'), 'BotDashboard should display average adaptive learning impact weight')
assert(page.includes('by reward basis'), 'BotDashboard should group outcome analytics by learning reward basis')
assert(page.includes('by source'), 'BotDashboard should group outcome analytics by final decision source')
assert(page.includes('by skip reason'), 'BotDashboard should group skipped outcome audits by skip reason')
assert(page.includes('recent skips'), 'BotDashboard should display recent skipped outcome audits')
assert(page.includes('recent outcomes'), 'BotDashboard should display recent exit outcome lineage rows')
assert(page.includes('basis'), 'BotDashboard should display each recent outcome reward basis')
assert(page.includes('source'), 'BotDashboard should display each recent outcome final decision source')
assert(page.includes('impact'), 'BotDashboard should display each recent outcome adaptive learning impact weight')
assert(page.includes('base px'), 'BotDashboard should display each recent outcome baseline exit price')
assert(page.includes('missing Q'), 'BotDashboard should display recent outcome missing quality factors')
assert(page.includes('by active action'), 'BotDashboard should group outcome analytics by active exit action')
assert(page.includes('by regime'), 'BotDashboard should group outcome analytics by market regime')
assert(page.includes('changed vs baseline'), 'BotDashboard should show changed-vs-baseline outcome comparison')
assert(page.includes('Exit Adaptive State'), 'BotDashboard should display learned adaptive exit state')
assert(page.includes('factor utility'), 'BotDashboard should expose factor utility learned from outcomes')
assert(page.includes('learned weights'), 'BotDashboard should expose learned exit factor weights')
assert(page.includes('active knobs'), 'BotDashboard should expose current adaptive thresholds and TP/trail knobs')
assert(page.includes('featureQuality'), 'BotDashboard should read feature-quality coverage from exit_review features')
assert(page.includes('missingFeatures'), 'BotDashboard should display missing holding-exit factor groups')
assert(page.includes('factorScale'), 'BotDashboard should read adaptive factor scale from exit_review features')
assert(page.includes('B-scale'), 'BotDashboard should expose broker-flow adaptive scale in Exit Review')
assert(page.includes('M-scale'), 'BotDashboard should expose money-flow adaptive OBV threshold in Exit Review')
assert(page.includes('S-scale'), 'BotDashboard should expose structure adaptive scale in Exit Review')
assert(page.includes('G-scale'), 'BotDashboard should expose giveback adaptive scale in Exit Review')
assert(page.includes('actionGates'), 'BotDashboard should read learned action gates from exit learning params')
assert(page.includes('full gate'), 'BotDashboard should expose adaptive full-exit gate in active knobs')
assert(page.includes('TP2 risk'), 'BotDashboard should expose adaptive moving-TP2 risk guard')
assert(page.includes('TP2 conf'), 'BotDashboard should expose adaptive moving-TP2 confidence guard')
assert(page.includes('TP2 ext'), 'BotDashboard should expose adaptive moving-TP2 extension guard')
assert(page.includes('sell conf'), 'BotDashboard should expose adaptive guarded-sell confidence')
assert(page.includes('Q move'), 'BotDashboard should expose moving-TP2 feature-quality guard')
assert(page.includes('Q sell'), 'BotDashboard should expose guarded-sell feature-quality guard')
assert(page.includes('Q move flow'), 'BotDashboard should expose moving-TP2 flow-evidence guard')
assert(page.includes('Q sell flow'), 'BotDashboard should expose guarded-sell flow-evidence guard')
