import fs from 'node:fs'
import path from 'node:path'
import assert from 'node:assert/strict'

const root = process.cwd()
const appPath = path.join(root, 'src', 'App.tsx')
const pagePath = path.join(root, 'src', 'pages', 'StrategyLearningPage.tsx')

assert(fs.existsSync(pagePath), 'Strategy Lab should have a dedicated Learning + Reward Ledger page')

const app = fs.readFileSync(appPath, 'utf8')
const page = fs.readFileSync(pagePath, 'utf8')

assert(app.includes("import('./pages/StrategyLearningPage')"), '/strategy-lab should route to the focused learning page')
assert(page.includes('策略學習與報酬帳本'), 'Strategy Lab should expose the production learning and reward-ledger mission')
assert(page.includes('StrategyHealthBoard'), 'Strategy Lab should expose an always-visible strategy health board')
assert(page.includes('StrategyLineageInspector'), 'Strategy Lab should expose a production lineage inspector')
assert(page.includes('STRATEGY_HEALTH_SECTIONS') && page.includes('group.rows.length'), 'Health board must group strategies and show a count for every canonical health bucket')
assert(page.includes('STRATEGY_LIFECYCLE_LANES') && page.includes("key: 'active'") && page.includes("key: 'candidate'"), 'Health board must split Active from Candidate before applying health buckets')
assert(page.includes('strategyLifecycleLane(row) === lane.key') && page.includes('xl:grid-cols-2'), 'Active and Candidate lanes must stay in visible left/right columns')
assert(page.includes('沒有額外的 Shadow 策略 stage'), 'Candidate must be the evidence accumulation lifecycle state')
assert(page.includes('rows={orderedRows}'), 'Health board must render every non-retired strategy without a hidden filter')
assert(!page.includes('StrategyViewFilter') && !page.includes('queueRows'), 'The old filtered queue must not hide strategy rows')
assert(page.includes("row.status !== 'retired'"), 'Retired strategies should stay outside the workspace')
assert(page.includes('rows={[selectedRow]}'), 'The evidence workspace must render one selected strategy instead of every card at once')
assert(page.includes('xl:grid-cols-[minmax(0,10fr)_minmax(0,7fr)_minmax(0,3fr)]'), 'Desktop workspace, stage transition, and lineage inspector must use the requested 5:3.5:1.5 ratio')
assert(page.includes('共用 hard gate 只管資料可比性與成熟度'), 'Stage transition must disclose the common maturity-only gate role')
assert(page.includes('不代表每天或每筆交易都不會出現負報酬'), 'LCB90 copy must describe an average-confidence statistic rather than impossible loss prevention')
assert(page.includes('不是單一股票一天的漲跌幅'), 'MDD copy must distinguish the date-portfolio alpha curve from a single-stock daily limit move')
assert(page.includes('Atomic V7 相對替換'), 'Candidate activation must expose the practical paired replacement gate')
assert(page.indexOf('<StrategyStageTransitionCard') < page.indexOf('<StrategyLineageInspector'), 'Stage transition must sit between the strategy workspace and lineage inspector')
assert(page.indexOf('policyWeight == null') > page.indexOf('missing.length ? missing'), 'Pending-buy relative weight must follow the current gate result in the inspector')
assert(page.includes('className="grid grid-cols-1 gap-px bg-slate-900"'), 'A single selected strategy must fill the complete ledger workspace')
assert(page.includes('aria-pressed={selected}') && page.includes('focus-visible:ring-2'), 'Strategy selectors must expose selection state and keyboard focus')
assert(!page.includes('正式策略健康分流詳情'), 'Strategy health routing must stay visible without a disclosure arrow')
assert(!page.includes('xl:grid-cols-2 xl:items-start'), 'The old all-strategies two-column wall must not return')
assert(page.includes('row.learning.today_matched'), 'strategy cards must expose daily matched count instead of forcing users to infer it from reward or policy fields')
assert(page.includes('strategyLabApi.learning()'), 'The focused page should load the canonical reward ledger response')
assert(page.includes('Promise.allSettled') && page.includes('strategyLabApi.specs()') && page.includes('strategyLabApi.evidenceProfiles()'), 'Strategy Lab must load all three production read models without making one failure erase the others')
assert(page.includes('registryLearningRow'), 'Strategy Lab must keep registry rows visible when the reward-ledger endpoint is unavailable')
assert(!page.includes("reason.includes('missing')"), 'Strategy health routing must not treat every metric name containing missing as a broken data pipeline')
assert(page.includes("row.learning.reward_state === 'no_matches'") && page.includes("row.learning.reward_state === 'reward_join_missing'"), 'No-match accumulation and true reward-join repair must remain distinct')
assert(page.includes('gate.strategy_id') && page.includes('profile.strategy_id') && page.includes('strategy_version'), 'All joins must preserve exact id:version identity')
assert(!page.includes('StrategyLifecycleSwimlane'), 'The focused page should not repeat lifecycle experiment navigation')
assert(!page.includes('MetaLearningDecisionDesk'), 'The focused page should not repeat meta-learning experiment controls')
assert(!page.includes('ModelUpgradeLaunchpad'), 'Model research controls belong in Model Pool, not the reward ledger page')
assert(!page.includes('Pre-trade Spec + Dry-run'), 'Strategy Lab should not repeat pre-trade spec/dry-run UI')
assert(page.includes('policy?.evidence.production_effect'), 'Adaptive policy must display its canonical production-effect state')
assert(page.includes('currentDecisionPending'), 'Strategy cards must distinguish a not-yet-produced day from a real 0/0/0 decision batch')
assert(page.includes('StrategyGateDetails'), 'Selected strategy must retain its own readiness thresholds and evidence')
assert(page.includes('replacement_gate'), 'Strategy cards must consume canonical replacement evidence from the API')
assert(page.includes('AtomicReplacementSummary'), 'Cross-family replacement must remain available once in governance details')
assert(page.includes('materializeDecisionLog') && page.includes('refreshStrategyRewardLedger') && page.includes('refreshStrategyPolicyState'), 'Operational actions must survive the readability refactor')

console.log('strategyLabNewFlowContract: OK')
