import fs from 'node:fs'
import path from 'node:path'
import assert from 'node:assert/strict'

const root = process.cwd()
const appPath = path.join(root, 'src', 'App.tsx')
const routeModulesPath = path.join(root, 'src', 'lib', 'routeModules.ts')
const pagePath = path.join(root, 'src', 'pages', 'StrategyLearningPage.tsx')
const apiPath = path.join(root, 'src', 'lib', 'api.ts')

assert(fs.existsSync(pagePath), 'Strategy Lab should have a dedicated Learning + Reward Ledger page')

const app = fs.readFileSync(appPath, 'utf8')
const routeModules = fs.readFileSync(routeModulesPath, 'utf8')
const page = fs.readFileSync(pagePath, 'utf8')
const api = fs.readFileSync(apiPath, 'utf8')

assert(routeModules.includes("strategyLab: () => import('@/pages/StrategyLearningPage')"), '/strategy-lab should load the focused learning page')
assert(app.includes('const StrategyLabPage = lazy(loadStrategyLabPage)'), '/strategy-lab should remain lazy loaded')
assert(page.includes('策略學習與報酬帳本'), 'Strategy Lab should expose the production learning and reward-ledger mission')
assert(page.includes('StrategyHealthBoard'), 'Strategy Lab should expose an always-visible strategy health board')
assert(page.includes('StrategyLineageInspector'), 'Strategy Lab should expose a production lineage inspector')
assert(page.includes('ACTIVE_STRATEGY_HEALTH_SECTIONS') && page.includes('CANDIDATE_STRATEGY_HEALTH_SECTIONS') && page.includes('group.rows.length'), 'Health board must use lane-specific buckets and show each count')
assert(page.includes('STRATEGY_LIFECYCLE_LANES') && page.includes("key: 'active'") && page.includes("key: 'candidate'"), 'Health board must split Active from Candidate before applying health buckets')
const activeSections = page.slice(page.indexOf('const ACTIVE_STRATEGY_HEALTH_SECTIONS'), page.indexOf('const CANDIDATE_STRATEGY_HEALTH_SECTIONS'))
const candidateSections = page.slice(page.indexOf('const CANDIDATE_STRATEGY_HEALTH_SECTIONS'), page.indexOf('const STRATEGY_HEALTH_SECTIONS_BY_LANE'))
assert(activeSections.includes("key: 'performance_cooldown'") && activeSections.includes('連續兩次 OOS promoted primary-horizon 分數為負') && activeSections.includes('diversity sleeve') && !activeSections.includes("key: 'promotion_pending'"), 'Active cooldown must be owned by consecutive promoted primary-horizon evidence and never show promotion pending')
assert(candidateSections.includes("key: 'promotion_pending'") && !candidateSections.includes("key: 'performance_cooldown'"), 'Only Candidate may expose promotion pending')
assert(candidateSections.includes("key: 'prefilter_failed'") && page.includes("String(gate.activation_gate.status) === 'prefilter_failed'"), 'Candidate prefilter failure must have its own bucket instead of promotion pending')
assert(candidateSections.includes("key: 'atomic_not_applicable'") && page.includes("String(gate.activation_gate.status) === 'not_applicable'"), 'Non-selection Candidate owners must have an explicit Atomic-not-applicable bucket')
assert(page.includes('strategyLifecycleLane(row) === lane.key') && page.includes('xl:grid-cols-2'), 'Active and Candidate lanes must stay in visible left/right columns')
assert(page.includes('沒有額外的 Shadow 策略 stage'), 'Candidate must be the evidence accumulation lifecycle state')
assert(page.includes('rows={orderedRows}'), 'Health board must render every non-retired strategy without a hidden filter')
assert(!page.includes('StrategyViewFilter') && !page.includes('queueRows'), 'The old filtered queue must not hide strategy rows')
assert(page.includes("row.status !== 'retired'"), 'Retired strategies should stay outside the workspace')
assert(page.includes('rows={[selectedRow]}'), 'The evidence workspace must render one selected strategy instead of every card at once')
assert(page.includes('xl:grid-cols-[minmax(0,10fr)_minmax(0,7fr)_minmax(0,3fr)]'), 'Desktop workspace, stage transition, and lineage inspector must use the requested 5:3.5:1.5 ratio')
assert(page.includes('共用 hard gate 只管 Candidate 的資料可比性與成熟度') && page.includes('Active 不再用共用勝率或 MDD hard gate'), 'Stage transition must separate Candidate maturity gates from Active per-strategy cooldown evidence')
assert(page.includes('primary-horizon OOS promoted calibration') && page.includes('連續兩個不同 knowledge cutoff 負分才降溫') && page.includes('連續兩個正分才恢復'), 'Active cooldown copy must describe the formal promoted-owner hysteresis')
assert(!page.includes('v3 依每個策略自己的成熟報酬、成熟日期與 rolling date-return 分配 contribution'), 'Retired rolling date-return contribution copy must not return')
assert(page.includes('sv-readable-card-content rounded-2xl') && page.includes('<h2 className="truncate text-[15px] font-bold text-slate-100">Stage transition</h2>'), 'Stage transition must use the homepage 15px bold title role and readable body typography')
assert(page.includes('共用成熟度門檻') && page.includes('觀察指標（不判定通過／失敗）'), 'Hard gates and diagnostics must render as separate semantic groups')
assert(page.includes('Active 權重輸入 · 非門檻') && page.includes('僅供診斷 · 非門檻'), 'Diagnostic values must state their non-gating role')
assert(!page.includes("if (pass == null) return '待累積'") && !page.includes('不設共用 hard gate'), 'Diagnostic metrics must not inherit a pending gate label')
assert(page.includes('不代表每天或每筆交易都不會出現負報酬'), 'LCB90 copy must describe an average-confidence statistic rather than impossible loss prevention')
assert(page.includes('不是單一股票一天的漲跌幅'), 'MDD copy must distinguish the date-portfolio alpha curve from a single-stock daily limit move')
assert(page.includes('Atomic V7 相對替換'), 'Candidate activation must expose the practical paired replacement gate')
assert(page.indexOf('<StrategyStageTransitionCard') < page.indexOf('<StrategyLineageInspector'), 'Stage transition must sit between the strategy workspace and lineage inspector')
assert(page.indexOf('formalPolicyWeight == null') > page.indexOf('missing.length ? missing'), 'Formal pending-buy contribution must follow the current gate result in the inspector')
assert(page.includes('className="grid grid-cols-1 gap-px bg-slate-900"'), 'A single selected strategy must fill the complete ledger workspace')
assert(page.includes('aria-pressed={selected}') && page.includes('focus-visible:ring-2'), 'Strategy selectors must expose selection state and keyboard focus')
assert(!page.includes('正式策略健康分流詳情'), 'Strategy health routing must stay visible without a disclosure arrow')
assert(!page.includes('xl:grid-cols-2 xl:items-start'), 'The old all-strategies two-column wall must not return')
assert(page.includes('row.learning.today_matched'), 'strategy cards must expose daily matched count instead of forcing users to infer it from reward or policy fields')
assert(page.includes('strategyLabApi.learning()'), 'The focused page should load the canonical reward ledger response')
assert(page.includes('Promise.allSettled') && page.includes('strategyLabApi.specs()') && page.includes('strategyLabApi.evidenceProfiles()'), 'Strategy Lab must load all three production read models without making one failure erase the others')
assert(page.includes('registryLearningRow'), 'Strategy Lab must keep registry rows visible when the reward-ledger endpoint is unavailable')
assert(!page.includes("reason.includes('missing')"), 'Strategy health routing must not treat every metric name containing missing as a broken data pipeline')
assert(page.includes("row.learning.reward_state === 'no_matches'") && page.includes("row.learning.reward_state === 'reward_join_missing'"), 'No-match accumulation and true reward-join repair must remain distinct')
assert(page.includes('gate.strategy_id') && page.includes('profile.strategy_id') && page.includes('strategy_version'), 'All joins must preserve exact id:version identity')
assert(!page.includes('StrategyLifecycleSwimlane'), 'The focused page should not repeat lifecycle experiment navigation')
assert(!page.includes('MetaLearningDecisionDesk'), 'The focused page should not repeat meta-learning experiment controls')
assert(!page.includes('ModelUpgradeLaunchpad'), 'Model research controls belong in Model Pool, not the reward ledger page')
assert(!page.includes('Pre-trade Spec + Dry-run'), 'Strategy Lab should not repeat pre-trade spec/dry-run UI')
assert(page.includes('previewPolicy?.evidence.production_effect') && page.includes('不是 formal production policy'), 'Adaptive preview must be labeled diagnostic and must not impersonate formal policy')
assert(page.includes('currentDecisionPending'), 'Strategy cards must distinguish a not-yet-produced day from a real 0/0/0 decision batch')
assert(page.includes('StrategyGateDetails'), 'Selected strategy must retain its own readiness thresholds and evidence')
assert(page.includes('replacement_gate'), 'Strategy cards must consume canonical replacement evidence from the API')
assert(page.includes('CandidateAtomicV7Dialog') && page.includes('<Dialog open={open}') && page.includes('Atomic V7 全門檻'), 'Candidate Atomic V7 evidence must open in a modal')
assert(page.includes('onClick={() => onSelect(key)}') && !page.includes("if (lane.key === 'candidate') onOpenAtomicV7(key)"), 'Clicking an upper Candidate card must only select the strategy')
assert(page.includes('<StrategyStageTransitionCard') && page.includes('aria-label="Atomic V7 相對替換指標"') && page.includes('查看全門檻') && page.includes("if (selectedRow?.status === 'candidate') setAtomicV7StrategyKey"), 'The lower Stage transition Atomic V7 indicator button must own modal opening')
assert(page.includes("sm:max-w-[96vw] xl:max-w-[1500px]") && page.includes("grid-rows-[auto_auto_auto_minmax(0,1fr)]") && page.includes("phase === 'prefilter'") && page.includes("phase === 'pair'") && page.includes("phase === 'cutover'"), 'Atomic V7 modal must be wide and split into three navigable phases instead of one narrow scrolling document')
assert(page.includes('prefilter.strategy_id === row.id') && page.includes('prefilter.strategy_version === row.version') && page.includes('decision.candidate_strategy_id === row.id') && page.includes('decision.candidate_strategy_version === row.version'), 'Atomic modal must preserve exact Candidate id:version identity for prefilter and pair decisions')
assert(page.includes('A. Candidate prefilter actual / target / pass') && page.includes('B. Candidate vs Active pair actual / target / pass') && page.includes('C. 最終 cutover firewall actual / target / pass'), 'Candidate modal must expose all V7 phases with actual, target, and pass')
assert(page.includes('notEvaluatedPairMetrics') && page.includes("value: '未評估'") && page.includes('尚無判定') && page.includes('不等於未通過'), 'Unexecuted pair gates must still list every target and remain explicitly not evaluated')
assert(page.includes('notEvaluatedCutoverMetrics') && page.includes('candidateCutoverEvaluated') && page.includes('不拿其他 Candidate 的 run-level portfolio actual 冒充'), 'Final cutover gates must remain Candidate-specific and fail closed when the run has no promotion identity for this Candidate')
assert(page.includes('目前沒有此 Candidate 的 prefilter evidence') && page.includes('三道 target 仍完整保留'), 'Candidate modal must keep every prefilter target visible even when actual evidence is missing')
assert(!page.includes('AtomicReplacementSummary') && !page.includes('共享 Portfolio Firewall') && !page.includes('Atomic V7 完整門檻總表（固定顯示）'), 'The standalone shared Portfolio block must be deleted')
const healthBucket = page.slice(page.indexOf('function strategyHealthBucket'), page.indexOf('function strategyHealthLabel'))
assert(healthBucket.indexOf("strategyLifecycleLane(row) === 'active'") < healthBucket.indexOf("row.learning.reward_state === 'pending_maturity'"), 'Active formal contribution routing must run before generic evidence accumulation')
assert(healthBucket.includes("ownerDecision?.performance_state === 'cooldown'") && healthBucket.includes("return 'performance_cooldown'"), 'Active performance cooldown must come from the persisted formal owner decision')
assert(healthBucket.includes("return gate.missing_evidence.length > 0") && healthBucket.includes("? 'accumulating' : 'evidence_repair'"), 'Readiness deficits must not be mislabeled as performance cooldown')
assert(healthBucket.includes("return 'formal_policy_pending'") && !healthBucket.includes("if (formalWeight == null) return 'evidence_repair'"), 'A missing or zero formal weight after data gates pass must be policy-pending rather than data repair')
assert(page.includes('gate?.allocation_eligible === true && formalPolicyWeight != null && formalPolicyWeight > 0'), 'Pending-buy health requires both the allocation gate and a positive formal weight')
assert(page.includes('formal_policy_lineage') && page.includes('formalPolicyWeights') && page.includes("formalPolicy ? executionEligibleCount : '-'"), 'Formal lineage must own weight display and execution-eligible counts, failing closed when unavailable')
assert(page.includes('const formalPolicy = strategyLanes?.formal.production_effect === true') && page.includes('const formalPolicy = lanes?.formal.production_effect === true'), 'Formal weights and inspector must require both production effect and formal lineage')
assert(api.includes('owner_strategy_decisions') && api.includes('performance_reason') && page.includes('formalPolicy.base_policy_version === formalBasePolicyVersion') && page.includes('formalPolicy.base_policy_as_of_date === formalBasePolicyAsOfDate'), 'Cooldown reasons must come from the exact persisted formal owner policy lineage')
assert(page.includes('formalOwnerDecisions[row.id]') && page.includes('正式 policy 降溫原因') && page.includes('為什麼被排入績效降溫') && page.includes('formalCooldownReasons.map'), 'Active cooldown cards and inspector must expose every persisted formal owner reason')
assert(page.includes('為什麼正式 contribution 尚未大於 0') && page.includes('不代表 reward、PIT 或 decision 資料損壞') && !page.includes('formalCooldown || formalContributionZero'), 'Zero contribution must have a policy/firewall explanation and must not render the cooldown panel')
assert(page.includes('production_firewall_allocation_gate_blocked_reason_not_archived') && page.includes('formalQuarantinedStrategyIds.includes(row.id)'), 'A quarantined Active without adaptive failure reasons must disclose the production firewall layer and archival limitation')
assert(page.includes('不拿 preview 原因冒充正式降溫原因'), 'Formal cooldown reasons must fail closed on lineage mismatch')
assert(page.includes('正式 contribution') && page.includes('Preview weight（診斷）'), 'Formal and preview weights must be visibly separate')
assert(page.includes('activationGateStatusLabel') && page.includes("return 'not-evaluated'") && page.includes('activationGatePass'), 'Activation state must preserve proposed/rejected/accepted and expose no evaluation explicitly')
assert(!page.includes("status === 'pending'") && page.includes("status === 'prefilter_failed'") && page.includes("status === 'not_evaluated'"), 'Activation helpers must use explicit evidence/prefilter/evaluation states and reject generic pending')
const activationGateType = api.slice(api.indexOf('activation_gate:'), api.indexOf('missing_evidence:', api.indexOf('activation_gate:')))
assert(!activationGateType.includes("| 'pending'") && activationGateType.includes("'evidence_pending'") && activationGateType.includes("'prefilter_failed'") && activationGateType.includes("'not_evaluated'"), 'Activation API union must not expose generic pending')
assert(page.includes('Pair verdict：not-evaluated') && !page.includes("value: gate.activation_gate.status === 'accepted' ? 'accepted' : 'pending'"), 'Missing pairs and non-accepted decisions must not collapse into generic pending')
assert(page.includes('full_portfolio_positive_cost_net_lcb95_hac') && page.includes('full_portfolio_absolute_cost_net_lcb95_hac') && !page.includes('full_portfolio_positive_cost_net_lcb)'), 'Full-portfolio paired and absolute cost-net gates must use the distinct V7 LCB95 HAC keys')
assert(page.includes('Full portfolio MDD baseline / final') && page.includes('Full portfolio turnover baseline / final') && page.includes('Full portfolio return correlation'), 'Per-Candidate modal cutover phase must expose run-level risk actuals against targets')
assert(page.includes('Holm-accepted replacement exists') && page.includes('Atomic one-in-one-out contract') && page.includes('Full portfolio all gates'), 'Per-Candidate modal cutover phase must expose statistical, atomic-cutover, and composite verdicts')
assert(api.includes('candidate_prefilters') && page.includes('candidatePrefilters'), 'Atomic V7 must project and consume Candidate prefilter evidence')
assert(page.includes('Candidate prefilter actual / target / pass') && page.includes('prefilter-failed') && page.includes('不會誤標成 pending pair 或 failed'), 'Candidate prefilter must expose explicit pass/fail/no-evidence states')
assert(!page.includes('Active 正式 contribution 分配') && !page.includes('raw score = max(0, rolling date-return mean)'), 'The standalone Active contribution formula block must be deleted')
assert(page.includes('正式 policy 待下一輪封存') && page.includes('current-business-date authoritative evening chain'), 'Strategy Lab must explain formal policy materialization lag and its evening-chain closure condition')
assert(page.includes("!row.learning.evidence_available") && page.includes('成熟度未取得') && page.includes('0 dates · 0 samples · 無型態命中'), 'Candidate maturity must distinguish unavailable API evidence from a genuine zero-match strategy')
assert(!page.includes('單一推薦資料流：'), 'The removed single recommendation-flow copy must not return')
assert(page.includes("const evidenceReady = prefilter.evidence_status === 'ready'") && page.includes('prefilter.production_eligible === false') && page.includes('evidence-missing（持續累積）'), 'Missing Candidate prefilter evidence must remain pending/missing; only ready plus production_eligible=false may fail')
assert(!page.includes("prefilter.production_eligible ? 'prefilter-pass' : 'prefilter-failed'"), 'Nullable Candidate eligibility must not collapse missing evidence into prefilter failure')
assert(page.includes('Candidate observation dates') && page.includes('Candidate marginal-edge LCB90') && page.includes('Candidate absolute hit-return mean'), 'Candidate prefilter must render every actual against its versioned target')
assert(api.includes("'not_applicable'") && api.includes('applicability_reason') && page.includes('atomicV7InapplicabilityLabel'), 'Atomic API and modal must distinguish owner-boundary not-applicable from missing evidence')
assert(page.includes('Prefilter verdict：通過') && page.includes('未通過：{metric.label}') && page.includes('actual {metric.value}；target {metric.target}'), 'S8-style prefilter failures must expose a visible passed/failed count and each failed actual versus target')
for (const field of [
  'effective_paired_dates',
  'paired_delta_hac_standard_error',
  'paired_delta_lcb95_hac',
  'paired_delta_one_sided_p_value',
  'paired_delta_power_at_minimum_economic_delta',
  'candidate_absolute_cost_net_lcb95_hac',
  'holm_local_alpha',
  'holm_adjusted_p_value',
  'holm_rejected',
]) {
  assert(api.includes(field) && page.includes(field), 'Atomic V7 field must be typed and rendered: ' + field)
}
assert(page.includes('MDD Candidate / incumbent') && page.includes('Turnover Candidate / incumbent') && page.includes('Return correlation'), 'Pair inspector must render Candidate/incumbent risk comparisons')
assert(page.includes('actual / target / pass') && page.includes('GateMetric key={metric.label}'), 'Atomic inspector must expose actual, target, and pass for run and pair metrics')
assert(page.includes('materializeDecisionLog') && page.includes('refreshStrategyRewardLedger') && page.includes('refreshStrategyPolicyState'), 'Operational actions must survive the readability refactor')

console.log('strategyLabNewFlowContract: OK')
