import assert from 'node:assert/strict'
import fs from 'node:fs'

const page = fs.readFileSync('src/pages/StrategyLearningPage.tsx', 'utf8')
const api = fs.readFileSync('src/lib/api.ts', 'utf8')
const worker = fs.readFileSync('../worker/src/lib/strategyLearning.ts', 'utf8')
const profilesRoute = fs.readFileSync('../worker/src/routes/adminReadRoutes.ts', 'utf8')
const metrics = fs.readFileSync('../worker/src/lib/strategyEvidenceMetrics.ts', 'utf8')

assert.match(api, /allocation_eligible: boolean/)
assert.match(api, /active_retention_min_hit_rate: number \| null/)
assert.match(api, /evidenceProfiles.*strategy\/evidence-profiles/)
assert.ok(api.includes("production_authority: 'comparison_only' | 'formal_owner_input_ready' | 'formal_owner_input_active'"))
assert.match(api, /primary_horizon_shadow_available/)
assert.ok(api.includes("multi_horizon_authority: 'shadow_only' | 'formal_owner_input_ready' | 'formal_owner'"))
assert.match(worker, /min_hit_rate: null/)
assert.match(worker, /active_retention_min_hit_rate: null/)
assert.match(worker, /diagnostic_only_metrics: \['match_rate', 'hit_rate', 'avg_cost_net_alpha', 'max_drawdown', 'date_return_lcb90'\]/)
assert.match(worker, /relative_pending_buy_gate_share_not_capital_allocation/)
assert.match(api, /all_non_retired_strategies_single_evaluation_stream/)
assert.match(page, /正式參與選股的策略/)
assert.match(page, /目前可讓推薦進待買/)
assert.match(page, /不是帳戶資金、下單金額或部位比例/)
assert.match(page, /待買資格過度集中（非健康穩態）/)
assert.match(page, /單一推薦資料流/)
assert.match(page, /Candidate → Active/)
assert.match(page, /沒有 Shadow strategy stage/)
assert.match(page, /共享 Portfolio Firewall：原子替換 V7/)
assert.match(page, /gate\.allocation_eligible === true/)
assert.match(page, /待買權重 0% 仍持續學習/)
assert.match(page, /PIT（當時可知資料）/)
assert.match(page, /LCB90/)
assert.match(page, /此策略自己的 evidence 契約/)
assert.match(page, /comparison-only evidence/)
assert.match(page, /正式：Production contribution firewall/)
assert.match(page, /Threshold route comparison（原 Shadow A）/)
assert.match(page, /正式：Multi-horizon evidence（原 Shadow B）/)
assert.match(page, /正式 multi-horizon evidence input/)
assert.match(page, /已就緒，待正式 policy closure/)
assert.match(api, /formal_owner_input_active/)
assert.match(page, /有 production 權限/)
assert.match(page, /結果資料已齊，指標建置中/)
assert.match(page, /Candidate 仍會持續產生零 production-effect evidence/)
assert.match(metrics, /no_strategy_hits_in_observation_window/)
assert.match(metrics, /shadow_coverage_diagnostics_before_threshold_change/)
assert.match(page, /至少需 2 個可估計日/)
assert.match(profilesRoute, /outcomes_ready_metrics_materializing/)
assert.match(profilesRoute, /strategy_evidence_metrics_v1/)
assert.match(page, /相對基準勝率 \/ 平均 Alpha/)
assert.match(page, /樣本與成熟交易日都達標/)
assert.match(metrics, /materializeStrategyEvidenceMetrics/)
assert.match(profilesRoute, /threshold_route_shadow/)
assert.match(profilesRoute, /multi_horizon_formal/)
assert.match(profilesRoute, /STRATEGY_ROUTE_MIN_TOTAL_DATES/)
assert.match(profilesRoute, /production_effect: false/)
assert.match(profilesRoute, /formal_owner_input_active/)
assert.match(page, /StrategyHealthBoard/)
assert.match(page, /STRATEGY_LIFECYCLE_LANES/)
assert.match(page, /strategyLifecycleLane\(row\) === lane\.key/)
assert.match(page, /rows=\{orderedRows\}/)
assert.doesNotMatch(page, /StrategyViewFilter|queueRows/)
assert.match(page, /StrategyLineageInspector/)
assert.match(page, /rows=\{\[selectedRow\]\}/)
assert.match(page, /Promise\.allSettled/)
assert.match(page, /strategyLabApi\.learning\(\)/)
assert.match(page, /strategyLabApi\.specs\(\)/)
assert.match(page, /strategyLabApi\.evidenceProfiles\(\)/)
assert.match(page, /return numeric > 0 \? 'text-rose-300' : 'text-emerald-300'/)
assert.doesNotMatch(page, /latest V6 run/)

console.log('strategy learning single-stream UI contract tests passed')
