import * as fs from 'node:fs'
import * as path from 'node:path'

function assert(condition: unknown, message: string): void {
  if (!condition) throw new Error(message)
}

function read(root: string, ...parts: string[]) {
  return fs.readFileSync(path.join(root, ...parts), 'utf8')
}

const root = process.cwd()
const css = read(root, 'src', 'index.css')
const appShell = read(root, 'src', 'components', 'AppShell.tsx')
const workstation = read(root, 'src', 'components', 'workstation', 'WorkstationChrome.tsx')
const bot = read(root, 'src', 'pages', 'BotDashboard.tsx')
const home = read(root, 'src', 'pages', 'DailyFocusHomePage.tsx')
const stockReport = read(root, 'src', 'pages', 'StockReportPage.tsx')
const dashboardV4Chart = read(root, 'src', 'components', 'charts', 'DashboardV4LightweightChart.tsx')
const strategyLab = read(root, 'src', 'pages', 'StrategyLabPage.tsx')
const strategyChart = read(root, 'src', 'components', 'charts', 'StrategyExperimentTimeline.tsx')
const modelPool = read(root, 'src', 'pages', 'ModelPoolPage.tsx')
const obs = read(root, 'src', 'pages', 'ObservabilityPage.tsx')
const scheduler = read(root, 'src', 'pages', 'SchedulerPage.tsx')
const schedulerChart = read(root, 'src', 'components', 'charts', 'SchedulerCadenceChart.tsx')
const dataQuality = read(root, 'src', 'pages', 'DataQualityPage.tsx')
const dataQualityChart = read(root, 'src', 'components', 'charts', 'DataQualityTrendChart.tsx')
const pipeline = read(root, 'src', 'pages', 'PipelinePage.tsx')
const inspector = read(root, 'src', 'pages', 'ModelPoolInspectorPage.tsx')

for (const surface of ['home', 'stock', 'bot', 'strategy', 'model', 'inspector', 'pipeline', 'ops']) {
  assert(css.includes(`[data-sv-surface="${surface}"]`), `surface theme must define ${surface}`)
}

assert(appShell.includes('surfaceForPath'), 'AppShell should own route-to-surface theme mapping')
assert(appShell.includes('data-sv-surface={surface}'), 'AppShell should expose active surface as a data attribute')
assert(appShell.includes("currentPath.startsWith('/report/')"), 'Stock report route should receive a stock detail surface theme')
assert(appShell.includes("currentPath.startsWith('/bot')"), 'Bot route should receive a private trading surface theme')
assert(appShell.includes("currentPath.startsWith('/strategy-lab')"), 'Strategy Lab route should receive a research surface theme')
assert(appShell.includes("currentPath.startsWith('/model-pool/inspector')"), 'Inspector route should receive an inspector surface theme')
assert(appShell.includes("currentPath.startsWith('/model-pool')"), 'Model Pool route should receive a governance surface theme')
assert(appShell.includes("currentPath.startsWith('/obs')") && appShell.includes("currentPath.startsWith('/scheduler')") && appShell.includes("currentPath.startsWith('/data-quality')"), 'OBS and specialist drilldowns should receive an operations surface theme')

assert(workstation.includes('sv-workstation-panel'), 'WorkstationPanel should consume semantic surface CSS instead of only hard-coded colors')
assert(workstation.includes('var(--sv-accent)'), 'Workstation primitives should consume surface accent tokens')
assert(workstation.includes('var(--sv-panel-border)'), 'Workstation primitives should consume surface border tokens')
assert(css.includes('.sv-content-card'), 'Surface CSS should provide reusable content cards for page-specific sections')
assert(css.includes('.sv-content-card-selected'), 'Surface CSS should provide selected content cards for active/private targets')
assert(css.includes('.sv-login-panel'), 'Surface CSS should provide a tokenized login panel for logged-out private surfaces')
assert(css.includes('.sv-surface-chip') && css.includes('.sv-surface-chip-accent'), 'Surface CSS should provide reusable tokenized chips')
assert(home.includes('sv-content-card'), 'Home public aggregate cards should consume the active public surface theme')
assert(home.includes('sv-accent-text'), 'Home public icons should consume the active public surface accent')
assert(home.includes('var(--sv-accent-border)') && home.includes('var(--sv-accent-soft)'), 'Home refresh action should consume surface accent tokens')
assert(!home.includes('border-[#d6a85f]/30 text-[#f1c16f]'), 'Home refresh action must not keep the retired amber-only styling')
assert(stockReport.includes('AppShell') && stockReport.includes('data-testid="stock-report-signal-board"'), 'Stock report should render inside workstation shell with a visual signal board')
assert(stockReport.includes('WorkstationPageTitle') && stockReport.includes('sv-content-card') && stockReport.includes('sv-accent-text'), 'Stock report should consume the stock detail surface theme')
assert(dashboardV4Chart.includes('Dashboard V4 / Lightweight Charts') && dashboardV4Chart.includes('sv-content-card'), 'Dashboard V4 chart should consume route-level surface cards')
assert(modelPool.includes('ModelGovernanceVisualMap') && modelPool.includes('sv-content-card'), 'ModelPool governance visual map should consume the active governance surface theme')
assert(modelPool.includes('data-testid="modelpool-governance-drilldown"') && modelPool.includes('sv-disclosure'), 'ModelPool governance drilldown should consume route-level disclosure tokens')
assert(modelPool.includes('var(--sv-accent-border)') && modelPool.includes('var(--sv-accent-soft)'), 'ModelPool governance actions should consume surface accent tokens')
assert(!modelPool.includes('border-[#d6a85f]/30 text-[#f1c16f]'), 'ModelPool governance actions must not keep retired amber-only styling')
assert(obs.includes('data-testid="obs-signal-board"'), 'OBS should expose a visual signal board before dense evidence rows')
assert(obs.includes('Scheduler SLO') && obs.includes('Data Quality') && obs.includes('Deploy Gate') && obs.includes('OBS Events'), 'OBS signal board should compress scheduler, data-quality, deploy, and event state into visual metrics')
assert(obs.includes('sv-content-card') && obs.includes('sv-disclosure'), 'OBS overview cards and drilldown rows should consume operations surface tokens')
assert(scheduler.includes('data-testid="scheduler-signal-board"'), 'Scheduler drilldown should expose a visual signal board before run rows')
assert(scheduler.includes('sv-content-card') && scheduler.includes('sv-muted-text') && scheduler.includes('sv-accent-text'), 'Scheduler drilldown should consume operations surface tokens')
assert(schedulerChart.includes('Scheduler Visual Workbench') && schedulerChart.includes('sv-content-card'), 'Scheduler visual workbench should consume route-level surface cards')
assert(dataQuality.includes('data-testid="data-quality-signal-board"'), 'Data Quality drilldown should expose a visual signal board before dense checks')
assert(dataQuality.includes('sv-content-card') && dataQuality.includes('sv-muted-text') && dataQuality.includes('sv-accent-text'), 'Data Quality drilldown should consume operations surface tokens')
assert(dataQuality.includes('border-[color:var(--sv-accent-border)]') && dataQuality.includes('bg-[color:var(--sv-accent-soft)]'), 'Data Quality actions should consume operations accent tokens')
assert(dataQualityChart.includes('Data Quality Visual Workbench') && dataQualityChart.includes('sv-content-card'), 'Data Quality visual workbench should consume route-level surface cards')
assert(dataQualityChart.includes('Current API data is a snapshot, not a historical trend'), 'Data Quality visual workbench should disclose snapshot semantics')
assert(bot.includes('sv-login-panel'), 'Bot logged-out preview should consume the private execution surface theme')
assert(bot.includes('sv-content-card'), 'Bot holdings and order summaries should consume surface content cards')
assert(bot.includes('sv-content-card-selected'), 'Bot selected execution/staging cards should consume selected surface content cards')
assert(bot.includes('sv-surface-chip-accent'), 'Bot rank/action chips should consume surface accent chips')
assert(bot.includes('sv-disclosure'), 'Bot raw table disclosures should consume surface disclosure tokens')
assert(strategyLab.includes('data-testid="strategy-signal-board"'), 'Strategy Lab should expose a visual signal board before dense research controls')
assert(strategyLab.includes('WorkstationPageTitle') && strategyLab.includes('sv-content-card') && strategyLab.includes('sv-accent-text'), 'Strategy Lab should consume the research route surface theme')
assert(strategyLab.includes('border-[color:var(--sv-accent-border)]') && strategyLab.includes('bg-[color:var(--sv-accent-soft)]'), 'Strategy Lab refresh action should consume research accent tokens')
assert(strategyChart.includes('Strategy Visual Workbench') && strategyChart.includes('sv-content-card'), 'Strategy Lab visual workbench should consume route-level surface cards')
assert(pipeline.includes('pipeline-compression-visual') && pipeline.includes('sv-content-card-selected'), 'Pipeline compression map should consume the active pipeline surface theme')
assert(pipeline.includes('sv-page-title') && pipeline.includes('sv-login-panel'), 'Pipeline header and login surfaces should consume route-level surface tokens')
assert(inspector.includes('visual-inspector-summary') && inspector.includes('sv-content-card-selected'), 'Inspector visual summary should consume selected surface cards')
assert(inspector.includes('sv-surface-input') && inspector.includes('sv-data-table-head') && inspector.includes('sv-data-table-body'), 'Inspector search and raw table should consume surface input/table tokens')
assert(!inspector.includes('border-[#d6a85f]/30 text-[#f1c16f]'), 'Inspector refresh action must not keep retired amber-only styling')
